// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminBookingStats = `-- name: AdminBookingStats :one
SELECT
    count(*)                                                                       AS total,
    count(*) FILTER (WHERE created_at >= now() - interval '7 days')                 AS this_week,
    coalesce(sum(price_minor) FILTER (WHERE status IN ('confirmed', 'completed')), 0)::bigint AS gmv_minor
FROM bookings
`

type AdminBookingStatsRow struct {
	Total    int64
	ThisWeek int64
	GmvMinor int64
}

// gmv_minor = money that actually flowed: bookings that reached confirmed or
// completed. this_week = created in the last 7 days.
func (q *Queries) AdminBookingStats(ctx context.Context) (AdminBookingStatsRow, error) {
	row := q.db.QueryRow(ctx, adminBookingStats)
	var i AdminBookingStatsRow
	err := row.Scan(&i.Total, &i.ThisWeek, &i.GmvMinor)
	return i, err
}

const adminCountTeachers = `-- name: AdminCountTeachers :one
SELECT count(*)
FROM teachers t
LEFT JOIN users u ON u.id = t.user_id
WHERE ($1::text IS NULL OR t.status = $1::text)
  AND (
      $2::text IS NULL
      OR t.display_name ILIKE '%' || $2 || '%'
      OR t.slug ILIKE '%' || $2 || '%'
      OR u.email ILIKE '%' || $2 || '%'
  )
`

type AdminCountTeachersParams struct {
	Status pgtype.Text
	Q      pgtype.Text
}

func (q *Queries) AdminCountTeachers(ctx context.Context, arg AdminCountTeachersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountTeachers, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT count(*)
FROM users u
WHERE (
    $1::text IS NULL
    OR u.email ILIKE '%' || $1 || '%'
    OR u.display_name ILIKE '%' || $1 || '%'
)
`

func (q *Queries) AdminCountUsers(ctx context.Context, q_ pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetTeacherModeration = `-- name: AdminGetTeacherModeration :one
SELECT
    t.id, t.status, t.verified, t.moderation_note,
    u.id           AS owner_id,
    u.email        AS owner_email,
    u.display_name AS owner_display_name
FROM teachers t
LEFT JOIN users u ON u.id = t.user_id
WHERE t.slug = $1
`

type AdminGetTeacherModerationRow struct {
	ID               uuid.UUID
	Status           string
	Verified         bool
	ModerationNote   string
	OwnerID          uuid.NullUUID
	OwnerEmail       pgtype.Text
	OwnerDisplayName pgtype.Text
}

func (q *Queries) AdminGetTeacherModeration(ctx context.Context, slug string) (AdminGetTeacherModerationRow, error) {
	row := q.db.QueryRow(ctx, adminGetTeacherModeration, slug)
	var i AdminGetTeacherModerationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Verified,
		&i.ModerationNote,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.OwnerDisplayName,
	)
	return i, err
}

const adminGetUser = `-- name: AdminGetUser :one
SELECT id, email, display_name, created_at FROM users WHERE id = $1
`

type AdminGetUserRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) AdminGetUser(ctx context.Context, id uuid.UUID) (AdminGetUserRow, error) {
	row := q.db.QueryRow(ctx, adminGetUser, id)
	var i AdminGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const adminGetUserTeacherProfile = `-- name: AdminGetUserTeacherProfile :one
SELECT slug, status, verified FROM teachers WHERE user_id = $1
`

type AdminGetUserTeacherProfileRow struct {
	Slug     string
	Status   string
	Verified bool
}

func (q *Queries) AdminGetUserTeacherProfile(ctx context.Context, userID uuid.NullUUID) (AdminGetUserTeacherProfileRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserTeacherProfile, userID)
	var i AdminGetUserTeacherProfileRow
	err := row.Scan(&i.Slug, &i.Status, &i.Verified)
	return i, err
}

const adminListTeachers = `-- name: AdminListTeachers :many
SELECT
    t.slug, t.display_name, t.status, t.verified, t.headline, t.country_name, t.created_at,
    u.id    AS owner_id,
    u.email AS owner_email
FROM teachers t
LEFT JOIN users u ON u.id = t.user_id
WHERE ($1::text IS NULL OR t.status = $1::text)
  AND (
      $2::text IS NULL
      OR t.display_name ILIKE '%' || $2 || '%'
      OR t.slug ILIKE '%' || $2 || '%'
      OR u.email ILIKE '%' || $2 || '%'
  )
ORDER BY t.created_at DESC, t.id
LIMIT $4::int OFFSET $3::int
`

type AdminListTeachersParams struct {
	Status     pgtype.Text
	Q          pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type AdminListTeachersRow struct {
	Slug        string
	DisplayName string
	Status      string
	Verified    bool
	Headline    string
	CountryName string
	CreatedAt   pgtype.Timestamptz
	OwnerID     uuid.NullUUID
	OwnerEmail  pgtype.Text
}

func (q *Queries) AdminListTeachers(ctx context.Context, arg AdminListTeachersParams) ([]AdminListTeachersRow, error) {
	rows, err := q.db.Query(ctx, adminListTeachers,
		arg.Status,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTeachersRow{}
	for rows.Next() {
		var i AdminListTeachersRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.Verified,
			&i.Headline,
			&i.CountryName,
			&i.CreatedAt,
			&i.OwnerID,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserBookings = `-- name: AdminListUserBookings :many
SELECT
    b.id, b.status, b.start_at, b.price_minor, b.currency,
    b.student_id,
    t.user_id       AS teacher_user_id,
    t.display_name  AS teacher_display_name,
    s.display_name  AS student_display_name
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    s ON s.id = b.student_id
WHERE b.student_id = $1 OR t.user_id = $1
ORDER BY b.created_at DESC, b.id
LIMIT 50
`

type AdminListUserBookingsRow struct {
	ID                 uuid.UUID
	Status             string
	StartAt            pgtype.Timestamptz
	PriceMinor         int64
	Currency           string
	StudentID          uuid.UUID
	TeacherUserID      uuid.NullUUID
	TeacherDisplayName string
	StudentDisplayName string
}

// The 50 newest bookings the user takes part in, as student or as teacher-owner.
func (q *Queries) AdminListUserBookings(ctx context.Context, studentID uuid.UUID) ([]AdminListUserBookingsRow, error) {
	rows, err := q.db.Query(ctx, adminListUserBookings, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserBookingsRow{}
	for rows.Next() {
		var i AdminListUserBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartAt,
			&i.PriceMinor,
			&i.Currency,
			&i.StudentID,
			&i.TeacherUserID,
			&i.TeacherDisplayName,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT
    u.id, u.email, u.display_name, u.created_at,
    EXISTS (SELECT 1 FROM teachers t WHERE t.user_id = u.id)          AS is_teacher,
    (SELECT count(*) FROM bookings b WHERE b.student_id = u.id)::bigint AS booking_count
FROM users u
WHERE (
    $1::text IS NULL
    OR u.email ILIKE '%' || $1 || '%'
    OR u.display_name ILIKE '%' || $1 || '%'
)
ORDER BY u.created_at DESC, u.id
LIMIT $3::int OFFSET $2::int
`

type AdminListUsersParams struct {
	Q          pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type AdminListUsersRow struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	CreatedAt    pgtype.Timestamptz
	IsTeacher    bool
	BookingCount int64
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.IsTeacher,
			&i.BookingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetTeacherStatus = `-- name: AdminSetTeacherStatus :exec
UPDATE teachers
SET status = $2, moderation_note = $3, updated_at = now()
WHERE slug = $1
`

type AdminSetTeacherStatusParams struct {
	Slug           string
	Status         string
	ModerationNote string
}

func (q *Queries) AdminSetTeacherStatus(ctx context.Context, arg AdminSetTeacherStatusParams) error {
	_, err := q.db.Exec(ctx, adminSetTeacherStatus, arg.Slug, arg.Status, arg.ModerationNote)
	return err
}

const adminSetTeacherVerified = `-- name: AdminSetTeacherVerified :exec
UPDATE teachers
SET verified = $2, updated_at = now()
WHERE slug = $1
`

type AdminSetTeacherVerifiedParams struct {
	Slug     string
	Verified bool
}

func (q *Queries) AdminSetTeacherVerified(ctx context.Context, arg AdminSetTeacherVerifiedParams) error {
	_, err := q.db.Exec(ctx, adminSetTeacherVerified, arg.Slug, arg.Verified)
	return err
}

const adminTeacherCounts = `-- name: AdminTeacherCounts :one
SELECT
    count(*)                                        AS total,
    count(*) FILTER (WHERE status = 'pending')      AS pending
FROM teachers
`

type AdminTeacherCountsRow struct {
	Total   int64
	Pending int64
}

func (q *Queries) AdminTeacherCounts(ctx context.Context) (AdminTeacherCountsRow, error) {
	row := q.db.QueryRow(ctx, adminTeacherCounts)
	var i AdminTeacherCountsRow
	err := row.Scan(&i.Total, &i.Pending)
	return i, err
}

const adminUserCount = `-- name: AdminUserCount :one

SELECT count(*) FROM users
`

// Admin module (phase A/B): read-across-tables queries for the ops dashboard and
// the moderation write path. This is an internal tool behind auth.RequireAdmin,
// so it reads other modules' tables directly rather than routing through their
// services.
func (q *Queries) AdminUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminUserPaymentsSummary = `-- name: AdminUserPaymentsSummary :one
SELECT
    coalesce(sum(p.amount_minor) FILTER (WHERE p.status = 'authorized'), 0)::bigint AS authorized_minor,
    coalesce(sum(p.amount_minor) FILTER (WHERE p.status = 'captured'),   0)::bigint AS captured_minor,
    coalesce(sum(p.amount_minor) FILTER (WHERE p.status = 'refunded'),   0)::bigint AS refunded_minor,
    coalesce(max(p.currency), 'UZS')::text                                          AS currency
FROM payments p
JOIN bookings b ON b.id = p.booking_id
WHERE b.student_id = $1
`

type AdminUserPaymentsSummaryRow struct {
	AuthorizedMinor int64
	CapturedMinor   int64
	RefundedMinor   int64
	Currency        string
}

// The user's payments as the paying student, bucketed by current payment state.
func (q *Queries) AdminUserPaymentsSummary(ctx context.Context, studentID uuid.UUID) (AdminUserPaymentsSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminUserPaymentsSummary, studentID)
	var i AdminUserPaymentsSummaryRow
	err := row.Scan(
		&i.AuthorizedMinor,
		&i.CapturedMinor,
		&i.RefundedMinor,
		&i.Currency,
	)
	return i, err
}

const adminUserRoles = `-- name: AdminUserRoles :many
SELECT r.id, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

type AdminUserRolesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) AdminUserRoles(ctx context.Context, userID uuid.UUID) ([]AdminUserRolesRow, error) {
	rows, err := q.db.Query(ctx, adminUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserRolesRow{}
	for rows.Next() {
		var i AdminUserRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
