// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminBookingStats = `-- name: AdminBookingStats :one
SELECT
    count(*)                                                                                 AS total,
    count(*) FILTER (WHERE created_at >= now() - interval '7 days')                           AS this_week,
    count(*) FILTER (WHERE status = 'confirmed' AND start_at > now())                         AS upcoming,
    count(*) FILTER (WHERE status = 'completed')                                              AS completed,
    count(*) FILTER (WHERE status = 'cancelled')                                              AS cancelled,
    count(DISTINCT student_id)                                                                AS active_students,
    coalesce(sum(price_minor) FILTER (WHERE status IN ('confirmed', 'completed')), 0)::bigint AS gmv_minor
FROM bookings
`

type AdminBookingStatsRow struct {
	Total          int64
	ThisWeek       int64
	Upcoming       int64
	Completed      int64
	Cancelled      int64
	ActiveStudents int64
	GmvMinor       int64
}

// gmv_minor = booking price that actually flowed: bookings that reached
// confirmed or completed. this_week = created in the last 7 days. upcoming =
// confirmed and not yet started. active_students = distinct people who booked.
func (q *Queries) AdminBookingStats(ctx context.Context) (AdminBookingStatsRow, error) {
	row := q.db.QueryRow(ctx, adminBookingStats)
	var i AdminBookingStatsRow
	err := row.Scan(
		&i.Total,
		&i.ThisWeek,
		&i.Upcoming,
		&i.Completed,
		&i.Cancelled,
		&i.ActiveStudents,
		&i.GmvMinor,
	)
	return i, err
}

const adminCountBookings = `-- name: AdminCountBookings :one
SELECT count(*)
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    s ON s.id = b.student_id
WHERE ($1::text IS NULL OR b.status = $1::text)
  AND (
      $2::text IS NULL
      OR t.display_name ILIKE '%' || $2 || '%'
      OR t.slug ILIKE '%' || $2 || '%'
      OR s.email ILIKE '%' || $2 || '%'
      OR s.display_name ILIKE '%' || $2 || '%'
  )
`

type AdminCountBookingsParams struct {
	Status pgtype.Text
	Q      pgtype.Text
}

func (q *Queries) AdminCountBookings(ctx context.Context, arg AdminCountBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountBookings, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountTeachers = `-- name: AdminCountTeachers :one
SELECT count(*)
FROM teachers t
LEFT JOIN users u ON u.id = t.user_id
WHERE ($1::text IS NULL OR t.status = $1::text)
  AND (
      $2::text IS NULL
      OR t.display_name ILIKE '%' || $2 || '%'
      OR t.slug ILIKE '%' || $2 || '%'
      OR u.email ILIKE '%' || $2 || '%'
  )
`

type AdminCountTeachersParams struct {
	Status pgtype.Text
	Q      pgtype.Text
}

func (q *Queries) AdminCountTeachers(ctx context.Context, arg AdminCountTeachersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountTeachers, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT count(*)
FROM users u
WHERE (
    $1::text IS NULL
    OR u.email ILIKE '%' || $1 || '%'
    OR u.display_name ILIKE '%' || $1 || '%'
)
`

func (q *Queries) AdminCountUsers(ctx context.Context, q_ pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetBooking = `-- name: AdminGetBooking :one
SELECT
    b.id, b.status, b.start_at, b.end_at, b.duration_minutes, b.is_trial,
    b.price_minor, b.currency, b.created_at,
    b.cancelled_at, b.cancellation_reason, b.cancelled_by, b.no_show_party,
    COALESCE(NULLIF(b.meeting_url_override, ''), t.meeting_url)::text AS meeting_url,
    t.slug              AS teacher_slug,
    t.display_name      AS teacher_display_name,
    s.id                AS student_id,
    s.email::text       AS student_email,
    s.display_name      AS student_display_name,
    COALESCE(p.status, '')::text        AS payment_status,
    COALESCE(p.amount_minor, 0)::bigint AS payment_amount_minor,
    COALESCE(p.currency, '')::text      AS payment_currency,
    EXISTS (SELECT 1 FROM disputes d WHERE d.booking_id = b.id AND d.status = 'open') AS has_open_dispute
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    s ON s.id = b.student_id
LEFT JOIN payments p ON p.booking_id = b.id
WHERE b.id = $1
`

type AdminGetBookingRow struct {
	ID                 uuid.UUID
	Status             string
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	DurationMinutes    int32
	IsTrial            bool
	PriceMinor         int64
	Currency           string
	CreatedAt          pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason string
	CancelledBy        string
	NoShowParty        string
	MeetingUrl         string
	TeacherSlug        string
	TeacherDisplayName string
	StudentID          uuid.UUID
	StudentEmail       string
	StudentDisplayName string
	PaymentStatus      string
	PaymentAmountMinor int64
	PaymentCurrency    string
	HasOpenDispute     bool
}

// One booking with everything the operator detail view shows: the list-row
// fields plus the lifecycle extras, the effective meeting link (the per-booking
// override if set, else the teacher's default), and the payment detail.
func (q *Queries) AdminGetBooking(ctx context.Context, id uuid.UUID) (AdminGetBookingRow, error) {
	row := q.db.QueryRow(ctx, adminGetBooking, id)
	var i AdminGetBookingRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.DurationMinutes,
		&i.IsTrial,
		&i.PriceMinor,
		&i.Currency,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.NoShowParty,
		&i.MeetingUrl,
		&i.TeacherSlug,
		&i.TeacherDisplayName,
		&i.StudentID,
		&i.StudentEmail,
		&i.StudentDisplayName,
		&i.PaymentStatus,
		&i.PaymentAmountMinor,
		&i.PaymentCurrency,
		&i.HasOpenDispute,
	)
	return i, err
}

const adminGetTeacherModeration = `-- name: AdminGetTeacherModeration :one
SELECT
    t.id, t.status, t.verified, t.moderation_note,
    u.id           AS owner_id,
    u.email        AS owner_email,
    u.display_name AS owner_display_name
FROM teachers t
LEFT JOIN users u ON u.id = t.user_id
WHERE t.slug = $1
`

type AdminGetTeacherModerationRow struct {
	ID               uuid.UUID
	Status           string
	Verified         bool
	ModerationNote   string
	OwnerID          uuid.NullUUID
	OwnerEmail       pgtype.Text
	OwnerDisplayName pgtype.Text
}

func (q *Queries) AdminGetTeacherModeration(ctx context.Context, slug string) (AdminGetTeacherModerationRow, error) {
	row := q.db.QueryRow(ctx, adminGetTeacherModeration, slug)
	var i AdminGetTeacherModerationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Verified,
		&i.ModerationNote,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.OwnerDisplayName,
	)
	return i, err
}

const adminGetUser = `-- name: AdminGetUser :one
SELECT id, email, display_name, created_at FROM users WHERE id = $1
`

type AdminGetUserRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) AdminGetUser(ctx context.Context, id uuid.UUID) (AdminGetUserRow, error) {
	row := q.db.QueryRow(ctx, adminGetUser, id)
	var i AdminGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const adminGetUserTeacherProfile = `-- name: AdminGetUserTeacherProfile :one
SELECT slug, status, verified FROM teachers WHERE user_id = $1
`

type AdminGetUserTeacherProfileRow struct {
	Slug     string
	Status   string
	Verified bool
}

func (q *Queries) AdminGetUserTeacherProfile(ctx context.Context, userID uuid.NullUUID) (AdminGetUserTeacherProfileRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserTeacherProfile, userID)
	var i AdminGetUserTeacherProfileRow
	err := row.Scan(&i.Slug, &i.Status, &i.Verified)
	return i, err
}

const adminListBookingDisputes = `-- name: AdminListBookingDisputes :many
SELECT
    d.id, d.booking_id, d.raised_by, d.reason, d.status, d.resolution,
    d.resolved_by, d.created_at, d.resolved_at,
    ru.display_name                     AS raised_by_display_name,
    COALESCE(su.display_name, '')::text AS resolved_by_display_name
FROM disputes d
JOIN users ru ON ru.id = d.raised_by
LEFT JOIN users su ON su.id = d.resolved_by
WHERE d.booking_id = $1
ORDER BY d.created_at DESC, d.id
`

type AdminListBookingDisputesRow struct {
	ID                    uuid.UUID
	BookingID             uuid.UUID
	RaisedBy              uuid.UUID
	Reason                string
	Status                string
	Resolution            string
	ResolvedBy            uuid.NullUUID
	CreatedAt             pgtype.Timestamptz
	ResolvedAt            pgtype.Timestamptz
	RaisedByDisplayName   string
	ResolvedByDisplayName string
}

// The booking's full dispute thread, newest first. Read straight from the
// disputes table: the admin surface is an ops tool, not a public API (see the
// package doc), so it does not route this through the disputes service.
func (q *Queries) AdminListBookingDisputes(ctx context.Context, bookingID uuid.UUID) ([]AdminListBookingDisputesRow, error) {
	rows, err := q.db.Query(ctx, adminListBookingDisputes, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListBookingDisputesRow{}
	for rows.Next() {
		var i AdminListBookingDisputesRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.RaisedBy,
			&i.Reason,
			&i.Status,
			&i.Resolution,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.RaisedByDisplayName,
			&i.ResolvedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListBookings = `-- name: AdminListBookings :many

SELECT
    b.id, b.status, b.start_at, b.end_at, b.price_minor, b.currency, b.created_at,
    t.slug              AS teacher_slug,
    t.display_name      AS teacher_display_name,
    s.id                AS student_id,
    s.email::text       AS student_email,
    s.display_name      AS student_display_name,
    COALESCE(p.status, '')::text AS payment_status,
    EXISTS (SELECT 1 FROM disputes d WHERE d.booking_id = b.id AND d.status = 'open') AS has_open_dispute
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    s ON s.id = b.student_id
LEFT JOIN payments p ON p.booking_id = b.id
WHERE ($1::text IS NULL OR b.status = $1::text)
  AND (
      $2::text IS NULL
      OR t.display_name ILIKE '%' || $2 || '%'
      OR t.slug ILIKE '%' || $2 || '%'
      OR s.email ILIKE '%' || $2 || '%'
      OR s.display_name ILIKE '%' || $2 || '%'
  )
ORDER BY b.start_at DESC, b.id
LIMIT $4::int OFFSET $3::int
`

type AdminListBookingsParams struct {
	Status     pgtype.Text
	Q          pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type AdminListBookingsRow struct {
	ID                 uuid.UUID
	Status             string
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	PriceMinor         int64
	Currency           string
	CreatedAt          pgtype.Timestamptz
	TeacherSlug        string
	TeacherDisplayName string
	StudentID          uuid.UUID
	StudentEmail       string
	StudentDisplayName string
	PaymentStatus      string
	HasOpenDispute     bool
}

// --- phase D: bookings admin ---
// Every booking on the platform (not just the caller's), newest lesson first.
// `status` is an optional exact filter; `q` matches the teacher's display name
// or slug and the student's email or display name. payment_status is ” when the
// booking has no intent yet (payments.booking_id is UNIQUE, so the LEFT JOIN
// cannot fan the row set out).
func (q *Queries) AdminListBookings(ctx context.Context, arg AdminListBookingsParams) ([]AdminListBookingsRow, error) {
	rows, err := q.db.Query(ctx, adminListBookings,
		arg.Status,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListBookingsRow{}
	for rows.Next() {
		var i AdminListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.PriceMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.TeacherSlug,
			&i.TeacherDisplayName,
			&i.StudentID,
			&i.StudentEmail,
			&i.StudentDisplayName,
			&i.PaymentStatus,
			&i.HasOpenDispute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTeachers = `-- name: AdminListTeachers :many
SELECT
    t.slug, t.display_name, t.status, t.verified, t.headline, t.country_name, t.created_at,
    u.id    AS owner_id,
    u.email AS owner_email
FROM teachers t
LEFT JOIN users u ON u.id = t.user_id
WHERE ($1::text IS NULL OR t.status = $1::text)
  AND (
      $2::text IS NULL
      OR t.display_name ILIKE '%' || $2 || '%'
      OR t.slug ILIKE '%' || $2 || '%'
      OR u.email ILIKE '%' || $2 || '%'
  )
ORDER BY t.created_at DESC, t.id
LIMIT $4::int OFFSET $3::int
`

type AdminListTeachersParams struct {
	Status     pgtype.Text
	Q          pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type AdminListTeachersRow struct {
	Slug        string
	DisplayName string
	Status      string
	Verified    bool
	Headline    string
	CountryName string
	CreatedAt   pgtype.Timestamptz
	OwnerID     uuid.NullUUID
	OwnerEmail  pgtype.Text
}

func (q *Queries) AdminListTeachers(ctx context.Context, arg AdminListTeachersParams) ([]AdminListTeachersRow, error) {
	rows, err := q.db.Query(ctx, adminListTeachers,
		arg.Status,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTeachersRow{}
	for rows.Next() {
		var i AdminListTeachersRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Status,
			&i.Verified,
			&i.Headline,
			&i.CountryName,
			&i.CreatedAt,
			&i.OwnerID,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUserBookings = `-- name: AdminListUserBookings :many
SELECT
    b.id, b.status, b.start_at, b.price_minor, b.currency,
    b.student_id,
    t.user_id       AS teacher_user_id,
    t.display_name  AS teacher_display_name,
    s.display_name  AS student_display_name
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    s ON s.id = b.student_id
WHERE b.student_id = $1 OR t.user_id = $1
ORDER BY b.created_at DESC, b.id
LIMIT 50
`

type AdminListUserBookingsRow struct {
	ID                 uuid.UUID
	Status             string
	StartAt            pgtype.Timestamptz
	PriceMinor         int64
	Currency           string
	StudentID          uuid.UUID
	TeacherUserID      uuid.NullUUID
	TeacherDisplayName string
	StudentDisplayName string
}

// The 50 newest bookings the user takes part in, as student or as teacher-owner.
func (q *Queries) AdminListUserBookings(ctx context.Context, studentID uuid.UUID) ([]AdminListUserBookingsRow, error) {
	rows, err := q.db.Query(ctx, adminListUserBookings, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserBookingsRow{}
	for rows.Next() {
		var i AdminListUserBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartAt,
			&i.PriceMinor,
			&i.Currency,
			&i.StudentID,
			&i.TeacherUserID,
			&i.TeacherDisplayName,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT
    u.id, u.email, u.display_name, u.created_at,
    EXISTS (SELECT 1 FROM teachers t WHERE t.user_id = u.id)          AS is_teacher,
    (SELECT count(*) FROM bookings b WHERE b.student_id = u.id)::bigint AS booking_count
FROM users u
WHERE (
    $1::text IS NULL
    OR u.email ILIKE '%' || $1 || '%'
    OR u.display_name ILIKE '%' || $1 || '%'
)
ORDER BY u.created_at DESC, u.id
LIMIT $3::int OFFSET $2::int
`

type AdminListUsersParams struct {
	Q          pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type AdminListUsersRow struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	CreatedAt    pgtype.Timestamptz
	IsTeacher    bool
	BookingCount int64
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Q, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.IsTeacher,
			&i.BookingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminOpenDisputeCount = `-- name: AdminOpenDisputeCount :one
SELECT count(*) FROM disputes WHERE status = 'open'
`

func (q *Queries) AdminOpenDisputeCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminOpenDisputeCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminPaymentStats = `-- name: AdminPaymentStats :one
SELECT
    coalesce(sum(amount_minor) FILTER (WHERE status = 'captured'), 0)::bigint AS captured_minor,
    coalesce(sum(amount_minor) FILTER (WHERE status = 'refunded'), 0)::bigint AS refunded_minor
FROM payments
`

type AdminPaymentStatsRow struct {
	CapturedMinor int64
	RefundedMinor int64
}

// Money the platform actually moved: captured = collected from students,
// refunded = returned to them.
func (q *Queries) AdminPaymentStats(ctx context.Context) (AdminPaymentStatsRow, error) {
	row := q.db.QueryRow(ctx, adminPaymentStats)
	var i AdminPaymentStatsRow
	err := row.Scan(&i.CapturedMinor, &i.RefundedMinor)
	return i, err
}

const adminPayoutStats = `-- name: AdminPayoutStats :one
SELECT
    coalesce(sum(amount_minor) FILTER (WHERE state IN ('held', 'available')), 0)::bigint AS owed_minor,
    coalesce(sum(amount_minor) FILTER (WHERE state = 'paid'), 0)::bigint                 AS paid_minor
FROM payout_ledger
`

type AdminPayoutStatsRow struct {
	OwedMinor int64
	PaidMinor int64
}

// owed_minor = earned by teachers but not yet disbursed (held or cleared);
// paid_minor = disbursed by past payout runs. Reversed rows count towards none.
func (q *Queries) AdminPayoutStats(ctx context.Context) (AdminPayoutStatsRow, error) {
	row := q.db.QueryRow(ctx, adminPayoutStats)
	var i AdminPayoutStatsRow
	err := row.Scan(&i.OwedMinor, &i.PaidMinor)
	return i, err
}

const adminReviewStats = `-- name: AdminReviewStats :one
SELECT
    count(*) FILTER (WHERE NOT hidden)                                                   AS visible_total,
    coalesce(round(avg(rating) FILTER (WHERE NOT hidden), 1), 0)::double precision        AS average_rating
FROM reviews
`

type AdminReviewStatsRow struct {
	VisibleTotal  int64
	AverageRating float64
}

// Visible reviews only (hidden ones are off the platform). average_rating is
// rounded to one decimal, 0 when there are none.
func (q *Queries) AdminReviewStats(ctx context.Context) (AdminReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, adminReviewStats)
	var i AdminReviewStatsRow
	err := row.Scan(&i.VisibleTotal, &i.AverageRating)
	return i, err
}

const adminSetTeacherStatus = `-- name: AdminSetTeacherStatus :exec
UPDATE teachers
SET status = $2, moderation_note = $3, updated_at = now()
WHERE slug = $1
`

type AdminSetTeacherStatusParams struct {
	Slug           string
	Status         string
	ModerationNote string
}

func (q *Queries) AdminSetTeacherStatus(ctx context.Context, arg AdminSetTeacherStatusParams) error {
	_, err := q.db.Exec(ctx, adminSetTeacherStatus, arg.Slug, arg.Status, arg.ModerationNote)
	return err
}

const adminSetTeacherVerified = `-- name: AdminSetTeacherVerified :exec
UPDATE teachers
SET verified = $2, updated_at = now()
WHERE slug = $1
`

type AdminSetTeacherVerifiedParams struct {
	Slug     string
	Verified bool
}

func (q *Queries) AdminSetTeacherVerified(ctx context.Context, arg AdminSetTeacherVerifiedParams) error {
	_, err := q.db.Exec(ctx, adminSetTeacherVerified, arg.Slug, arg.Verified)
	return err
}

const adminTeacherStats = `-- name: AdminTeacherStats :one
SELECT
    count(*)                                     AS total,
    count(*) FILTER (WHERE status = 'pending')   AS pending,
    count(*) FILTER (WHERE status = 'approved')  AS approved,
    count(*) FILTER (WHERE verified)             AS verified
FROM teachers
`

type AdminTeacherStatsRow struct {
	Total    int64
	Pending  int64
	Approved int64
	Verified int64
}

func (q *Queries) AdminTeacherStats(ctx context.Context) (AdminTeacherStatsRow, error) {
	row := q.db.QueryRow(ctx, adminTeacherStats)
	var i AdminTeacherStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Approved,
		&i.Verified,
	)
	return i, err
}

const adminUserPaymentsSummary = `-- name: AdminUserPaymentsSummary :one
SELECT
    coalesce(sum(p.amount_minor) FILTER (WHERE p.status = 'authorized'), 0)::bigint AS authorized_minor,
    coalesce(sum(p.amount_minor) FILTER (WHERE p.status = 'captured'),   0)::bigint AS captured_minor,
    coalesce(sum(p.amount_minor) FILTER (WHERE p.status = 'refunded'),   0)::bigint AS refunded_minor,
    coalesce(max(p.currency), 'UZS')::text                                          AS currency
FROM payments p
JOIN bookings b ON b.id = p.booking_id
WHERE b.student_id = $1
`

type AdminUserPaymentsSummaryRow struct {
	AuthorizedMinor int64
	CapturedMinor   int64
	RefundedMinor   int64
	Currency        string
}

// The user's payments as the paying student, bucketed by current payment state.
func (q *Queries) AdminUserPaymentsSummary(ctx context.Context, studentID uuid.UUID) (AdminUserPaymentsSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminUserPaymentsSummary, studentID)
	var i AdminUserPaymentsSummaryRow
	err := row.Scan(
		&i.AuthorizedMinor,
		&i.CapturedMinor,
		&i.RefundedMinor,
		&i.Currency,
	)
	return i, err
}

const adminUserRoles = `-- name: AdminUserRoles :many
SELECT r.id, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

type AdminUserRolesRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) AdminUserRoles(ctx context.Context, userID uuid.UUID) ([]AdminUserRolesRow, error) {
	rows, err := q.db.Query(ctx, adminUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserRolesRow{}
	for rows.Next() {
		var i AdminUserRolesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUserStats = `-- name: AdminUserStats :one


SELECT
    count(*)                                                       AS total,
    count(*) FILTER (WHERE created_at >= now() - interval '7 days') AS this_week
FROM users
`

type AdminUserStatsRow struct {
	Total    int64
	ThisWeek int64
}

// Admin module (phase A/B): read-across-tables queries for the ops dashboard and
// the moderation write path. This is an internal tool behind auth.RequireAdmin,
// so it reads other modules' tables directly rather than routing through their
// services.
// The dashboard counters (GET /v1/admin/metrics) are six small aggregate reads,
// one per area. Each is cheap (a single sequential scan of one table); the
// dashboard is a rare, operator-only call.
func (q *Queries) AdminUserStats(ctx context.Context) (AdminUserStatsRow, error) {
	row := q.db.QueryRow(ctx, adminUserStats)
	var i AdminUserStatsRow
	err := row.Scan(&i.Total, &i.ThisWeek)
	return i, err
}
