// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :exec
UPDATE auth_tokens SET consumed_at = now()
WHERE token_sha256 = $1 AND consumed_at IS NULL
`

// Spend a token by its hash (the redeem flows already hold the hash, not the id).
func (q *Queries) ConsumeAuthToken(ctx context.Context, tokenSha256 []byte) error {
	_, err := q.db.Exec(ctx, consumeAuthToken, tokenSha256)
	return err
}

const consumeUserAuthTokens = `-- name: ConsumeUserAuthTokens :exec
UPDATE auth_tokens SET consumed_at = now()
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type ConsumeUserAuthTokensParams struct {
	UserID  uuid.UUID
	Purpose string
}

// Invalidate a user's outstanding tokens of a purpose before issuing a new one,
// so only the newest link works.
func (q *Queries) ConsumeUserAuthTokens(ctx context.Context, arg ConsumeUserAuthTokensParams) error {
	_, err := q.db.Exec(ctx, consumeUserAuthTokens, arg.UserID, arg.Purpose)
	return err
}

const createAuthToken = `-- name: CreateAuthToken :one

INSERT INTO auth_tokens (user_id, purpose, token_sha256, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAuthTokenParams struct {
	UserID      uuid.UUID
	Purpose     string
	TokenSha256 []byte
	ExpiresAt   pgtype.Timestamptz
}

// --- account-recovery link tokens (migration 000013) ---
func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenSha256,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token_hash, expires_at, revoked_at, replaced_by, user_agent, created_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
	UserAgent        string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
}

type CreateUserRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Auth module: user accounts and refresh-token sessions.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

// Seed-only. teachers.user_id references users, so callers must clear teachers
// first.
func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllUsers)
	return err
}

const getLiveAuthToken = `-- name: GetLiveAuthToken :one
SELECT id, user_id
FROM auth_tokens
WHERE token_sha256 = $1 AND purpose = $2
  AND consumed_at IS NULL AND expires_at > now()
`

type GetLiveAuthTokenParams struct {
	TokenSha256 []byte
	Purpose     string
}

type GetLiveAuthTokenRow struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// A token that can still be redeemed: matches the hash + purpose, not consumed,
// not expired.
func (q *Queries) GetLiveAuthToken(ctx context.Context, arg GetLiveAuthTokenParams) (GetLiveAuthTokenRow, error) {
	row := q.db.QueryRow(ctx, getLiveAuthToken, arg.TokenSha256, arg.Purpose)
	var i GetLiveAuthTokenRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, expires_at, revoked_at, replaced_by, user_agent, created_at
FROM sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, email_verified_at, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, email_verified_at, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestAuthTokenAt = `-- name: LatestAuthTokenAt :one
SELECT coalesce(max(created_at), 'epoch'::timestamptz)::timestamptz AS latest
FROM auth_tokens
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type LatestAuthTokenAtParams struct {
	UserID  uuid.UUID
	Purpose string
}

// The most recent still-live token of a purpose for a user — drives the "one was
// just sent, don't send another" cooldown. No row -> zero time.
func (q *Queries) LatestAuthTokenAt(ctx context.Context, arg LatestAuthTokenAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestAuthTokenAt, arg.UserID, arg.Purpose)
	var latest pgtype.Timestamptz
	err := row.Scan(&latest)
	return latest, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified_at = coalesce(email_verified_at, now()), updated_at = now()
WHERE id = $1
`

// Idempotent: keeps the first verification time if the row is already verified.
func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Reuse-detection hammer: kills every still-active session for a user.
func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now(), replaced_by = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ReplacedBy uuid.NullUUID
	ID         uuid.UUID
}

// Marks a session revoked and records the session that replaced it (rotation).
// No-op if it was already revoked.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ReplacedBy, arg.ID)
	return err
}

const seedMarkEmailVerified = `-- name: SeedMarkEmailVerified :exec
UPDATE users SET email_verified_at = now() WHERE email_verified_at IS NULL
`

// Seed-only: stamp every demo account verified so the nudge banner is quiet.
func (q *Queries) SeedMarkEmailVerified(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedMarkEmailVerified)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

// Password reset: replace the hash and bump updated_at. The caller also revokes
// every session in the same transaction.
func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, email_verified_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID
	DisplayName string
}

type UpdateUserRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Edit the caller's own account. Email is immutable here (changing it needs a
// verification flow that does not exist yet).
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
