// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addAvailabilitySlot = `-- name: AddAvailabilitySlot :exec
INSERT INTO teacher_availability_slots (teacher_id, weekday, start_minute, end_minute)
VALUES ($1, $2, $3, $4)
`

type AddAvailabilitySlotParams struct {
	TeacherID   uuid.UUID
	Weekday     int16
	StartMinute int32
	EndMinute   int32
}

func (q *Queries) AddAvailabilitySlot(ctx context.Context, arg AddAvailabilitySlotParams) error {
	_, err := q.db.Exec(ctx, addAvailabilitySlot,
		arg.TeacherID,
		arg.Weekday,
		arg.StartMinute,
		arg.EndMinute,
	)
	return err
}

const deleteAvailabilitySlots = `-- name: DeleteAvailabilitySlots :exec
DELETE FROM teacher_availability_slots WHERE teacher_id = $1
`

func (q *Queries) DeleteAvailabilitySlots(ctx context.Context, teacherID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvailabilitySlots, teacherID)
	return err
}

const getTeacherAvailabilityContext = `-- name: GetTeacherAvailabilityContext :one

SELECT id, slug, timezone FROM teachers WHERE slug = $1
`

type GetTeacherAvailabilityContextRow struct {
	ID       uuid.UUID
	Slug     string
	Timezone string
}

// Availability module: a teacher's weekly recurring slots (UTC minutes).
// Resolve a slug to the teacher id and timezone the availability endpoints need.
func (q *Queries) GetTeacherAvailabilityContext(ctx context.Context, slug string) (GetTeacherAvailabilityContextRow, error) {
	row := q.db.QueryRow(ctx, getTeacherAvailabilityContext, slug)
	var i GetTeacherAvailabilityContextRow
	err := row.Scan(&i.ID, &i.Slug, &i.Timezone)
	return i, err
}

const listAvailabilitySlots = `-- name: ListAvailabilitySlots :many
SELECT weekday, start_minute, end_minute
FROM teacher_availability_slots
WHERE teacher_id = $1
ORDER BY weekday, start_minute
`

type ListAvailabilitySlotsRow struct {
	Weekday     int16
	StartMinute int32
	EndMinute   int32
}

func (q *Queries) ListAvailabilitySlots(ctx context.Context, teacherID uuid.UUID) ([]ListAvailabilitySlotsRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilitySlots, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilitySlotsRow{}
	for rows.Next() {
		var i ListAvailabilitySlotsRow
		if err := rows.Scan(&i.Weekday, &i.StartMinute, &i.EndMinute); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
