// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings
SET status = 'cancelled', cancelled_at = now(), cancellation_reason = $2,
    cancelled_by = $3, cancellation_outcome = $4, updated_at = now()
WHERE id = $1
`

type CancelBookingParams struct {
	ID                  uuid.UUID
	CancellationReason  string
	CancelledBy         string
	CancellationOutcome string
}

// cancelled_by records WHO cancelled: 'student', 'teacher' (includes a teacher
// no-show) or 'admin' (the operator force-cancel override); cancellation_outcome
// what happened to the money (refunded / forfeited / unpaid, see migration
// 000027). The service picks both values; the columns' CHECK constraints are
// the guard.
func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) error {
	_, err := q.db.Exec(ctx, cancelBooking,
		arg.ID,
		arg.CancellationReason,
		arg.CancelledBy,
		arg.CancellationOutcome,
	)
	return err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    teacher_id, student_id, start_at, end_at,
    duration_minutes, status, price_minor, currency, is_trial, lesson_type_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10
)
RETURNING id
`

type CreateBookingParams struct {
	TeacherID       uuid.UUID
	StudentID       uuid.UUID
	StartAt         pgtype.Timestamptz
	EndAt           pgtype.Timestamptz
	DurationMinutes int32
	Status          string
	PriceMinor      int64
	Currency        string
	IsTrial         bool
	LessonTypeID    uuid.NullUUID
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.TeacherID,
		arg.StudentID,
		arg.StartAt,
		arg.EndAt,
		arg.DurationMinutes,
		arg.Status,
		arg.PriceMinor,
		arg.Currency,
		arg.IsTrial,
		arg.LessonTypeID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllBookings = `-- name: DeleteAllBookings :exec
DELETE FROM bookings
`

// Seed-only. bookings.teacher_id / student_id reference teachers / users with
// no ON DELETE CASCADE, so the seed must clear bookings before those tables.
func (q *Queries) DeleteAllBookings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllBookings)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT
    b.id, b.teacher_id, b.student_id, b.start_at, b.end_at,
    b.duration_minutes, b.status, b.price_minor, b.currency, b.is_trial,
    b.cancelled_at, b.cancellation_reason, b.cancelled_by, b.cancellation_outcome,
    b.reschedule_count, b.rescheduled_from,
    b.created_at, b.updated_at,
    b.meeting_url_override,
    b.no_show_party,
    b.lesson_type_id,
    lt.title          AS lesson_type_title,
    t.slug            AS teacher_slug,
    t.display_name    AS teacher_display_name,
    t.timezone        AS teacher_timezone,
    t.avatar_url      AS teacher_avatar_url,
    t.user_id         AS teacher_user_id,
    t.meeting_url     AS teacher_meeting_url,
    COALESCE(tu.email, '')::text AS teacher_email,
    COALESCE(tu.locale, 'en')::text AS teacher_locale,
    u.display_name    AS student_display_name,
    u.email::text     AS student_email,
    u.locale::text    AS student_locale
FROM bookings b
LEFT JOIN lesson_types lt ON lt.id = b.lesson_type_id
JOIN teachers t ON t.id = b.teacher_id
JOIN users    u ON u.id = b.student_id
LEFT JOIN users tu ON tu.id = t.user_id
WHERE b.id = $1
`

type GetBookingByIDRow struct {
	ID                  uuid.UUID
	TeacherID           uuid.UUID
	StudentID           uuid.UUID
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	DurationMinutes     int32
	Status              string
	PriceMinor          int64
	Currency            string
	IsTrial             bool
	CancelledAt         pgtype.Timestamptz
	CancellationReason  string
	CancelledBy         string
	CancellationOutcome string
	RescheduleCount     int32
	RescheduledFrom     pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	MeetingUrlOverride  string
	NoShowParty         string
	LessonTypeID        uuid.NullUUID
	LessonTypeTitle     pgtype.Text
	TeacherSlug         string
	TeacherDisplayName  string
	TeacherTimezone     string
	TeacherAvatarUrl    string
	TeacherUserID       uuid.NullUUID
	TeacherMeetingUrl   string
	TeacherEmail        string
	TeacherLocale       string
	StudentDisplayName  string
	StudentEmail        string
	StudentLocale       string
}

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.StudentID,
		&i.StartAt,
		&i.EndAt,
		&i.DurationMinutes,
		&i.Status,
		&i.PriceMinor,
		&i.Currency,
		&i.IsTrial,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.CancellationOutcome,
		&i.RescheduleCount,
		&i.RescheduledFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MeetingUrlOverride,
		&i.NoShowParty,
		&i.LessonTypeID,
		&i.LessonTypeTitle,
		&i.TeacherSlug,
		&i.TeacherDisplayName,
		&i.TeacherTimezone,
		&i.TeacherAvatarUrl,
		&i.TeacherUserID,
		&i.TeacherMeetingUrl,
		&i.TeacherEmail,
		&i.TeacherLocale,
		&i.StudentDisplayName,
		&i.StudentEmail,
		&i.StudentLocale,
	)
	return i, err
}

const getBookingTeacherContext = `-- name: GetBookingTeacherContext :one

SELECT id, slug, display_name, timezone, avatar_url,
       price_per_hour_minor, trial_price_minor, currency, user_id, meeting_url
FROM teachers
WHERE slug = $1 AND status = 'approved'
`

type GetBookingTeacherContextRow struct {
	ID                uuid.UUID
	Slug              string
	DisplayName       string
	Timezone          string
	AvatarUrl         string
	PricePerHourMinor int64
	TrialPriceMinor   pgtype.Int8
	Currency          CurrencyCode
	UserID            uuid.NullUUID
	MeetingUrl        string
}

// Booking module: concrete scheduled lessons. Times are UTC timestamptz. The
// recurring weekly availability is read via the availability queries; here we
// only need the teacher context, existing bookings for overlap checks, and the
// booking rows themselves (joined to a light teacher + student summary so the
// frontend lists avoid N+1 calls).
// Slug -> everything the booking flow needs: identity, timezone, pricing, and
// the owning account (drives the "can't book yourself" check).
// Only an approved (publicly visible) teacher can be booked. A non-approved slug
// returns no rows here, so the booking flow treats it as "no such teacher": 404
// on GET /v1/teachers/{slug}/slots and 404 teacher_not_found on POST /v1/bookings.
func (q *Queries) GetBookingTeacherContext(ctx context.Context, slug string) (GetBookingTeacherContextRow, error) {
	row := q.db.QueryRow(ctx, getBookingTeacherContext, slug)
	var i GetBookingTeacherContextRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Timezone,
		&i.AvatarUrl,
		&i.PricePerHourMinor,
		&i.TrialPriceMinor,
		&i.Currency,
		&i.UserID,
		&i.MeetingUrl,
	)
	return i, err
}

const getStudentTrialBooking = `-- name: GetStudentTrialBooking :one
SELECT id
FROM bookings
WHERE teacher_id = $1
  AND student_id = $2
  AND is_trial
  AND status <> 'cancelled'
ORDER BY created_at
LIMIT 1
`

type GetStudentTrialBookingParams struct {
	TeacherID uuid.UUID
	StudentID uuid.UUID
}

// The trial a student already holds with a teacher, if any. Mirrors the
// partial unique index bookings_one_trial_per_student_idx: cancelled trials
// do not count, everything else does.
func (q *Queries) GetStudentTrialBooking(ctx context.Context, arg GetStudentTrialBookingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getStudentTrialBooking, arg.TeacherID, arg.StudentID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTeacherIDByOwner = `-- name: GetTeacherIDByOwner :one
SELECT id FROM teachers WHERE user_id = $1
`

// The teacher profile owned by an account (one per user), or no rows.
func (q *Queries) GetTeacherIDByOwner(ctx context.Context, userID uuid.NullUUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTeacherIDByOwner, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listBookings = `-- name: ListBookings :many
SELECT
    b.id, b.teacher_id, b.student_id, b.start_at, b.end_at,
    b.duration_minutes, b.status, b.price_minor, b.currency, b.is_trial,
    b.cancelled_at, b.cancellation_reason, b.cancelled_by, b.cancellation_outcome,
    b.reschedule_count, b.rescheduled_from,
    b.created_at, b.updated_at,
    b.meeting_url_override,
    b.no_show_party,
    b.lesson_type_id,
    lt.title          AS lesson_type_title,
    t.slug            AS teacher_slug,
    t.display_name    AS teacher_display_name,
    t.timezone        AS teacher_timezone,
    t.avatar_url      AS teacher_avatar_url,
    t.user_id         AS teacher_user_id,
    t.meeting_url     AS teacher_meeting_url,
    COALESCE(tu.email, '')::text AS teacher_email,
    COALESCE(tu.locale, 'en')::text AS teacher_locale,
    u.display_name    AS student_display_name,
    u.email::text     AS student_email,
    u.locale::text    AS student_locale
FROM bookings b
LEFT JOIN lesson_types lt ON lt.id = b.lesson_type_id
JOIN teachers t ON t.id = b.teacher_id
JOIN users    u ON u.id = b.student_id
LEFT JOIN users tu ON tu.id = t.user_id
WHERE (b.student_id = $1 OR b.teacher_id = $2)
  AND ($3::text IS NULL OR b.status = $3::text)
ORDER BY b.start_at DESC, b.id
`

type ListBookingsParams struct {
	StudentFilter uuid.UUID
	TeacherFilter uuid.UUID
	Status        pgtype.Text
}

type ListBookingsRow struct {
	ID                  uuid.UUID
	TeacherID           uuid.UUID
	StudentID           uuid.UUID
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	DurationMinutes     int32
	Status              string
	PriceMinor          int64
	Currency            string
	IsTrial             bool
	CancelledAt         pgtype.Timestamptz
	CancellationReason  string
	CancelledBy         string
	CancellationOutcome string
	RescheduleCount     int32
	RescheduledFrom     pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	MeetingUrlOverride  string
	NoShowParty         string
	LessonTypeID        uuid.NullUUID
	LessonTypeTitle     pgtype.Text
	TeacherSlug         string
	TeacherDisplayName  string
	TeacherTimezone     string
	TeacherAvatarUrl    string
	TeacherUserID       uuid.NullUUID
	TeacherMeetingUrl   string
	TeacherEmail        string
	TeacherLocale       string
	StudentDisplayName  string
	StudentEmail        string
	StudentLocale       string
}

// Bookings the caller participates in. Pass the caller's user id as
// student_filter and/or the caller-owned teacher id as teacher_filter; use the
// all-zero uuid for a dimension that should not match. Newest lesson first.
func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings, arg.StudentFilter, arg.TeacherFilter, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsRow{}
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.StudentID,
			&i.StartAt,
			&i.EndAt,
			&i.DurationMinutes,
			&i.Status,
			&i.PriceMinor,
			&i.Currency,
			&i.IsTrial,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.CancellationOutcome,
			&i.RescheduleCount,
			&i.RescheduledFrom,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MeetingUrlOverride,
			&i.NoShowParty,
			&i.LessonTypeID,
			&i.LessonTypeTitle,
			&i.TeacherSlug,
			&i.TeacherDisplayName,
			&i.TeacherTimezone,
			&i.TeacherAvatarUrl,
			&i.TeacherUserID,
			&i.TeacherMeetingUrl,
			&i.TeacherEmail,
			&i.TeacherLocale,
			&i.StudentDisplayName,
			&i.StudentEmail,
			&i.StudentLocale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherBookingIntervals = `-- name: ListTeacherBookingIntervals :many
SELECT start_at, end_at
FROM bookings
WHERE teacher_id = $1
  AND status <> 'cancelled'
  AND start_at < $2
  AND end_at   > $3
ORDER BY start_at
`

type ListTeacherBookingIntervalsParams struct {
	TeacherID   uuid.UUID
	WindowEnd   pgtype.Timestamptz
	WindowStart pgtype.Timestamptz
}

type ListTeacherBookingIntervalsRow struct {
	StartAt pgtype.Timestamptz
	EndAt   pgtype.Timestamptz
}

// Non-cancelled bookings for a teacher that overlap the [from, to) window, for
// server-side slot generation and the pre-insert bookability re-check.
func (q *Queries) ListTeacherBookingIntervals(ctx context.Context, arg ListTeacherBookingIntervalsParams) ([]ListTeacherBookingIntervalsRow, error) {
	rows, err := q.db.Query(ctx, listTeacherBookingIntervals, arg.TeacherID, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherBookingIntervalsRow{}
	for rows.Next() {
		var i ListTeacherBookingIntervalsRow
		if err := rows.Scan(&i.StartAt, &i.EndAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleBooking = `-- name: RescheduleBooking :exec
UPDATE bookings
SET rescheduled_from = start_at,
    start_at = $2,
    end_at = $3,
    reschedule_count = reschedule_count + 1,
    updated_at = now()
WHERE id = $1
`

type RescheduleBookingParams struct {
	ID      uuid.UUID
	StartAt pgtype.Timestamptz
	EndAt   pgtype.Timestamptz
}

// Moves a lesson. The EXCLUDE constraints re-check both parties' calendars on
// the UPDATE, so a clash surfaces as 23P01 exactly as on insert.
func (q *Queries) RescheduleBooking(ctx context.Context, arg RescheduleBookingParams) error {
	_, err := q.db.Exec(ctx, rescheduleBooking, arg.ID, arg.StartAt, arg.EndAt)
	return err
}

const seedInsertBooking = `-- name: SeedInsertBooking :one
INSERT INTO bookings (
    teacher_id, student_id, start_at, end_at,
    duration_minutes, status, price_minor, currency, is_trial, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, false, $9
)
RETURNING id
`

type SeedInsertBookingParams struct {
	TeacherID       uuid.UUID
	StudentID       uuid.UUID
	StartAt         pgtype.Timestamptz
	EndAt           pgtype.Timestamptz
	DurationMinutes int32
	Status          string
	PriceMinor      int64
	Currency        string
	CreatedAt       pgtype.Timestamptz
}

// Seed-only: a booking in an explicit lifecycle state (the API path always
// starts at pending_payment). Used to give the admin / dispute demo data
// something to point at on a fresh database.
func (q *Queries) SeedInsertBooking(ctx context.Context, arg SeedInsertBookingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, seedInsertBooking,
		arg.TeacherID,
		arg.StudentID,
		arg.StartAt,
		arg.EndAt,
		arg.DurationMinutes,
		arg.Status,
		arg.PriceMinor,
		arg.Currency,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setBookingMeetingLinkOverride = `-- name: SetBookingMeetingLinkOverride :exec
UPDATE bookings SET meeting_url_override = $2, updated_at = now() WHERE id = $1
`

type SetBookingMeetingLinkOverrideParams struct {
	ID                 uuid.UUID
	MeetingUrlOverride string
}

// Per-booking meeting link override. An empty string clears it (fall back to the
// teacher's default meeting_url).
func (q *Queries) SetBookingMeetingLinkOverride(ctx context.Context, arg SetBookingMeetingLinkOverrideParams) error {
	_, err := q.db.Exec(ctx, setBookingMeetingLinkOverride, arg.ID, arg.MeetingUrlOverride)
	return err
}

const setBookingNoShowParty = `-- name: SetBookingNoShowParty :exec
UPDATE bookings SET no_show_party = $2, updated_at = now() WHERE id = $1
`

type SetBookingNoShowPartyParams struct {
	ID          uuid.UUID
	NoShowParty string
}

// Records who missed the lesson. The status transition (completed on a student
// no-show, cancelled on a teacher no-show) is applied separately via
// SetBookingStatus / CancelBooking so the capture / refund path is reused.
func (q *Queries) SetBookingNoShowParty(ctx context.Context, arg SetBookingNoShowPartyParams) error {
	_, err := q.db.Exec(ctx, setBookingNoShowParty, arg.ID, arg.NoShowParty)
	return err
}

const setBookingStatus = `-- name: SetBookingStatus :exec
UPDATE bookings SET status = $2, updated_at = now() WHERE id = $1
`

type SetBookingStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) error {
	_, err := q.db.Exec(ctx, setBookingStatus, arg.ID, arg.Status)
	return err
}
