// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings
SET status = 'cancelled', cancelled_at = now(), cancellation_reason = $2, updated_at = now()
WHERE id = $1
`

type CancelBookingParams struct {
	ID                 uuid.UUID
	CancellationReason string
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) error {
	_, err := q.db.Exec(ctx, cancelBooking, arg.ID, arg.CancellationReason)
	return err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    teacher_id, student_id, start_at, end_at,
    duration_minutes, status, price_minor, currency, is_trial
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
RETURNING id
`

type CreateBookingParams struct {
	TeacherID       uuid.UUID
	StudentID       uuid.UUID
	StartAt         pgtype.Timestamptz
	EndAt           pgtype.Timestamptz
	DurationMinutes int32
	Status          string
	PriceMinor      int64
	Currency        string
	IsTrial         bool
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.TeacherID,
		arg.StudentID,
		arg.StartAt,
		arg.EndAt,
		arg.DurationMinutes,
		arg.Status,
		arg.PriceMinor,
		arg.Currency,
		arg.IsTrial,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllBookings = `-- name: DeleteAllBookings :exec
DELETE FROM bookings
`

// Seed-only. bookings.teacher_id / student_id reference teachers / users with
// no ON DELETE CASCADE, so the seed must clear bookings before those tables.
func (q *Queries) DeleteAllBookings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllBookings)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT
    b.id, b.teacher_id, b.student_id, b.start_at, b.end_at,
    b.duration_minutes, b.status, b.price_minor, b.currency, b.is_trial,
    b.cancelled_at, b.cancellation_reason, b.created_at, b.updated_at,
    b.meeting_url_override,
    b.no_show_party,
    t.slug            AS teacher_slug,
    t.display_name    AS teacher_display_name,
    t.timezone        AS teacher_timezone,
    t.avatar_url      AS teacher_avatar_url,
    t.user_id         AS teacher_user_id,
    t.meeting_url     AS teacher_meeting_url,
    COALESCE(tu.email, '')::text AS teacher_email,
    u.display_name    AS student_display_name,
    u.email::text     AS student_email
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    u ON u.id = b.student_id
LEFT JOIN users tu ON tu.id = t.user_id
WHERE b.id = $1
`

type GetBookingByIDRow struct {
	ID                 uuid.UUID
	TeacherID          uuid.UUID
	StudentID          uuid.UUID
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	DurationMinutes    int32
	Status             string
	PriceMinor         int64
	Currency           string
	IsTrial            bool
	CancelledAt        pgtype.Timestamptz
	CancellationReason string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	MeetingUrlOverride string
	NoShowParty        string
	TeacherSlug        string
	TeacherDisplayName string
	TeacherTimezone    string
	TeacherAvatarUrl   string
	TeacherUserID      uuid.NullUUID
	TeacherMeetingUrl  string
	TeacherEmail       string
	StudentDisplayName string
	StudentEmail       string
}

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.StudentID,
		&i.StartAt,
		&i.EndAt,
		&i.DurationMinutes,
		&i.Status,
		&i.PriceMinor,
		&i.Currency,
		&i.IsTrial,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MeetingUrlOverride,
		&i.NoShowParty,
		&i.TeacherSlug,
		&i.TeacherDisplayName,
		&i.TeacherTimezone,
		&i.TeacherAvatarUrl,
		&i.TeacherUserID,
		&i.TeacherMeetingUrl,
		&i.TeacherEmail,
		&i.StudentDisplayName,
		&i.StudentEmail,
	)
	return i, err
}

const getBookingTeacherContext = `-- name: GetBookingTeacherContext :one

SELECT id, slug, display_name, timezone, avatar_url,
       price_per_hour_minor, trial_price_minor, currency, user_id, meeting_url
FROM teachers
WHERE slug = $1
`

type GetBookingTeacherContextRow struct {
	ID                uuid.UUID
	Slug              string
	DisplayName       string
	Timezone          string
	AvatarUrl         string
	PricePerHourMinor int64
	TrialPriceMinor   pgtype.Int8
	Currency          CurrencyCode
	UserID            uuid.NullUUID
	MeetingUrl        string
}

// Booking module: concrete scheduled lessons. Times are UTC timestamptz. The
// recurring weekly availability is read via the availability queries; here we
// only need the teacher context, existing bookings for overlap checks, and the
// booking rows themselves (joined to a light teacher + student summary so the
// frontend lists avoid N+1 calls).
// Slug -> everything the booking flow needs: identity, timezone, pricing, and
// the owning account (drives the "can't book yourself" check).
func (q *Queries) GetBookingTeacherContext(ctx context.Context, slug string) (GetBookingTeacherContextRow, error) {
	row := q.db.QueryRow(ctx, getBookingTeacherContext, slug)
	var i GetBookingTeacherContextRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Timezone,
		&i.AvatarUrl,
		&i.PricePerHourMinor,
		&i.TrialPriceMinor,
		&i.Currency,
		&i.UserID,
		&i.MeetingUrl,
	)
	return i, err
}

const getTeacherIDByOwner = `-- name: GetTeacherIDByOwner :one
SELECT id FROM teachers WHERE user_id = $1
`

// The teacher profile owned by an account (one per user), or no rows.
func (q *Queries) GetTeacherIDByOwner(ctx context.Context, userID uuid.NullUUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTeacherIDByOwner, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listBookings = `-- name: ListBookings :many
SELECT
    b.id, b.teacher_id, b.student_id, b.start_at, b.end_at,
    b.duration_minutes, b.status, b.price_minor, b.currency, b.is_trial,
    b.cancelled_at, b.cancellation_reason, b.created_at, b.updated_at,
    b.meeting_url_override,
    b.no_show_party,
    t.slug            AS teacher_slug,
    t.display_name    AS teacher_display_name,
    t.timezone        AS teacher_timezone,
    t.avatar_url      AS teacher_avatar_url,
    t.user_id         AS teacher_user_id,
    t.meeting_url     AS teacher_meeting_url,
    COALESCE(tu.email, '')::text AS teacher_email,
    u.display_name    AS student_display_name,
    u.email::text     AS student_email
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    u ON u.id = b.student_id
LEFT JOIN users tu ON tu.id = t.user_id
WHERE (b.student_id = $1 OR b.teacher_id = $2)
  AND ($3::text IS NULL OR b.status = $3::text)
ORDER BY b.start_at DESC, b.id
`

type ListBookingsParams struct {
	StudentFilter uuid.UUID
	TeacherFilter uuid.UUID
	Status        pgtype.Text
}

type ListBookingsRow struct {
	ID                 uuid.UUID
	TeacherID          uuid.UUID
	StudentID          uuid.UUID
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	DurationMinutes    int32
	Status             string
	PriceMinor         int64
	Currency           string
	IsTrial            bool
	CancelledAt        pgtype.Timestamptz
	CancellationReason string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	MeetingUrlOverride string
	NoShowParty        string
	TeacherSlug        string
	TeacherDisplayName string
	TeacherTimezone    string
	TeacherAvatarUrl   string
	TeacherUserID      uuid.NullUUID
	TeacherMeetingUrl  string
	TeacherEmail       string
	StudentDisplayName string
	StudentEmail       string
}

// Bookings the caller participates in. Pass the caller's user id as
// student_filter and/or the caller-owned teacher id as teacher_filter; use the
// all-zero uuid for a dimension that should not match. Newest lesson first.
func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings, arg.StudentFilter, arg.TeacherFilter, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsRow{}
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.StudentID,
			&i.StartAt,
			&i.EndAt,
			&i.DurationMinutes,
			&i.Status,
			&i.PriceMinor,
			&i.Currency,
			&i.IsTrial,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MeetingUrlOverride,
			&i.NoShowParty,
			&i.TeacherSlug,
			&i.TeacherDisplayName,
			&i.TeacherTimezone,
			&i.TeacherAvatarUrl,
			&i.TeacherUserID,
			&i.TeacherMeetingUrl,
			&i.TeacherEmail,
			&i.StudentDisplayName,
			&i.StudentEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherBookingIntervals = `-- name: ListTeacherBookingIntervals :many
SELECT start_at, end_at
FROM bookings
WHERE teacher_id = $1
  AND status <> 'cancelled'
  AND start_at < $2
  AND end_at   > $3
ORDER BY start_at
`

type ListTeacherBookingIntervalsParams struct {
	TeacherID   uuid.UUID
	WindowEnd   pgtype.Timestamptz
	WindowStart pgtype.Timestamptz
}

type ListTeacherBookingIntervalsRow struct {
	StartAt pgtype.Timestamptz
	EndAt   pgtype.Timestamptz
}

// Non-cancelled bookings for a teacher that overlap the [from, to) window, for
// server-side slot generation and the pre-insert bookability re-check.
func (q *Queries) ListTeacherBookingIntervals(ctx context.Context, arg ListTeacherBookingIntervalsParams) ([]ListTeacherBookingIntervalsRow, error) {
	rows, err := q.db.Query(ctx, listTeacherBookingIntervals, arg.TeacherID, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherBookingIntervalsRow{}
	for rows.Next() {
		var i ListTeacherBookingIntervalsRow
		if err := rows.Scan(&i.StartAt, &i.EndAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookingMeetingLinkOverride = `-- name: SetBookingMeetingLinkOverride :exec
UPDATE bookings SET meeting_url_override = $2, updated_at = now() WHERE id = $1
`

type SetBookingMeetingLinkOverrideParams struct {
	ID                 uuid.UUID
	MeetingUrlOverride string
}

// Per-booking meeting link override. An empty string clears it (fall back to the
// teacher's default meeting_url).
func (q *Queries) SetBookingMeetingLinkOverride(ctx context.Context, arg SetBookingMeetingLinkOverrideParams) error {
	_, err := q.db.Exec(ctx, setBookingMeetingLinkOverride, arg.ID, arg.MeetingUrlOverride)
	return err
}

const setBookingNoShowParty = `-- name: SetBookingNoShowParty :exec
UPDATE bookings SET no_show_party = $2, updated_at = now() WHERE id = $1
`

type SetBookingNoShowPartyParams struct {
	ID          uuid.UUID
	NoShowParty string
}

// Records who missed the lesson. The status transition (completed on a student
// no-show, cancelled on a teacher no-show) is applied separately via
// SetBookingStatus / CancelBooking so the capture / refund path is reused.
func (q *Queries) SetBookingNoShowParty(ctx context.Context, arg SetBookingNoShowPartyParams) error {
	_, err := q.db.Exec(ctx, setBookingNoShowParty, arg.ID, arg.NoShowParty)
	return err
}

const setBookingStatus = `-- name: SetBookingStatus :exec
UPDATE bookings SET status = $2, updated_at = now() WHERE id = $1
`

type SetBookingStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) error {
	_, err := q.db.Exec(ctx, setBookingStatus, arg.ID, arg.Status)
	return err
}
