// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCourseItem = `-- name: AddCourseItem :one

INSERT INTO course_items (section_id, kind, title, video_asset_id, resource_id, position, is_preview, duration_seconds)
VALUES (
    $1, $2, $3,
    $4, $5,
    COALESCE((SELECT max(position) + 1 FROM course_items WHERE section_id = $1), 0),
    $6, $7
)
RETURNING id, section_id, kind, title, video_asset_id, resource_id, position, created_at, is_preview, duration_seconds
`

type AddCourseItemParams struct {
	SectionID       uuid.UUID
	Kind            string
	Title           string
	VideoAssetID    uuid.NullUUID
	ResourceID      uuid.NullUUID
	IsPreview       bool
	DurationSeconds int32
}

// Items.
// position is the current item count for the section, same idiom as sections.
// is_preview / duration_seconds are phase-D1 video metadata; the service has
// already refused a preview or a duration on a non-video item before we get
// here, and the table's CHECKs are the backstop.
func (q *Queries) AddCourseItem(ctx context.Context, arg AddCourseItemParams) (CourseItem, error) {
	row := q.db.QueryRow(ctx, addCourseItem,
		arg.SectionID,
		arg.Kind,
		arg.Title,
		arg.VideoAssetID,
		arg.ResourceID,
		arg.IsPreview,
		arg.DurationSeconds,
	)
	var i CourseItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Kind,
		&i.Title,
		&i.VideoAssetID,
		&i.ResourceID,
		&i.Position,
		&i.CreatedAt,
		&i.IsPreview,
		&i.DurationSeconds,
	)
	return i, err
}

const addCourseSection = `-- name: AddCourseSection :one

INSERT INTO course_sections (course_id, title, position)
VALUES (
    $1, $2,
    COALESCE((SELECT max(position) + 1 FROM course_sections WHERE course_id = $1), 0)
)
RETURNING id, course_id, title, position, created_at, updated_at
`

type AddCourseSectionParams struct {
	CourseID uuid.UUID
	Title    string
}

// Sections.
// position is the current section count for the course, computed here so the
// insert stays a single statement (same idiom as AttachBookingResource).
func (q *Queries) AddCourseSection(ctx context.Context, arg AddCourseSectionParams) (CourseSection, error) {
	row := q.db.QueryRow(ctx, addCourseSection, arg.CourseID, arg.Title)
	var i CourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminCountCourses = `-- name: AdminCountCourses :one
SELECT count(*)
FROM courses c
JOIN teachers t ON t.id = c.teacher_id
WHERE ($1::text IS NULL
        OR ($1::text = 'archived' AND c.archived_at IS NOT NULL)
        OR ($1::text <> 'archived' AND c.status = $1::text AND c.archived_at IS NULL))
  AND ($2::bool IS NULL
        OR ($2::bool AND c.suspended_at IS NOT NULL)
        OR (NOT $2::bool AND c.suspended_at IS NULL))
  AND ($3::text IS NULL OR t.slug = $3::text)
  AND ($4::text IS NULL OR c.title ILIKE '%' || $4::text || '%')
`

type AdminCountCoursesParams struct {
	Status      pgtype.Text
	Suspended   pgtype.Bool
	TeacherSlug pgtype.Text
	Q           pgtype.Text
}

func (q *Queries) AdminCountCourses(ctx context.Context, arg AdminCountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountCourses,
		arg.Status,
		arg.Suspended,
		arg.TeacherSlug,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListCourses = `-- name: AdminListCourses :many

SELECT
    c.id, c.teacher_id, c.title, c.subtitle, c.description, c.cover_asset_id,
    c.price_amount_minor, c.price_currency, c.status, c.ever_published, c.archived_at,
    c.suspended_at, c.created_at, c.updated_at,
    t.slug AS teacher_slug, t.display_name AS teacher_display_name
FROM courses c
JOIN teachers t ON t.id = c.teacher_id
WHERE ($1::text IS NULL
        OR ($1::text = 'archived' AND c.archived_at IS NOT NULL)
        OR ($1::text <> 'archived' AND c.status = $1::text AND c.archived_at IS NULL))
  AND ($2::bool IS NULL
        OR ($2::bool AND c.suspended_at IS NOT NULL)
        OR (NOT $2::bool AND c.suspended_at IS NULL))
  AND ($3::text IS NULL OR t.slug = $3::text)
  AND ($4::text IS NULL OR c.title ILIKE '%' || $4::text || '%')
ORDER BY c.created_at DESC, c.id
LIMIT $6::int OFFSET $5::int
`

type AdminListCoursesParams struct {
	Status      pgtype.Text
	Suspended   pgtype.Bool
	TeacherSlug pgtype.Text
	Q           pgtype.Text
	PageOffset  int32
	PageLimit   int32
}

type AdminListCoursesRow struct {
	ID                 uuid.UUID
	TeacherID          uuid.UUID
	Title              string
	Subtitle           string
	Description        string
	CoverAssetID       uuid.NullUUID
	PriceAmountMinor   int64
	PriceCurrency      CurrencyCode
	Status             string
	EverPublished      bool
	ArchivedAt         pgtype.Timestamptz
	SuspendedAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	TeacherSlug        string
	TeacherDisplayName string
}

// Phase C3: admin moderation.
// The operator moderation queue: every course regardless of status/teacher/
// suspension, newest first. Filters mirror reviews' ModerationQuery shape:
// status ('draft'|'published'|'archived', "archived" meaning archived_at IS NOT
// NULL regardless of the underlying status column), suspended ('true'|'false'),
// teacher_slug, and a title substring q — each NULL/empty means "any".
func (q *Queries) AdminListCourses(ctx context.Context, arg AdminListCoursesParams) ([]AdminListCoursesRow, error) {
	rows, err := q.db.Query(ctx, adminListCourses,
		arg.Status,
		arg.Suspended,
		arg.TeacherSlug,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListCoursesRow{}
	for rows.Next() {
		var i AdminListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.CoverAssetID,
			&i.PriceAmountMinor,
			&i.PriceCurrency,
			&i.Status,
			&i.EverPublished,
			&i.ArchivedAt,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeacherSlug,
			&i.TeacherDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListCourses = `-- name: CatalogListCourses :many

SELECT
    c.id, c.teacher_id, c.title, c.subtitle, c.description, c.cover_asset_id,
    c.price_amount_minor, c.price_currency, c.status, c.ever_published, c.archived_at,
    c.suspended_at, c.created_at, c.updated_at,
    t.slug AS teacher_slug, t.display_name AS teacher_display_name,
    (SELECT count(*) FROM course_sections cs WHERE cs.course_id = c.id) AS section_count,
    (SELECT count(*) FROM course_items ci JOIN course_sections cs2 ON cs2.id = ci.section_id WHERE cs2.course_id = c.id) AS item_count,
    -- Phase D1 card metadata. The duration is summed on read rather than
    -- denormalised so it can never drift from the items. The card only needs
    -- to know *whether* a free preview exists (a badge); which item plays is
    -- the landing page's business, and its outline already carries per-item
    -- is_preview — so this stays a cheap non-null EXISTS.
    (SELECT COALESCE(sum(ci.duration_seconds), 0)::bigint FROM course_items ci JOIN course_sections cs3 ON cs3.id = ci.section_id WHERE cs3.course_id = c.id) AS total_duration_seconds,
    EXISTS(SELECT 1 FROM course_items ci JOIN course_sections cs4 ON cs4.id = ci.section_id WHERE cs4.course_id = c.id AND ci.is_preview) AS has_preview
FROM courses c
JOIN teachers t ON t.id = c.teacher_id
WHERE c.status = 'published' AND c.archived_at IS NULL AND c.suspended_at IS NULL AND t.status = 'approved'
  AND ($1::text IS NULL OR c.title ILIKE '%' || $1::text || '%' OR c.subtitle ILIKE '%' || $1::text || '%')
  AND ($2::bigint IS NULL OR c.price_amount_minor <= $2::bigint)
ORDER BY
    (CASE WHEN $3::text = 'price_asc'  THEN c.price_amount_minor END) ASC NULLS LAST,
    (CASE WHEN $3::text = 'price_desc' THEN c.price_amount_minor END) DESC NULLS LAST,
    c.created_at DESC, c.id
LIMIT $5::int OFFSET $4::int
`

type CatalogListCoursesParams struct {
	Q             pgtype.Text
	MaxPriceMinor pgtype.Int8
	Sort          string
	PageOffset    int32
	PageLimit     int32
}

type CatalogListCoursesRow struct {
	ID                   uuid.UUID
	TeacherID            uuid.UUID
	Title                string
	Subtitle             string
	Description          string
	CoverAssetID         uuid.NullUUID
	PriceAmountMinor     int64
	PriceCurrency        CurrencyCode
	Status               string
	EverPublished        bool
	ArchivedAt           pgtype.Timestamptz
	SuspendedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	TeacherSlug          string
	TeacherDisplayName   string
	SectionCount         int64
	ItemCount            int64
	TotalDurationSeconds int64
	HasPreview           bool
}

// Catalog: published, non-archived, non-suspended courses only, from an
// approved teacher (mirrors GetBookingTeacherContext's status = 'approved'
// gate — a suspended teacher's courses shouldn't surface in the public
// marketplace even if the course row itself is still 'published'). Phase C3
// adds suspended_at IS NULL: an operator takedown must 404 the storefront the
// same way an unpublished/archived course already does.
// sort: 'price_asc' | 'price_desc' | anything else (including "" / 'newest' /
// 'recommended' — there is no rating-based ranking for courses yet) falls
// back to newest-first. The two CASE columns are NULL for every row unless
// their own sort is selected, so they never affect ordering otherwise and the
// final created_at/id tiebreak always applies.
func (q *Queries) CatalogListCourses(ctx context.Context, arg CatalogListCoursesParams) ([]CatalogListCoursesRow, error) {
	rows, err := q.db.Query(ctx, catalogListCourses,
		arg.Q,
		arg.MaxPriceMinor,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListCoursesRow{}
	for rows.Next() {
		var i CatalogListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.CoverAssetID,
			&i.PriceAmountMinor,
			&i.PriceCurrency,
			&i.Status,
			&i.EverPublished,
			&i.ArchivedAt,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeacherSlug,
			&i.TeacherDisplayName,
			&i.SectionCount,
			&i.ItemCount,
			&i.TotalDurationSeconds,
			&i.HasPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeItemProgress = `-- name: CompleteItemProgress :one
INSERT INTO course_item_progress (enrollment_id, item_id, status, completed_at)
VALUES ($1, $2, 'completed', $3)
ON CONFLICT (enrollment_id, item_id) DO UPDATE SET
    status = 'completed',
    completed_at = COALESCE(course_item_progress.completed_at, $3),
    updated_at = now()
RETURNING id, enrollment_id, item_id, status, video_position_seconds, completed_at, updated_at
`

type CompleteItemProgressParams struct {
	EnrollmentID uuid.UUID
	ItemID       uuid.UUID
	CompletedAt  pgtype.Timestamptz
}

// Marks an item complete unconditionally (a course-embedded resource's
// submission reaching submitted/graded, via resources.CourseProgress). Never
// regresses video_position_seconds or an already-recorded completed_at.
func (q *Queries) CompleteItemProgress(ctx context.Context, arg CompleteItemProgressParams) (CourseItemProgress, error) {
	row := q.db.QueryRow(ctx, completeItemProgress, arg.EnrollmentID, arg.ItemID, arg.CompletedAt)
	var i CourseItemProgress
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.ItemID,
		&i.Status,
		&i.VideoPositionSeconds,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCatalogCourses = `-- name: CountCatalogCourses :one
SELECT count(*)
FROM courses c
JOIN teachers t ON t.id = c.teacher_id
WHERE c.status = 'published' AND c.archived_at IS NULL AND c.suspended_at IS NULL AND t.status = 'approved'
  AND ($1::text IS NULL OR c.title ILIKE '%' || $1::text || '%' OR c.subtitle ILIKE '%' || $1::text || '%')
  AND ($2::bigint IS NULL OR c.price_amount_minor <= $2::bigint)
`

type CountCatalogCoursesParams struct {
	Q             pgtype.Text
	MaxPriceMinor pgtype.Int8
}

func (q *Queries) CountCatalogCourses(ctx context.Context, arg CountCatalogCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogCourses, arg.Q, arg.MaxPriceMinor)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeacherCourses = `-- name: CountTeacherCourses :one
SELECT count(*)
FROM courses
WHERE teacher_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::bool OR archived_at IS NULL)
`

type CountTeacherCoursesParams struct {
	TeacherID       uuid.UUID
	Status          pgtype.Text
	IncludeArchived bool
}

func (q *Queries) CountTeacherCourses(ctx context.Context, arg CountTeacherCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeacherCourses, arg.TeacherID, arg.Status, arg.IncludeArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one

INSERT INTO courses (teacher_id, title, subtitle, description, price_amount_minor, price_currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at, suspended_at
`

type CreateCourseParams struct {
	TeacherID        uuid.UUID
	Title            string
	Subtitle         string
	Description      string
	PriceAmountMinor int64
	PriceCurrency    CurrencyCode
}

// Course authoring (phase C1): a teacher's courses, and the curriculum tree
// (sections -> items) each one owns.
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.TeacherID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const deleteAllCourseEnrollments = `-- name: DeleteAllCourseEnrollments :exec
DELETE FROM course_enrollments
`

func (q *Queries) DeleteAllCourseEnrollments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCourseEnrollments)
	return err
}

const deleteAllCourseItemProgress = `-- name: DeleteAllCourseItemProgress :exec

DELETE FROM course_item_progress
`

// Seed-only. FK order (deepest first): course_item_progress -> course_items/
// course_enrollments; submissions.enrollment_id -> course_enrollments (cleared
// by resources.DeleteAllSubmissions, called by cmd/seed before
// DeleteAllCourseEnrollments); course_enrollments -> courses/users;
// course_items -> course_sections; course_sections -> courses; courses ->
// teachers. cmd/seed clears all of these before DeleteAllTeachers/
// DeleteAllUsers, same "explicit, deepest-first" discipline as its existing
// booking/payment clearing.
func (q *Queries) DeleteAllCourseItemProgress(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCourseItemProgress)
	return err
}

const deleteAllCourseItems = `-- name: DeleteAllCourseItems :exec
DELETE FROM course_items
`

func (q *Queries) DeleteAllCourseItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCourseItems)
	return err
}

const deleteAllCourseSections = `-- name: DeleteAllCourseSections :exec
DELETE FROM course_sections
`

func (q *Queries) DeleteAllCourseSections(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCourseSections)
	return err
}

const deleteAllCourses = `-- name: DeleteAllCourses :exec
DELETE FROM courses
`

func (q *Queries) DeleteAllCourses(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCourses)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteCourseItem = `-- name: DeleteCourseItem :exec
DELETE FROM course_items WHERE id = $1
`

func (q *Queries) DeleteCourseItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseItem, id)
	return err
}

const deleteCourseSection = `-- name: DeleteCourseSection :exec
DELETE FROM course_sections WHERE id = $1
`

func (q *Queries) DeleteCourseSection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseSection, id)
	return err
}

const enrollmentGrantsResource = `-- name: EnrollmentGrantsResource :one
SELECT EXISTS(
    SELECT 1
    FROM course_enrollments e
    JOIN course_sections cs ON cs.course_id = e.course_id
    JOIN course_items ci ON ci.section_id = cs.id
    WHERE e.id = $1 AND ci.resource_id = $2
) AS granted
`

type EnrollmentGrantsResourceParams struct {
	EnrollmentID uuid.UUID
	ResourceID   uuid.NullUUID
}

// Does this enrollment's course actually embed resourceID as a curriculum
// item? The course-context equivalent of GetBookingResourceByPair's "is this
// actually attached" check.
func (q *Queries) EnrollmentGrantsResource(ctx context.Context, arg EnrollmentGrantsResourceParams) (bool, error) {
	row := q.db.QueryRow(ctx, enrollmentGrantsResource, arg.EnrollmentID, arg.ResourceID)
	var granted bool
	err := row.Scan(&granted)
	return granted, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, teacher_id, title, subtitle, description, cover_asset_id,
       price_amount_minor, price_currency, status, ever_published, archived_at,
       created_at, updated_at, suspended_at
FROM courses
WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getCourseItem = `-- name: GetCourseItem :one
SELECT id, section_id, kind, title, video_asset_id, resource_id, position, created_at, is_preview, duration_seconds
FROM course_items
WHERE id = $1
`

func (q *Queries) GetCourseItem(ctx context.Context, id uuid.UUID) (CourseItem, error) {
	row := q.db.QueryRow(ctx, getCourseItem, id)
	var i CourseItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Kind,
		&i.Title,
		&i.VideoAssetID,
		&i.ResourceID,
		&i.Position,
		&i.CreatedAt,
		&i.IsPreview,
		&i.DurationSeconds,
	)
	return i, err
}

const getCourseItemForEnrollmentResource = `-- name: GetCourseItemForEnrollmentResource :one
SELECT ci.id, ci.section_id, ci.kind, ci.title, ci.video_asset_id, ci.resource_id, ci.position, ci.created_at, ci.is_preview, ci.duration_seconds
FROM course_enrollments e
JOIN course_sections cs ON cs.course_id = e.course_id
JOIN course_items ci ON ci.section_id = cs.id
WHERE e.id = $1 AND ci.resource_id = $2
LIMIT 1
`

type GetCourseItemForEnrollmentResourceParams struct {
	EnrollmentID uuid.UUID
	ResourceID   uuid.NullUUID
}

// Resolves the curriculum item a course-context submission's resource
// corresponds to, scoped to the enrollment's own course. Backs
// resources.CourseProgress.ItemCompleted.
func (q *Queries) GetCourseItemForEnrollmentResource(ctx context.Context, arg GetCourseItemForEnrollmentResourceParams) (CourseItem, error) {
	row := q.db.QueryRow(ctx, getCourseItemForEnrollmentResource, arg.EnrollmentID, arg.ResourceID)
	var i CourseItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Kind,
		&i.Title,
		&i.VideoAssetID,
		&i.ResourceID,
		&i.Position,
		&i.CreatedAt,
		&i.IsPreview,
		&i.DurationSeconds,
	)
	return i, err
}

const getCourseSection = `-- name: GetCourseSection :one
SELECT id, course_id, title, position, created_at, updated_at
FROM course_sections
WHERE id = $1
`

func (q *Queries) GetCourseSection(ctx context.Context, id uuid.UUID) (CourseSection, error) {
	row := q.db.QueryRow(ctx, getCourseSection, id)
	var i CourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentByCourseAndStudent = `-- name: GetEnrollmentByCourseAndStudent :one
SELECT id, course_id, student_id, source, amount_paid_minor, currency, created_at
FROM course_enrollments
WHERE course_id = $1 AND student_id = $2
`

type GetEnrollmentByCourseAndStudentParams struct {
	CourseID  uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) GetEnrollmentByCourseAndStudent(ctx context.Context, arg GetEnrollmentByCourseAndStudentParams) (CourseEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByCourseAndStudent, arg.CourseID, arg.StudentID)
	var i CourseEnrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.Source,
		&i.AmountPaidMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentByID = `-- name: GetEnrollmentByID :one
SELECT id, course_id, student_id, source, amount_paid_minor, currency, created_at
FROM course_enrollments
WHERE id = $1
`

func (q *Queries) GetEnrollmentByID(ctx context.Context, id uuid.UUID) (CourseEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByID, id)
	var i CourseEnrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.Source,
		&i.AmountPaidMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentParticipants = `-- name: GetEnrollmentParticipants :one
SELECT t.user_id AS teacher_owner_id, e.student_id AS student_id
FROM course_enrollments e
JOIN courses c ON c.id = e.course_id
JOIN teachers t ON t.id = c.teacher_id
WHERE e.id = $1
`

type GetEnrollmentParticipantsRow struct {
	TeacherOwnerID uuid.NullUUID
	StudentID      uuid.UUID
}

// Resolves an enrollment's two participants for authorization: the course's
// teacher's owning account, and the enrolled student.
func (q *Queries) GetEnrollmentParticipants(ctx context.Context, id uuid.UUID) (GetEnrollmentParticipantsRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentParticipants, id)
	var i GetEnrollmentParticipantsRow
	err := row.Scan(&i.TeacherOwnerID, &i.StudentID)
	return i, err
}

const getPreviewItem = `-- name: GetPreviewItem :one

SELECT ci.id, ci.video_asset_id, ci.is_preview, ci.duration_seconds, ci.title,
       c.id AS course_id,
       (c.status = 'published' AND c.archived_at IS NULL AND c.suspended_at IS NULL AND t.status = 'approved') AS on_storefront
FROM course_items ci
JOIN course_sections cs ON cs.id = ci.section_id
JOIN courses c ON c.id = cs.course_id
JOIN teachers t ON t.id = c.teacher_id
WHERE ci.id = $1 AND c.id = $2
`

type GetPreviewItemParams struct {
	ItemID   uuid.UUID
	CourseID uuid.UUID
}

type GetPreviewItemRow struct {
	ID              uuid.UUID
	VideoAssetID    uuid.NullUUID
	IsPreview       bool
	DurationSeconds int32
	Title           string
	CourseID        uuid.UUID
	OnStorefront    pgtype.Bool
}

// Phase D1: free preview lessons.
// Resolves a course item for the PUBLIC preview stream, returning everything
// the access decision needs in one query so the handler can't accidentally
// check a subset: the item's own preview flag and video asset, plus the
// storefront gates (published, not archived, not suspended, approved teacher)
// of the course it actually belongs to. The course_id predicate is what stops
// a caller pairing a preview item id with an unrelated published course id.
func (q *Queries) GetPreviewItem(ctx context.Context, arg GetPreviewItemParams) (GetPreviewItemRow, error) {
	row := q.db.QueryRow(ctx, getPreviewItem, arg.ItemID, arg.CourseID)
	var i GetPreviewItemRow
	err := row.Scan(
		&i.ID,
		&i.VideoAssetID,
		&i.IsPreview,
		&i.DurationSeconds,
		&i.Title,
		&i.CourseID,
		&i.OnStorefront,
	)
	return i, err
}

const getTeacherOwnerID = `-- name: GetTeacherOwnerID :one

SELECT user_id FROM teachers WHERE id = $1
`

// Phase C2: public catalog, purchase/enrollment, the student player, and
// progress tracking.
// The account that owns a teacher profile (the reverse of GetTeacherIDByOwner).
// Used to resolve who to authorize as "the teacher" for a course (e.g. an
// enrollment's grading authorization) without joining through users elsewhere.
func (q *Queries) GetTeacherOwnerID(ctx context.Context, id uuid.UUID) (uuid.NullUUID, error) {
	row := q.db.QueryRow(ctx, getTeacherOwnerID, id)
	var user_id uuid.NullUUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getTeacherSummary = `-- name: GetTeacherSummary :one
SELECT id, slug, display_name, (status = 'approved') AS approved FROM teachers WHERE id = $1
`

type GetTeacherSummaryRow struct {
	ID          uuid.UUID
	Slug        string
	DisplayName string
	Approved    bool
}

func (q *Queries) GetTeacherSummary(ctx context.Context, id uuid.UUID) (GetTeacherSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTeacherSummary, id)
	var i GetTeacherSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Approved,
	)
	return i, err
}

const insertEnrollment = `-- name: InsertEnrollment :one

INSERT INTO course_enrollments (course_id, student_id, source, amount_paid_minor, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, student_id, source, amount_paid_minor, currency, created_at
`

type InsertEnrollmentParams struct {
	CourseID        uuid.UUID
	StudentID       uuid.UUID
	Source          string
	AmountPaidMinor int64
	Currency        CurrencyCode
}

// Enrollment.
// Insert-first idempotency: a duplicate (course_id, student_id) raises
// SQLSTATE 23505 on the table's UNIQUE constraint, mapped by the repository
// to load-and-return the existing row instead — never check-then-insert.
func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (CourseEnrollment, error) {
	row := q.db.QueryRow(ctx, insertEnrollment,
		arg.CourseID,
		arg.StudentID,
		arg.Source,
		arg.AmountPaidMinor,
		arg.Currency,
	)
	var i CourseEnrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.Source,
		&i.AmountPaidMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseItems = `-- name: ListCourseItems :many
SELECT id, section_id, kind, title, video_asset_id, resource_id, position, created_at, is_preview, duration_seconds
FROM course_items
WHERE section_id = $1
ORDER BY position, id
`

func (q *Queries) ListCourseItems(ctx context.Context, sectionID uuid.UUID) ([]CourseItem, error) {
	rows, err := q.db.Query(ctx, listCourseItems, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseItem{}
	for rows.Next() {
		var i CourseItem
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Kind,
			&i.Title,
			&i.VideoAssetID,
			&i.ResourceID,
			&i.Position,
			&i.CreatedAt,
			&i.IsPreview,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseItemsByCourse = `-- name: ListCourseItemsByCourse :many
SELECT ci.id, ci.section_id, ci.kind, ci.title, ci.video_asset_id, ci.resource_id, ci.position, ci.created_at, ci.is_preview, ci.duration_seconds
FROM course_items ci
JOIN course_sections cs ON cs.id = ci.section_id
WHERE cs.course_id = $1
ORDER BY cs.position, cs.id, ci.position, ci.id
`

// Every item across a course's sections, in curriculum order (section
// position, then item position) — one query for the whole tree instead of
// N+1 per-section queries; the service groups rows by section_id in Go.
func (q *Queries) ListCourseItemsByCourse(ctx context.Context, courseID uuid.UUID) ([]CourseItem, error) {
	rows, err := q.db.Query(ctx, listCourseItemsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseItem{}
	for rows.Next() {
		var i CourseItem
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Kind,
			&i.Title,
			&i.VideoAssetID,
			&i.ResourceID,
			&i.Position,
			&i.CreatedAt,
			&i.IsPreview,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseSections = `-- name: ListCourseSections :many
SELECT id, course_id, title, position, created_at, updated_at
FROM course_sections
WHERE course_id = $1
ORDER BY position, id
`

func (q *Queries) ListCourseSections(ctx context.Context, courseID uuid.UUID) ([]CourseSection, error) {
	rows, err := q.db.Query(ctx, listCourseSections, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseSection{}
	for rows.Next() {
		var i CourseSection
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsForStudent = `-- name: ListEnrollmentsForStudent :many
SELECT
    e.id, e.course_id, e.student_id, e.source, e.amount_paid_minor, e.currency, e.created_at,
    c.teacher_id AS course_teacher_id, c.title AS course_title, c.subtitle AS course_subtitle,
    c.description AS course_description, c.cover_asset_id AS course_cover_asset_id,
    c.price_amount_minor AS course_price_amount_minor, c.price_currency AS course_price_currency,
    c.status AS course_status, c.ever_published AS course_ever_published, c.archived_at AS course_archived_at,
    c.created_at AS course_created_at, c.updated_at AS course_updated_at,
    (SELECT count(*) FROM course_items ci JOIN course_sections cs ON cs.id = ci.section_id WHERE cs.course_id = c.id) AS total_items,
    (SELECT count(*) FROM course_item_progress cip WHERE cip.enrollment_id = e.id AND cip.status = 'completed') AS completed_items
FROM course_enrollments e
JOIN courses c ON c.id = e.course_id
WHERE e.student_id = $1
ORDER BY e.created_at DESC, e.id
`

type ListEnrollmentsForStudentRow struct {
	ID                     uuid.UUID
	CourseID               uuid.UUID
	StudentID              uuid.UUID
	Source                 string
	AmountPaidMinor        int64
	Currency               CurrencyCode
	CreatedAt              pgtype.Timestamptz
	CourseTeacherID        uuid.UUID
	CourseTitle            string
	CourseSubtitle         string
	CourseDescription      string
	CourseCoverAssetID     uuid.NullUUID
	CoursePriceAmountMinor int64
	CoursePriceCurrency    CurrencyCode
	CourseStatus           string
	CourseEverPublished    bool
	CourseArchivedAt       pgtype.Timestamptz
	CourseCreatedAt        pgtype.Timestamptz
	CourseUpdatedAt        pgtype.Timestamptz
	TotalItems             int64
	CompletedItems         int64
}

// "My learning": the student's enrollments, newest first, each with its
// course summary and a progress percent computed from two correlated
// subqueries (total curriculum items for the course; completed rows for this
// specific enrollment) — cheap since a course has at most a few dozen items.
func (q *Queries) ListEnrollmentsForStudent(ctx context.Context, studentID uuid.UUID) ([]ListEnrollmentsForStudentRow, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrollmentsForStudentRow{}
	for rows.Next() {
		var i ListEnrollmentsForStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.StudentID,
			&i.Source,
			&i.AmountPaidMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.CourseTeacherID,
			&i.CourseTitle,
			&i.CourseSubtitle,
			&i.CourseDescription,
			&i.CourseCoverAssetID,
			&i.CoursePriceAmountMinor,
			&i.CoursePriceCurrency,
			&i.CourseStatus,
			&i.CourseEverPublished,
			&i.CourseArchivedAt,
			&i.CourseCreatedAt,
			&i.CourseUpdatedAt,
			&i.TotalItems,
			&i.CompletedItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemProgressForEnrollment = `-- name: ListItemProgressForEnrollment :many
SELECT id, enrollment_id, item_id, status, video_position_seconds, completed_at, updated_at
FROM course_item_progress
WHERE enrollment_id = $1
`

func (q *Queries) ListItemProgressForEnrollment(ctx context.Context, enrollmentID uuid.UUID) ([]CourseItemProgress, error) {
	rows, err := q.db.Query(ctx, listItemProgressForEnrollment, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseItemProgress{}
	for rows.Next() {
		var i CourseItemProgress
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.ItemID,
			&i.Status,
			&i.VideoPositionSeconds,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherCourses = `-- name: ListTeacherCourses :many
SELECT id, teacher_id, title, subtitle, description, cover_asset_id,
       price_amount_minor, price_currency, status, ever_published, archived_at,
       created_at, updated_at, suspended_at
FROM courses
WHERE teacher_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::bool OR archived_at IS NULL)
ORDER BY created_at DESC, id
LIMIT $5::int OFFSET $4::int
`

type ListTeacherCoursesParams struct {
	TeacherID       uuid.UUID
	Status          pgtype.Text
	IncludeArchived bool
	PageOffset      int32
	PageLimit       int32
}

// The authoring library list. Filters are optional: status ('draft'|'published')
// and whether to include archived rows.
func (q *Queries) ListTeacherCourses(ctx context.Context, arg ListTeacherCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listTeacherCourses,
		arg.TeacherID,
		arg.Status,
		arg.IncludeArchived,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.CoverAssetID,
			&i.PriceAmountMinor,
			&i.PriceCurrency,
			&i.Status,
			&i.EverPublished,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCourseSection = `-- name: RenameCourseSection :one
UPDATE course_sections
SET title = $2, updated_at = now()
WHERE id = $1
RETURNING id, course_id, title, position, created_at, updated_at
`

type RenameCourseSectionParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) RenameCourseSection(ctx context.Context, arg RenameCourseSectionParams) (CourseSection, error) {
	row := q.db.QueryRow(ctx, renameCourseSection, arg.ID, arg.Title)
	var i CourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reorderCourseItems = `-- name: ReorderCourseItems :execrows
WITH ordered AS (
    SELECT id, row_number() OVER () - 1 AS position
    FROM unnest($2::uuid[]) AS id
)
UPDATE course_items ci
SET position = ordered.position
FROM ordered
WHERE ci.id = ordered.id AND ci.section_id = $1
`

type ReorderCourseItemsParams struct {
	SectionID uuid.UUID
	ItemIds   []uuid.UUID
}

func (q *Queries) ReorderCourseItems(ctx context.Context, arg ReorderCourseItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderCourseItems, arg.SectionID, arg.ItemIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderCourseSections = `-- name: ReorderCourseSections :execrows
WITH ordered AS (
    SELECT id, row_number() OVER () - 1 AS position
    FROM unnest($2::uuid[]) AS id
)
UPDATE course_sections cs
SET position = ordered.position, updated_at = now()
FROM ordered
WHERE cs.id = ordered.id AND cs.course_id = $1
`

type ReorderCourseSectionsParams struct {
	CourseID   uuid.UUID
	SectionIds []uuid.UUID
}

// Rewrites positions 0..n-1 from the given ordered id array in one statement.
// The service has already validated the array is exactly this course's
// current section ids; the course_id filter is a defense-in-depth guard
// against a section that raced its way into another course between the
// service's check and this write (affected rows short of len(ids) surfaces
// to the caller as a write failure, never a silent partial reorder).
func (q *Queries) ReorderCourseSections(ctx context.Context, arg ReorderCourseSectionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderCourseSections, arg.CourseID, arg.SectionIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCourseArchived = `-- name: SetCourseArchived :one
UPDATE courses
SET archived_at = CASE WHEN $1::bool THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at, suspended_at
`

type SetCourseArchivedParams struct {
	Archived bool
	ID       uuid.UUID
}

func (q *Queries) SetCourseArchived(ctx context.Context, arg SetCourseArchivedParams) (Course, error) {
	row := q.db.QueryRow(ctx, setCourseArchived, arg.Archived, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const setCourseStatus = `-- name: SetCourseStatus :one
UPDATE courses
SET status = $1,
    ever_published = ever_published OR ($1::text = 'published'),
    updated_at = now()
WHERE id = $2
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at, suspended_at
`

type SetCourseStatusParams struct {
	Status string
	ID     uuid.UUID
}

// ever_published is a one-way latch: OR'd with "is this setting `published`",
// so unpublishing (status back to draft) never clears it — Delete stays
// blocked forever once a course has gone live at least once.
func (q *Queries) SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (Course, error) {
	row := q.db.QueryRow(ctx, setCourseStatus, arg.Status, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const setCourseSuspended = `-- name: SetCourseSuspended :one
UPDATE courses
SET suspended_at = CASE WHEN $1::bool THEN COALESCE(suspended_at, now()) ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at, suspended_at
`

type SetCourseSuspendedParams struct {
	Suspended bool
	CourseID  uuid.UUID
}

// Idempotent: suspending an already-suspended course (or unsuspending an
// already-active one) is a no-op that still returns the current row — COALESCE
// keeps the original suspended_at instead of sliding it forward on a repeat
// call, same "don't move a timestamp that's already set" idiom as
// UpsertItemProgress's completed_at. Returns the course row only; the
// repository loads the teacher summary separately with GetTeacherSummary
// (same two-query shape avoids a CTE-scoped ambiguous-column parse sqlc
// rejects when the same query both updates and re-joins the touched row).
func (q *Queries) SetCourseSuspended(ctx context.Context, arg SetCourseSuspendedParams) (Course, error) {
	row := q.db.QueryRow(ctx, setCourseSuspended, arg.Suspended, arg.CourseID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const studentHasResourceAccess = `-- name: StudentHasResourceAccess :one
SELECT EXISTS(
    SELECT 1
    FROM course_enrollments e
    JOIN course_sections cs ON cs.course_id = e.course_id
    JOIN course_items ci ON ci.section_id = cs.id
    WHERE e.student_id = $1 AND ci.resource_id = $2
) AS accessible
`

type StudentHasResourceAccessParams struct {
	StudentID  uuid.UUID
	ResourceID uuid.NullUUID
}

// Does studentID have SOME active enrollment granting access to resourceID,
// independent of which specific enrollment? Backs the course-based widening
// of a course-embedded resource's material/audio file.
func (q *Queries) StudentHasResourceAccess(ctx context.Context, arg StudentHasResourceAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, studentHasResourceAccess, arg.StudentID, arg.ResourceID)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}

const studentHasVideoAccess = `-- name: StudentHasVideoAccess :one
SELECT EXISTS(
    SELECT 1
    FROM course_enrollments e
    JOIN course_sections cs ON cs.course_id = e.course_id
    JOIN course_items ci ON ci.section_id = cs.id
    WHERE e.student_id = $1 AND ci.video_asset_id = $2
) AS accessible
`

type StudentHasVideoAccessParams struct {
	StudentID   uuid.UUID
	FileAssetID uuid.NullUUID
}

// Backs files.AssigneeChecker's course-based widening: is fileAssetID a video
// item's asset in some course the student is actively enrolled in?
func (q *Queries) StudentHasVideoAccess(ctx context.Context, arg StudentHasVideoAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, studentHasVideoAccess, arg.StudentID, arg.FileAssetID)
	var accessible bool
	err := row.Scan(&accessible)
	return accessible, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = $2, subtitle = $3, description = $4, cover_asset_id = $5,
    price_amount_minor = $6, price_currency = $7, updated_at = now()
WHERE id = $1
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at, suspended_at
`

type UpdateCourseParams struct {
	ID               uuid.UUID
	Title            string
	Subtitle         string
	Description      string
	CoverAssetID     uuid.NullUUID
	PriceAmountMinor int64
	PriceCurrency    CurrencyCode
}

// Full replace of the editable fields: title / subtitle / description / cover
// / price. The service passes the current value for anything it isn't
// changing, same convention as UpdateResource.
func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.CoverAssetID,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const updateCourseItem = `-- name: UpdateCourseItem :one
UPDATE course_items
SET title            = $1,
    is_preview       = COALESCE($2, is_preview),
    duration_seconds = COALESCE($3, duration_seconds)
WHERE id = $4
RETURNING id, section_id, kind, title, video_asset_id, resource_id, position, created_at, is_preview, duration_seconds
`

type UpdateCourseItemParams struct {
	Title           string
	IsPreview       pgtype.Bool
	DurationSeconds pgtype.Int4
	ID              uuid.UUID
}

// Phase D1: the item edit now carries the preview flag and the video duration
// alongside the title. Both are COALESCEd so a caller that omits them (the
// plain rename path) leaves the stored values alone.
func (q *Queries) UpdateCourseItem(ctx context.Context, arg UpdateCourseItemParams) (CourseItem, error) {
	row := q.db.QueryRow(ctx, updateCourseItem,
		arg.Title,
		arg.IsPreview,
		arg.DurationSeconds,
		arg.ID,
	)
	var i CourseItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Kind,
		&i.Title,
		&i.VideoAssetID,
		&i.ResourceID,
		&i.Position,
		&i.CreatedAt,
		&i.IsPreview,
		&i.DurationSeconds,
	)
	return i, err
}

const upsertItemProgress = `-- name: UpsertItemProgress :one

INSERT INTO course_item_progress (enrollment_id, item_id, video_position_seconds, status, completed_at)
VALUES (
    $1, $2,
    COALESCE($3::int, 0),
    CASE WHEN $4::bool IS TRUE THEN 'completed' ELSE 'in_progress' END,
    CASE WHEN $4::bool IS TRUE THEN now() ELSE NULL END
)
ON CONFLICT (enrollment_id, item_id) DO UPDATE SET
    video_position_seconds = COALESCE($3::int, course_item_progress.video_position_seconds),
    status = CASE
        WHEN $4::bool IS TRUE  THEN 'completed'
        WHEN $4::bool IS FALSE THEN 'in_progress'
        ELSE course_item_progress.status
    END,
    completed_at = CASE
        WHEN $4::bool IS TRUE  THEN COALESCE(course_item_progress.completed_at, now())
        WHEN $4::bool IS FALSE THEN NULL
        ELSE course_item_progress.completed_at
    END,
    updated_at = now()
RETURNING id, enrollment_id, item_id, status, video_position_seconds, completed_at, updated_at
`

type UpsertItemProgressParams struct {
	EnrollmentID         uuid.UUID
	ItemID               uuid.UUID
	VideoPositionSeconds pgtype.Int4
	Completed            pgtype.Bool
}

// Progress.
// Merges the given fields into a video item's progress row for a student
// driving the player (position updates as they watch; explicit
// complete/uncomplete). NULL args (a field the client didn't send) leave the
// stored value unchanged. completed=true stamps completed_at once (COALESCE
// keeps the first time it was ever set); completed=false clears it.
func (q *Queries) UpsertItemProgress(ctx context.Context, arg UpsertItemProgressParams) (CourseItemProgress, error) {
	row := q.db.QueryRow(ctx, upsertItemProgress,
		arg.EnrollmentID,
		arg.ItemID,
		arg.VideoPositionSeconds,
		arg.Completed,
	)
	var i CourseItemProgress
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.ItemID,
		&i.Status,
		&i.VideoPositionSeconds,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
