// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoursePayment = `-- name: CreateCoursePayment :one

INSERT INTO course_payments (course_id, student_id, provider, amount_minor, currency, status)
VALUES ($1, $2, $3, $4, $5, 'requires_payment')
ON CONFLICT (course_id, student_id) DO UPDATE SET course_id = course_payments.course_id
RETURNING id, course_id, student_id, provider, provider_ref, status, amount_minor, currency,
          last_error, authorized_at, captured_at, refunded_at, created_at, updated_at
`

type CreateCoursePaymentParams struct {
	CourseID    uuid.UUID
	StudentID   uuid.UUID
	Provider    string
	AmountMinor int64
	Currency    CurrencyCode
}

// Phase C2: course-purchase payments. A sibling of payments.sql's booking
// flow — same status lifecycle and webhook-idempotency shape, keyed to
// (course_id, student_id) instead of booking_id. No payout-ledger write here;
// revenue-share for course sales is a future phase.
// Idempotent: a second call for the same (course_id, student_id) is a no-op
// and still returns the existing row (mirrors CreatePayment's ON CONFLICT
// DO UPDATE no-op trick).
func (q *Queries) CreateCoursePayment(ctx context.Context, arg CreateCoursePaymentParams) (CoursePayment, error) {
	row := q.db.QueryRow(ctx, createCoursePayment,
		arg.CourseID,
		arg.StudentID,
		arg.Provider,
		arg.AmountMinor,
		arg.Currency,
	)
	var i CoursePayment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.LastError,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoursePaymentByCourseAndStudent = `-- name: GetCoursePaymentByCourseAndStudent :one
SELECT id, course_id, student_id, provider, provider_ref, status, amount_minor, currency,
       last_error, authorized_at, captured_at, refunded_at, created_at, updated_at
FROM course_payments
WHERE course_id = $1 AND student_id = $2
`

type GetCoursePaymentByCourseAndStudentParams struct {
	CourseID  uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) GetCoursePaymentByCourseAndStudent(ctx context.Context, arg GetCoursePaymentByCourseAndStudentParams) (CoursePayment, error) {
	row := q.db.QueryRow(ctx, getCoursePaymentByCourseAndStudent, arg.CourseID, arg.StudentID)
	var i CoursePayment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.LastError,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoursePaymentByID = `-- name: GetCoursePaymentByID :one
SELECT id, course_id, student_id, provider, provider_ref, status, amount_minor, currency,
       last_error, authorized_at, captured_at, refunded_at, created_at, updated_at
FROM course_payments
WHERE id = $1
`

func (q *Queries) GetCoursePaymentByID(ctx context.Context, id uuid.UUID) (CoursePayment, error) {
	row := q.db.QueryRow(ctx, getCoursePaymentByID, id)
	var i CoursePayment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.StudentID,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.LastError,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCoursePaymentEvent = `-- name: InsertCoursePaymentEvent :exec
INSERT INTO course_payment_events (event_id, payment_id, type)
VALUES ($1, $2, $3)
`

type InsertCoursePaymentEventParams struct {
	EventID   string
	PaymentID uuid.UUID
	Type      string
}

func (q *Queries) InsertCoursePaymentEvent(ctx context.Context, arg InsertCoursePaymentEventParams) error {
	_, err := q.db.Exec(ctx, insertCoursePaymentEvent, arg.EventID, arg.PaymentID, arg.Type)
	return err
}

const markCoursePaymentAuthorized = `-- name: MarkCoursePaymentAuthorized :exec
UPDATE course_payments
SET status = 'authorized', provider_ref = $1, authorized_at = now(), updated_at = now()
WHERE id = $2
`

type MarkCoursePaymentAuthorizedParams struct {
	ProviderRef pgtype.Text
	ID          uuid.UUID
}

func (q *Queries) MarkCoursePaymentAuthorized(ctx context.Context, arg MarkCoursePaymentAuthorizedParams) error {
	_, err := q.db.Exec(ctx, markCoursePaymentAuthorized, arg.ProviderRef, arg.ID)
	return err
}

const markCoursePaymentCaptured = `-- name: MarkCoursePaymentCaptured :exec
UPDATE course_payments SET status = 'captured', captured_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkCoursePaymentCaptured(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCoursePaymentCaptured, id)
	return err
}

const markCoursePaymentFailed = `-- name: MarkCoursePaymentFailed :exec
UPDATE course_payments
SET status = 'failed', last_error = $1, updated_at = now()
WHERE id = $2
`

type MarkCoursePaymentFailedParams struct {
	LastError string
	ID        uuid.UUID
}

func (q *Queries) MarkCoursePaymentFailed(ctx context.Context, arg MarkCoursePaymentFailedParams) error {
	_, err := q.db.Exec(ctx, markCoursePaymentFailed, arg.LastError, arg.ID)
	return err
}

const markCoursePaymentRefunded = `-- name: MarkCoursePaymentRefunded :exec
UPDATE course_payments SET status = 'refunded', refunded_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkCoursePaymentRefunded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCoursePaymentRefunded, id)
	return err
}
