// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountCourseReviews = `-- name: AdminCountCourseReviews :one
SELECT count(*)
FROM course_reviews cr
WHERE ($1::boolean IS NULL OR cr.hidden = $1::boolean)
  AND ($2::uuid IS NULL OR cr.course_id = $2::uuid)
  AND ($3::int IS NULL OR cr.rating <= $3::int)
`

type AdminCountCourseReviewsParams struct {
	Hidden    pgtype.Bool
	CourseID  uuid.NullUUID
	MaxRating pgtype.Int4
}

func (q *Queries) AdminCountCourseReviews(ctx context.Context, arg AdminCountCourseReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountCourseReviews, arg.Hidden, arg.CourseID, arg.MaxRating)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetCourseReview = `-- name: AdminGetCourseReview :one
SELECT cr.id, cr.course_id, cr.rating, cr.comment, cr.hidden, cr.created_at,
       c.title AS course_title,
       u.display_name AS student_display_name
FROM course_reviews cr
JOIN courses c ON c.id = cr.course_id
JOIN users u ON u.id = cr.student_id
WHERE cr.id = $1
`

type AdminGetCourseReviewRow struct {
	ID                 uuid.UUID
	CourseID           uuid.UUID
	Rating             int16
	Comment            string
	Hidden             bool
	CreatedAt          pgtype.Timestamptz
	CourseTitle        string
	StudentDisplayName string
}

// One moderation-queue row by id, with the course title and student name the
// bare course_reviews row can't carry. Used to build the response after a
// hide/unhide, whose RETURNING clause only sees the one table.
func (q *Queries) AdminGetCourseReview(ctx context.Context, id uuid.UUID) (AdminGetCourseReviewRow, error) {
	row := q.db.QueryRow(ctx, adminGetCourseReview, id)
	var i AdminGetCourseReviewRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
		&i.CourseTitle,
		&i.StudentDisplayName,
	)
	return i, err
}

const adminListCourseReviews = `-- name: AdminListCourseReviews :many
SELECT cr.id, cr.course_id, cr.rating, cr.comment, cr.hidden, cr.created_at,
       c.title AS course_title,
       u.display_name AS student_display_name
FROM course_reviews cr
JOIN courses c ON c.id = cr.course_id
JOIN users u ON u.id = cr.student_id
WHERE ($1::boolean IS NULL OR cr.hidden = $1::boolean)
  AND ($2::uuid IS NULL OR cr.course_id = $2::uuid)
  AND ($3::int IS NULL OR cr.rating <= $3::int)
ORDER BY cr.created_at DESC, cr.id
LIMIT $5::int OFFSET $4::int
`

type AdminListCourseReviewsParams struct {
	Hidden     pgtype.Bool
	CourseID   uuid.NullUUID
	MaxRating  pgtype.Int4
	PageOffset int32
	PageLimit  int32
}

type AdminListCourseReviewsRow struct {
	ID                 uuid.UUID
	CourseID           uuid.UUID
	Rating             int16
	Comment            string
	Hidden             bool
	CreatedAt          pgtype.Timestamptz
	CourseTitle        string
	StudentDisplayName string
}

// The moderation queue: every course review regardless of visibility, newest
// first, optionally narrowed to one visibility, one course, or a rating
// ceiling (to surface the low-star reviews an operator is looking for).
func (q *Queries) AdminListCourseReviews(ctx context.Context, arg AdminListCourseReviewsParams) ([]AdminListCourseReviewsRow, error) {
	rows, err := q.db.Query(ctx, adminListCourseReviews,
		arg.Hidden,
		arg.CourseID,
		arg.MaxRating,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListCourseReviewsRow{}
	for rows.Next() {
		var i AdminListCourseReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Rating,
			&i.Comment,
			&i.Hidden,
			&i.CreatedAt,
			&i.CourseTitle,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCourseReviews = `-- name: CountCourseReviews :one
SELECT count(*) FROM course_reviews
WHERE course_id = $1 AND NOT hidden
`

func (q *Queries) CountCourseReviews(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCourseReviews, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const courseRatingBreakdown = `-- name: CourseRatingBreakdown :many
SELECT rating, count(*)::bigint AS n
FROM course_reviews
WHERE course_id = $1 AND NOT hidden
GROUP BY rating
`

type CourseRatingBreakdownRow struct {
	Rating int16
	N      int64
}

// The "5★ ▓▓▓ 12" histogram under a course's rating. Visible rows only, and
// only the star values that actually occur — the caller fills 1..5 with zeros.
func (q *Queries) CourseRatingBreakdown(ctx context.Context, courseID uuid.UUID) ([]CourseRatingBreakdownRow, error) {
	rows, err := q.db.Query(ctx, courseRatingBreakdown, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseRatingBreakdownRow{}
	for rows.Next() {
		var i CourseRatingBreakdownRow
		if err := rows.Scan(&i.Rating, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllCourseReviews = `-- name: DeleteAllCourseReviews :exec
DELETE FROM course_reviews
`

func (q *Queries) DeleteAllCourseReviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCourseReviews)
	return err
}

const getCourseReviewByEnrollment = `-- name: GetCourseReviewByEnrollment :one
SELECT id, course_id, enrollment_id, student_id, rating, comment, hidden, created_at, updated_at
FROM course_reviews
WHERE enrollment_id = $1
`

func (q *Queries) GetCourseReviewByEnrollment(ctx context.Context, enrollmentID uuid.UUID) (CourseReview, error) {
	row := q.db.QueryRow(ctx, getCourseReviewByEnrollment, enrollmentID)
	var i CourseReview
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseReviewByID = `-- name: GetCourseReviewByID :one
SELECT id, course_id, enrollment_id, student_id, rating, comment, hidden, created_at, updated_at
FROM course_reviews
WHERE id = $1
`

func (q *Queries) GetCourseReviewByID(ctx context.Context, id uuid.UUID) (CourseReview, error) {
	row := q.db.QueryRow(ctx, getCourseReviewByID, id)
	var i CourseReview
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCourseReview = `-- name: InsertCourseReview :one

INSERT INTO course_reviews (course_id, enrollment_id, student_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, enrollment_id, student_id, rating, comment, hidden, created_at, updated_at
`

type InsertCourseReviewParams struct {
	CourseID     uuid.UUID
	EnrollmentID uuid.UUID
	StudentID    uuid.UUID
	Rating       int16
	Comment      string
}

// Course reviews (phase D2): a buyer's rating + comment for a course they are
// enrolled in, plus the derived display aggregate on courses.rating /
// review_count. See migration 000024 for the design notes.
// A duplicate (enrollment_id) raises SQLSTATE 23505 on the table's UNIQUE
// constraint, which the repository maps to ErrAlreadyReviewed — race-safe,
// never a check-then-insert.
func (q *Queries) InsertCourseReview(ctx context.Context, arg InsertCourseReviewParams) (CourseReview, error) {
	row := q.db.QueryRow(ctx, insertCourseReview,
		arg.CourseID,
		arg.EnrollmentID,
		arg.StudentID,
		arg.Rating,
		arg.Comment,
	)
	var i CourseReview
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseReviews = `-- name: ListCourseReviews :many
SELECT cr.id, cr.rating, cr.comment, cr.created_at, cr.updated_at,
       u.display_name AS student_display_name
FROM course_reviews cr
JOIN users u ON u.id = cr.student_id
WHERE cr.course_id = $1 AND NOT cr.hidden
ORDER BY cr.created_at DESC, cr.id
LIMIT $3::int OFFSET $2::int
`

type ListCourseReviewsParams struct {
	CourseID   uuid.UUID
	PageOffset int32
	PageLimit  int32
}

type ListCourseReviewsRow struct {
	ID                 uuid.UUID
	Rating             int16
	Comment            string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	StudentDisplayName string
}

// One course's public review list: visible rows only, newest first.
func (q *Queries) ListCourseReviews(ctx context.Context, arg ListCourseReviewsParams) ([]ListCourseReviewsRow, error) {
	rows, err := q.db.Query(ctx, listCourseReviews, arg.CourseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseReviewsRow{}
	for rows.Next() {
		var i ListCourseReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeCourseRating = `-- name: RecomputeCourseRating :exec
WITH v AS (
    SELECT COALESCE(sum(rating), 0)::numeric AS sum_r,
           count(*)                          AS n
    FROM course_reviews
    WHERE course_id = $1 AND NOT hidden
)
UPDATE courses c
SET review_count = v.n,
    rating = CASE
        WHEN v.n = 0 THEN 0
        ELSE LEAST(5, GREATEST(0, round(v.sum_r / v.n, 1)))::real
    END,
    updated_at = now()
FROM v
WHERE c.id = $1
`

// Rebuild courses.rating / review_count from the course's currently VISIBLE
// reviews. Idempotent and order-independent — run it inside the same
// transaction as any create / edit / hide / unhide / delete. A course with no
// visible reviews reads as 0/0, which every surface renders as "no ratings
// yet" rather than as a zero-star course.
func (q *Queries) RecomputeCourseRating(ctx context.Context, courseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, recomputeCourseRating, courseID)
	return err
}

const setCourseReviewHidden = `-- name: SetCourseReviewHidden :one
UPDATE course_reviews
SET hidden = $1, updated_at = now()
WHERE id = $2
RETURNING id, course_id, enrollment_id, student_id, rating, comment, hidden, created_at, updated_at
`

type SetCourseReviewHiddenParams struct {
	Hidden bool
	ID     uuid.UUID
}

func (q *Queries) SetCourseReviewHidden(ctx context.Context, arg SetCourseReviewHiddenParams) (CourseReview, error) {
	row := q.db.QueryRow(ctx, setCourseReviewHidden, arg.Hidden, arg.ID)
	var i CourseReview
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourseReview = `-- name: UpdateCourseReview :one
UPDATE course_reviews
SET rating = $1,
    comment = $2,
    updated_at = now()
WHERE id = $3 AND student_id = $4
RETURNING id, course_id, enrollment_id, student_id, rating, comment, hidden, created_at, updated_at
`

type UpdateCourseReviewParams struct {
	Rating    int16
	Comment   string
	ID        uuid.UUID
	StudentID uuid.UUID
}

// The author edits their own standing opinion. Scoped by student_id so an
// edit can never touch someone else's row even if the id leaked.
func (q *Queries) UpdateCourseReview(ctx context.Context, arg UpdateCourseReviewParams) (CourseReview, error) {
	row := q.db.QueryRow(ctx, updateCourseReview,
		arg.Rating,
		arg.Comment,
		arg.ID,
		arg.StudentID,
	)
	var i CourseReview
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.Rating,
		&i.Comment,
		&i.Hidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
