// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCourseItem = `-- name: AddCourseItem :one

INSERT INTO course_items (section_id, kind, title, video_asset_id, resource_id, position)
VALUES (
    $1, $2, $3,
    $4, $5,
    COALESCE((SELECT max(position) + 1 FROM course_items WHERE section_id = $1), 0)
)
RETURNING id, section_id, kind, title, video_asset_id, resource_id, position, created_at
`

type AddCourseItemParams struct {
	SectionID    uuid.UUID
	Kind         string
	Title        string
	VideoAssetID uuid.NullUUID
	ResourceID   uuid.NullUUID
}

// Items.
// position is the current item count for the section, same idiom as sections.
func (q *Queries) AddCourseItem(ctx context.Context, arg AddCourseItemParams) (CourseItem, error) {
	row := q.db.QueryRow(ctx, addCourseItem,
		arg.SectionID,
		arg.Kind,
		arg.Title,
		arg.VideoAssetID,
		arg.ResourceID,
	)
	var i CourseItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Kind,
		&i.Title,
		&i.VideoAssetID,
		&i.ResourceID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const addCourseSection = `-- name: AddCourseSection :one

INSERT INTO course_sections (course_id, title, position)
VALUES (
    $1, $2,
    COALESCE((SELECT max(position) + 1 FROM course_sections WHERE course_id = $1), 0)
)
RETURNING id, course_id, title, position, created_at, updated_at
`

type AddCourseSectionParams struct {
	CourseID uuid.UUID
	Title    string
}

// Sections.
// position is the current section count for the course, computed here so the
// insert stays a single statement (same idiom as AttachBookingResource).
func (q *Queries) AddCourseSection(ctx context.Context, arg AddCourseSectionParams) (CourseSection, error) {
	row := q.db.QueryRow(ctx, addCourseSection, arg.CourseID, arg.Title)
	var i CourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countTeacherCourses = `-- name: CountTeacherCourses :one
SELECT count(*)
FROM courses
WHERE teacher_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::bool OR archived_at IS NULL)
`

type CountTeacherCoursesParams struct {
	TeacherID       uuid.UUID
	Status          pgtype.Text
	IncludeArchived bool
}

func (q *Queries) CountTeacherCourses(ctx context.Context, arg CountTeacherCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeacherCourses, arg.TeacherID, arg.Status, arg.IncludeArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one

INSERT INTO courses (teacher_id, title, subtitle, description, price_amount_minor, price_currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at
`

type CreateCourseParams struct {
	TeacherID        uuid.UUID
	Title            string
	Subtitle         string
	Description      string
	PriceAmountMinor int64
	PriceCurrency    CurrencyCode
}

// Course authoring (phase C1): a teacher's courses, and the curriculum tree
// (sections -> items) each one owns.
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.TeacherID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteCourseItem = `-- name: DeleteCourseItem :exec
DELETE FROM course_items WHERE id = $1
`

func (q *Queries) DeleteCourseItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseItem, id)
	return err
}

const deleteCourseSection = `-- name: DeleteCourseSection :exec
DELETE FROM course_sections WHERE id = $1
`

func (q *Queries) DeleteCourseSection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseSection, id)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, teacher_id, title, subtitle, description, cover_asset_id,
       price_amount_minor, price_currency, status, ever_published, archived_at,
       created_at, updated_at
FROM courses
WHERE id = $1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseItem = `-- name: GetCourseItem :one
SELECT id, section_id, kind, title, video_asset_id, resource_id, position, created_at
FROM course_items
WHERE id = $1
`

func (q *Queries) GetCourseItem(ctx context.Context, id uuid.UUID) (CourseItem, error) {
	row := q.db.QueryRow(ctx, getCourseItem, id)
	var i CourseItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Kind,
		&i.Title,
		&i.VideoAssetID,
		&i.ResourceID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseSection = `-- name: GetCourseSection :one
SELECT id, course_id, title, position, created_at, updated_at
FROM course_sections
WHERE id = $1
`

func (q *Queries) GetCourseSection(ctx context.Context, id uuid.UUID) (CourseSection, error) {
	row := q.db.QueryRow(ctx, getCourseSection, id)
	var i CourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseItems = `-- name: ListCourseItems :many
SELECT id, section_id, kind, title, video_asset_id, resource_id, position, created_at
FROM course_items
WHERE section_id = $1
ORDER BY position, id
`

func (q *Queries) ListCourseItems(ctx context.Context, sectionID uuid.UUID) ([]CourseItem, error) {
	rows, err := q.db.Query(ctx, listCourseItems, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseItem{}
	for rows.Next() {
		var i CourseItem
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Kind,
			&i.Title,
			&i.VideoAssetID,
			&i.ResourceID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseItemsByCourse = `-- name: ListCourseItemsByCourse :many
SELECT ci.id, ci.section_id, ci.kind, ci.title, ci.video_asset_id, ci.resource_id, ci.position, ci.created_at
FROM course_items ci
JOIN course_sections cs ON cs.id = ci.section_id
WHERE cs.course_id = $1
ORDER BY cs.position, cs.id, ci.position, ci.id
`

// Every item across a course's sections, in curriculum order (section
// position, then item position) — one query for the whole tree instead of
// N+1 per-section queries; the service groups rows by section_id in Go.
func (q *Queries) ListCourseItemsByCourse(ctx context.Context, courseID uuid.UUID) ([]CourseItem, error) {
	rows, err := q.db.Query(ctx, listCourseItemsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseItem{}
	for rows.Next() {
		var i CourseItem
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Kind,
			&i.Title,
			&i.VideoAssetID,
			&i.ResourceID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseSections = `-- name: ListCourseSections :many
SELECT id, course_id, title, position, created_at, updated_at
FROM course_sections
WHERE course_id = $1
ORDER BY position, id
`

func (q *Queries) ListCourseSections(ctx context.Context, courseID uuid.UUID) ([]CourseSection, error) {
	rows, err := q.db.Query(ctx, listCourseSections, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseSection{}
	for rows.Next() {
		var i CourseSection
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherCourses = `-- name: ListTeacherCourses :many
SELECT id, teacher_id, title, subtitle, description, cover_asset_id,
       price_amount_minor, price_currency, status, ever_published, archived_at,
       created_at, updated_at
FROM courses
WHERE teacher_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::bool OR archived_at IS NULL)
ORDER BY created_at DESC, id
LIMIT $5::int OFFSET $4::int
`

type ListTeacherCoursesParams struct {
	TeacherID       uuid.UUID
	Status          pgtype.Text
	IncludeArchived bool
	PageOffset      int32
	PageLimit       int32
}

// The authoring library list. Filters are optional: status ('draft'|'published')
// and whether to include archived rows.
func (q *Queries) ListTeacherCourses(ctx context.Context, arg ListTeacherCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listTeacherCourses,
		arg.TeacherID,
		arg.Status,
		arg.IncludeArchived,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.CoverAssetID,
			&i.PriceAmountMinor,
			&i.PriceCurrency,
			&i.Status,
			&i.EverPublished,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCourseItem = `-- name: RenameCourseItem :one
UPDATE course_items
SET title = $2
WHERE id = $1
RETURNING id, section_id, kind, title, video_asset_id, resource_id, position, created_at
`

type RenameCourseItemParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) RenameCourseItem(ctx context.Context, arg RenameCourseItemParams) (CourseItem, error) {
	row := q.db.QueryRow(ctx, renameCourseItem, arg.ID, arg.Title)
	var i CourseItem
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Kind,
		&i.Title,
		&i.VideoAssetID,
		&i.ResourceID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const renameCourseSection = `-- name: RenameCourseSection :one
UPDATE course_sections
SET title = $2, updated_at = now()
WHERE id = $1
RETURNING id, course_id, title, position, created_at, updated_at
`

type RenameCourseSectionParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) RenameCourseSection(ctx context.Context, arg RenameCourseSectionParams) (CourseSection, error) {
	row := q.db.QueryRow(ctx, renameCourseSection, arg.ID, arg.Title)
	var i CourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reorderCourseItems = `-- name: ReorderCourseItems :execrows
WITH ordered AS (
    SELECT id, row_number() OVER () - 1 AS position
    FROM unnest($2::uuid[]) AS id
)
UPDATE course_items ci
SET position = ordered.position
FROM ordered
WHERE ci.id = ordered.id AND ci.section_id = $1
`

type ReorderCourseItemsParams struct {
	SectionID uuid.UUID
	ItemIds   []uuid.UUID
}

func (q *Queries) ReorderCourseItems(ctx context.Context, arg ReorderCourseItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderCourseItems, arg.SectionID, arg.ItemIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderCourseSections = `-- name: ReorderCourseSections :execrows
WITH ordered AS (
    SELECT id, row_number() OVER () - 1 AS position
    FROM unnest($2::uuid[]) AS id
)
UPDATE course_sections cs
SET position = ordered.position, updated_at = now()
FROM ordered
WHERE cs.id = ordered.id AND cs.course_id = $1
`

type ReorderCourseSectionsParams struct {
	CourseID   uuid.UUID
	SectionIds []uuid.UUID
}

// Rewrites positions 0..n-1 from the given ordered id array in one statement.
// The service has already validated the array is exactly this course's
// current section ids; the course_id filter is a defense-in-depth guard
// against a section that raced its way into another course between the
// service's check and this write (affected rows short of len(ids) surfaces
// to the caller as a write failure, never a silent partial reorder).
func (q *Queries) ReorderCourseSections(ctx context.Context, arg ReorderCourseSectionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderCourseSections, arg.CourseID, arg.SectionIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCourseArchived = `-- name: SetCourseArchived :one
UPDATE courses
SET archived_at = CASE WHEN $1::bool THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at
`

type SetCourseArchivedParams struct {
	Archived bool
	ID       uuid.UUID
}

func (q *Queries) SetCourseArchived(ctx context.Context, arg SetCourseArchivedParams) (Course, error) {
	row := q.db.QueryRow(ctx, setCourseArchived, arg.Archived, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCourseStatus = `-- name: SetCourseStatus :one
UPDATE courses
SET status = $1,
    ever_published = ever_published OR ($1::text = 'published'),
    updated_at = now()
WHERE id = $2
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at
`

type SetCourseStatusParams struct {
	Status string
	ID     uuid.UUID
}

// ever_published is a one-way latch: OR'd with "is this setting `published`",
// so unpublishing (status back to draft) never clears it — Delete stays
// blocked forever once a course has gone live at least once.
func (q *Queries) SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (Course, error) {
	row := q.db.QueryRow(ctx, setCourseStatus, arg.Status, arg.ID)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = $2, subtitle = $3, description = $4, cover_asset_id = $5,
    price_amount_minor = $6, price_currency = $7, updated_at = now()
WHERE id = $1
RETURNING id, teacher_id, title, subtitle, description, cover_asset_id,
          price_amount_minor, price_currency, status, ever_published, archived_at,
          created_at, updated_at
`

type UpdateCourseParams struct {
	ID               uuid.UUID
	Title            string
	Subtitle         string
	Description      string
	CoverAssetID     uuid.NullUUID
	PriceAmountMinor int64
	PriceCurrency    CurrencyCode
}

// Full replace of the editable fields: title / subtitle / description / cover
// / price. The service passes the current value for anything it isn't
// changing, same convention as UpdateResource.
func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.CoverAssetID,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.CoverAssetID,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.Status,
		&i.EverPublished,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
