// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountDisputes = `-- name: AdminCountDisputes :one
SELECT count(*)
FROM disputes d
WHERE ($1::text IS NULL OR d.status = $1::text)
`

func (q *Queries) AdminCountDisputes(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountDisputes, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListDisputes = `-- name: AdminListDisputes :many
SELECT d.id, d.booking_id, d.raised_by, d.reason, d.status, d.resolution,
       d.resolved_by, d.created_at, d.resolved_at,
       ru.display_name                     AS raised_by_display_name,
       COALESCE(su.display_name, '')::text AS resolved_by_display_name,
       b.status                            AS booking_status,
       b.start_at                          AS booking_start_at,
       b.price_minor                       AS booking_price_minor,
       b.currency                          AS booking_currency,
       t.slug                              AS teacher_slug,
       t.display_name                      AS teacher_display_name,
       s.id                                AS student_id,
       s.email::text                       AS student_email,
       s.display_name                      AS student_display_name
FROM disputes d
JOIN users    ru ON ru.id = d.raised_by
LEFT JOIN users su ON su.id = d.resolved_by
JOIN bookings b  ON b.id = d.booking_id
JOIN teachers t  ON t.id = b.teacher_id
JOIN users    s  ON s.id = b.student_id
WHERE ($1::text IS NULL OR d.status = $1::text)
ORDER BY d.created_at DESC, d.id
LIMIT $3::int OFFSET $2::int
`

type AdminListDisputesParams struct {
	Status     pgtype.Text
	PageOffset int32
	PageLimit  int32
}

type AdminListDisputesRow struct {
	ID                    uuid.UUID
	BookingID             uuid.UUID
	RaisedBy              uuid.UUID
	Reason                string
	Status                string
	Resolution            string
	ResolvedBy            uuid.NullUUID
	CreatedAt             pgtype.Timestamptz
	ResolvedAt            pgtype.Timestamptz
	RaisedByDisplayName   string
	ResolvedByDisplayName string
	BookingStatus         string
	BookingStartAt        pgtype.Timestamptz
	BookingPriceMinor     int64
	BookingCurrency       string
	TeacherSlug           string
	TeacherDisplayName    string
	StudentID             uuid.UUID
	StudentEmail          string
	StudentDisplayName    string
}

// The operator queue: disputes filtered by status (default 'open' in the
// service), each with the booking + parties context the list view renders.
func (q *Queries) AdminListDisputes(ctx context.Context, arg AdminListDisputesParams) ([]AdminListDisputesRow, error) {
	rows, err := q.db.Query(ctx, adminListDisputes, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListDisputesRow{}
	for rows.Next() {
		var i AdminListDisputesRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.RaisedBy,
			&i.Reason,
			&i.Status,
			&i.Resolution,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.RaisedByDisplayName,
			&i.ResolvedByDisplayName,
			&i.BookingStatus,
			&i.BookingStartAt,
			&i.BookingPriceMinor,
			&i.BookingCurrency,
			&i.TeacherSlug,
			&i.TeacherDisplayName,
			&i.StudentID,
			&i.StudentEmail,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllDisputes = `-- name: DeleteAllDisputes :exec
DELETE FROM disputes
`

// Seed-only. disputes.booking_id cascades, but raised_by / resolved_by
// reference users with no cascade, so the seed clears disputes explicitly
// before bookings and users.
func (q *Queries) DeleteAllDisputes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllDisputes)
	return err
}

const getDisputeBookingContext = `-- name: GetDisputeBookingContext :one

SELECT b.id, b.status, b.student_id,
       t.user_id AS teacher_user_id
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
WHERE b.id = $1
`

type GetDisputeBookingContextRow struct {
	ID            uuid.UUID
	Status        string
	StudentID     uuid.UUID
	TeacherUserID uuid.NullUUID
}

// Disputes module (phase D): a participant contests a confirmed / completed
// lesson, an operator with `disputes.resolve` closes it.
//
// Like the reviews module, this file reads the booking context it needs
// directly (the participant + status check) rather than routing through the
// bookings service — the Go packages stay decoupled, the SQL joins once.
// Everything POST/GET /v1/bookings/{id}/disputes needs to authorize the caller:
// the booking's student, the account owning the teacher profile, and the status
// (only confirmed / completed lessons can be disputed).
func (q *Queries) GetDisputeBookingContext(ctx context.Context, id uuid.UUID) (GetDisputeBookingContextRow, error) {
	row := q.db.QueryRow(ctx, getDisputeBookingContext, id)
	var i GetDisputeBookingContextRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StudentID,
		&i.TeacherUserID,
	)
	return i, err
}

const getDisputeByID = `-- name: GetDisputeByID :one
SELECT d.id, d.booking_id, d.raised_by, d.reason, d.status, d.resolution,
       d.resolved_by, d.created_at, d.resolved_at,
       ru.display_name                     AS raised_by_display_name,
       COALESCE(su.display_name, '')::text AS resolved_by_display_name
FROM disputes d
JOIN users ru ON ru.id = d.raised_by
LEFT JOIN users su ON su.id = d.resolved_by
WHERE d.id = $1
`

type GetDisputeByIDRow struct {
	ID                    uuid.UUID
	BookingID             uuid.UUID
	RaisedBy              uuid.UUID
	Reason                string
	Status                string
	Resolution            string
	ResolvedBy            uuid.NullUUID
	CreatedAt             pgtype.Timestamptz
	ResolvedAt            pgtype.Timestamptz
	RaisedByDisplayName   string
	ResolvedByDisplayName string
}

func (q *Queries) GetDisputeByID(ctx context.Context, id uuid.UUID) (GetDisputeByIDRow, error) {
	row := q.db.QueryRow(ctx, getDisputeByID, id)
	var i GetDisputeByIDRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.RaisedByDisplayName,
		&i.ResolvedByDisplayName,
	)
	return i, err
}

const getOpenDisputeForBooking = `-- name: GetOpenDisputeForBooking :one
SELECT d.id, d.booking_id, d.raised_by, d.reason, d.status, d.resolution,
       d.resolved_by, d.created_at, d.resolved_at,
       ru.display_name AS raised_by_display_name
FROM disputes d
JOIN users ru ON ru.id = d.raised_by
WHERE d.booking_id = $1 AND d.status = 'open'
`

type GetOpenDisputeForBookingRow struct {
	ID                  uuid.UUID
	BookingID           uuid.UUID
	RaisedBy            uuid.UUID
	Reason              string
	Status              string
	Resolution          string
	ResolvedBy          uuid.NullUUID
	CreatedAt           pgtype.Timestamptz
	ResolvedAt          pgtype.Timestamptz
	RaisedByDisplayName string
}

// The booking's open dispute, if any. Backs the `open_dispute` /
// `can_raise_dispute` fields the participant sees on a booking.
func (q *Queries) GetOpenDisputeForBooking(ctx context.Context, bookingID uuid.UUID) (GetOpenDisputeForBookingRow, error) {
	row := q.db.QueryRow(ctx, getOpenDisputeForBooking, bookingID)
	var i GetOpenDisputeForBookingRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.RaisedByDisplayName,
	)
	return i, err
}

const insertDispute = `-- name: InsertDispute :one
INSERT INTO disputes (booking_id, raised_by, reason)
VALUES ($1, $2, $3)
RETURNING id, booking_id, raised_by, reason, status, resolution, resolved_by, created_at, resolved_at
`

type InsertDisputeParams struct {
	BookingID uuid.UUID
	RaisedBy  uuid.UUID
	Reason    string
}

// A second OPEN dispute for the same booking raises SQLSTATE 23505 on
// disputes_one_open_per_booking, which the repository maps to ErrDisputeExists
// (race-safe, never a check-then-insert).
func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, insertDispute, arg.BookingID, arg.RaisedBy, arg.Reason)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listDisputesForBooking = `-- name: ListDisputesForBooking :many
SELECT d.id, d.booking_id, d.raised_by, d.reason, d.status, d.resolution,
       d.resolved_by, d.created_at, d.resolved_at,
       ru.display_name              AS raised_by_display_name,
       COALESCE(su.display_name, '')::text AS resolved_by_display_name
FROM disputes d
JOIN users ru ON ru.id = d.raised_by
LEFT JOIN users su ON su.id = d.resolved_by
WHERE d.booking_id = $1
ORDER BY d.created_at DESC, d.id
`

type ListDisputesForBookingRow struct {
	ID                    uuid.UUID
	BookingID             uuid.UUID
	RaisedBy              uuid.UUID
	Reason                string
	Status                string
	Resolution            string
	ResolvedBy            uuid.NullUUID
	CreatedAt             pgtype.Timestamptz
	ResolvedAt            pgtype.Timestamptz
	RaisedByDisplayName   string
	ResolvedByDisplayName string
}

// The whole dispute thread for one booking, newest first.
func (q *Queries) ListDisputesForBooking(ctx context.Context, bookingID uuid.UUID) ([]ListDisputesForBookingRow, error) {
	rows, err := q.db.Query(ctx, listDisputesForBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputesForBookingRow{}
	for rows.Next() {
		var i ListDisputesForBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.RaisedBy,
			&i.Reason,
			&i.Status,
			&i.Resolution,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.RaisedByDisplayName,
			&i.ResolvedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE disputes
SET status      = $1,
    resolution  = $2,
    resolved_by = $3::uuid,
    resolved_at = now()
WHERE id = $4 AND status = 'open'
RETURNING id, booking_id, raised_by, reason, status, resolution, resolved_by, created_at, resolved_at
`

type ResolveDisputeParams struct {
	Status     string
	Resolution string
	ResolvedBy uuid.UUID
	ID         uuid.UUID
}

// Guarded UPDATE: only an OPEN dispute moves. No rows back means either "no such
// dispute" or "already resolved" — the repository re-reads the row to tell the
// two apart, so a lost race renders 409 already_resolved rather than clobbering
// another operator's resolution.
func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, resolveDispute,
		arg.Status,
		arg.Resolution,
		arg.ResolvedBy,
		arg.ID,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const seedInsertDispute = `-- name: SeedInsertDispute :exec
INSERT INTO disputes (booking_id, raised_by, reason)
VALUES ($1, $2, $3)
`

type SeedInsertDisputeParams struct {
	BookingID uuid.UUID
	RaisedBy  uuid.UUID
	Reason    string
}

// Seed-only: an open dispute on a seeded booking so /v1/admin/disputes is not
// empty on a fresh database.
func (q *Queries) SeedInsertDispute(ctx context.Context, arg SeedInsertDisputeParams) error {
	_, err := q.db.Exec(ctx, seedInsertDispute, arg.BookingID, arg.RaisedBy, arg.Reason)
	return err
}
