// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrencyCode string

const (
	CurrencyCodeUZS CurrencyCode = "UZS"
	CurrencyCodeUSD CurrencyCode = "USD"
)

func (e *CurrencyCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrencyCode(s)
	case string:
		*e = CurrencyCode(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrencyCode: %T", src)
	}
	return nil
}

type NullCurrencyCode struct {
	CurrencyCode CurrencyCode
	Valid        bool // Valid is true if CurrencyCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrencyCode) Scan(value interface{}) error {
	if value == nil {
		ns.CurrencyCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrencyCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrencyCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrencyCode), nil
}

type LanguageLevel string

const (
	LanguageLevelNative LanguageLevel = "native"
	LanguageLevelC2     LanguageLevel = "c2"
	LanguageLevelC1     LanguageLevel = "c1"
	LanguageLevelB2     LanguageLevel = "b2"
	LanguageLevelB1     LanguageLevel = "b1"
	LanguageLevelA2     LanguageLevel = "a2"
	LanguageLevelA1     LanguageLevel = "a1"
)

func (e *LanguageLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LanguageLevel(s)
	case string:
		*e = LanguageLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for LanguageLevel: %T", src)
	}
	return nil
}

type NullLanguageLevel struct {
	LanguageLevel LanguageLevel
	Valid         bool // Valid is true if LanguageLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguageLevel) Scan(value interface{}) error {
	if value == nil {
		ns.LanguageLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LanguageLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguageLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LanguageLevel), nil
}

type LanguageRole string

const (
	LanguageRoleTeaches    LanguageRole = "teaches"
	LanguageRoleAlsoSpeaks LanguageRole = "also_speaks"
)

func (e *LanguageRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LanguageRole(s)
	case string:
		*e = LanguageRole(s)
	default:
		return fmt.Errorf("unsupported scan type for LanguageRole: %T", src)
	}
	return nil
}

type NullLanguageRole struct {
	LanguageRole LanguageRole
	Valid        bool // Valid is true if LanguageRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguageRole) Scan(value interface{}) error {
	if value == nil {
		ns.LanguageRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LanguageRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguageRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LanguageRole), nil
}

type TeacherKind string

const (
	TeacherKindProfessional TeacherKind = "professional"
	TeacherKindCommunity    TeacherKind = "community"
)

func (e *TeacherKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeacherKind(s)
	case string:
		*e = TeacherKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TeacherKind: %T", src)
	}
	return nil
}

type NullTeacherKind struct {
	TeacherKind TeacherKind
	Valid       bool // Valid is true if TeacherKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeacherKind) Scan(value interface{}) error {
	if value == nil {
		ns.TeacherKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeacherKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeacherKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeacherKind), nil
}

type AuthToken struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Purpose     string
	TokenSha256 []byte
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Booking struct {
	ID                 uuid.UUID
	TeacherID          uuid.UUID
	StudentID          uuid.UUID
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	DurationMinutes    int32
	Status             string
	PriceMinor         int64
	Currency           string
	IsTrial            bool
	CancelledAt        pgtype.Timestamptz
	CancellationReason string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	MeetingUrlOverride string
	NoShowParty        string
	CancelledBy        string
}

type Dispute struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	RaisedBy   uuid.UUID
	Reason     string
	Status     string
	Resolution string
	ResolvedBy uuid.NullUUID
	CreatedAt  pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
}

type FileAsset struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Provider    string
	ObjectKey   string
	Filename    string
	ContentType string
	Bytes       int64
	CreatedAt   pgtype.Timestamptz
}

type Payment struct {
	ID           uuid.UUID
	BookingID    uuid.UUID
	Provider     string
	ProviderRef  pgtype.Text
	Status       string
	AmountMinor  int64
	Currency     string
	LastError    string
	AuthorizedAt pgtype.Timestamptz
	CapturedAt   pgtype.Timestamptz
	RefundedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PaymentEvent struct {
	EventID    string
	PaymentID  uuid.UUID
	Type       string
	ReceivedAt pgtype.Timestamptz
}

type PayoutBatch struct {
	ID           uuid.UUID
	CreatedBy    uuid.UUID
	Status       string
	TotalMinor   int64
	Currency     string
	TeacherCount int32
	LineCount    int32
	CreatedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type PayoutLedger struct {
	ID            uuid.UUID
	TeacherID     uuid.UUID
	BookingID     uuid.UUID
	AmountMinor   int64
	Currency      string
	State         string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	AvailableAt   pgtype.Timestamptz
	PaidAt        pgtype.Timestamptz
	PayoutBatchID uuid.NullUUID
}

type Resource struct {
	ID           uuid.UUID
	TeacherID    uuid.UUID
	Type         string
	Title        string
	Instructions string
	Content      []byte
	Status       string
	ArchivedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Review struct {
	ID        uuid.UUID
	TeacherID uuid.UUID
	StudentID uuid.UUID
	BookingID uuid.NullUUID
	Rating    int16
	Comment   string
	CreatedAt pgtype.Timestamptz
	Hidden    bool
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID     uuid.UUID
	Permission string
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash []byte
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	ReplacedBy       uuid.NullUUID
	UserAgent        string
	CreatedAt        pgtype.Timestamptz
}

type Teacher struct {
	ID                uuid.UUID
	Slug              string
	DisplayName       string
	Headline          string
	Kind              TeacherKind
	CountryCode       string
	CountryName       string
	City              string
	Timezone          string
	PricePerHourMinor int64
	TrialPriceMinor   pgtype.Int8
	Currency          CurrencyCode
	Rating            float32
	ReviewCount       int32
	LessonsCompleted  int32
	StudentCount      int32
	ResponseTimeHours int32
	AcceptingStudents bool
	AvatarUrl         string
	VideoThumbnailUrl string
	IntroVideoUrl     string
	About             string
	TeachingStyle     string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	UserID            uuid.NullUUID
	MeetingUrl        string
	Status            string
	Verified          bool
	ModerationNote    string
	RatingBase        float32
	ReviewCountBase   int32
}

type TeacherAvailabilitySlot struct {
	ID          int64
	TeacherID   uuid.UUID
	Weekday     int16
	StartMinute int32
	EndMinute   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TeacherExperience struct {
	ID        int64
	TeacherID uuid.UUID
	Title     string
	Org       string
	Period    string
	Position  int32
}

type TeacherFocu struct {
	TeacherID uuid.UUID
	Tag       string
	Position  int32
}

type TeacherLanguage struct {
	TeacherID uuid.UUID
	Role      LanguageRole
	Code      string
	Name      string
	Level     LanguageLevel
	Position  int32
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	DisplayName     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	GrantedAt pgtype.Timestamptz
}
