// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmBookingForPayment = `-- name: ConfirmBookingForPayment :exec
UPDATE bookings
SET status = 'confirmed', updated_at = now()
WHERE id = $1 AND status = 'pending_payment'
`

// System transition (no participant check): pending_payment -> confirmed on a
// successful authorization webhook. Guarded so a replay cannot resurrect a
// cancelled booking.
func (q *Queries) ConfirmBookingForPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmBookingForPayment, id)
	return err
}

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (booking_id, provider, status, amount_minor, currency)
VALUES ($1, $2, 'requires_payment', $3, $4)
ON CONFLICT (booking_id) DO UPDATE SET booking_id = payments.booking_id
RETURNING id, booking_id, provider, provider_ref, status, amount_minor, currency,
          last_error, authorized_at, captured_at, refunded_at, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID   uuid.UUID
	Provider    string
	AmountMinor int64
	Currency    string
}

// Payments module: one payment intent per booking, the webhook-event log that
// guards idempotency, and the simplified teacher-earnings ledger. Money is
// integer minor units everywhere.
// Eagerly created right after a booking is inserted. Idempotent: a second call
// for the same booking is a no-op and still returns the existing row.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.Provider,
		arg.AmountMinor,
		arg.Currency,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.LastError,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllPaymentEvents = `-- name: DeleteAllPaymentEvents :exec
DELETE FROM payment_events
`

func (q *Queries) DeleteAllPaymentEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPaymentEvents)
	return err
}

const deleteAllPayments = `-- name: DeleteAllPayments :exec
DELETE FROM payments
`

// Seed-only. payments.booking_id references bookings with no ON DELETE CASCADE,
// so the seed must clear payment rows (and the event log / ledger that
// reference them) before bookings.
func (q *Queries) DeleteAllPayments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPayments)
	return err
}

const deleteAllPayoutLedger = `-- name: DeleteAllPayoutLedger :exec
DELETE FROM payout_ledger
`

func (q *Queries) DeleteAllPayoutLedger(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPayoutLedger)
	return err
}

const getPaymentByBooking = `-- name: GetPaymentByBooking :one
SELECT id, booking_id, provider, provider_ref, status, amount_minor, currency,
       last_error, authorized_at, captured_at, refunded_at, created_at, updated_at
FROM payments
WHERE booking_id = $1
`

func (q *Queries) GetPaymentByBooking(ctx context.Context, bookingID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBooking, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.LastError,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, booking_id, provider, provider_ref, status, amount_minor, currency,
       last_error, authorized_at, captured_at, refunded_at, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.LastError,
		&i.AuthorizedAt,
		&i.CapturedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCourseLedgerHeld = `-- name: InsertCourseLedgerHeld :exec
INSERT INTO payout_ledger (teacher_id, course_enrollment_id, amount_minor, currency, state, available_at)
SELECT co.teacher_id, ce.id,
       $1::bigint,
       $2::text,
       'held',
       now() + make_interval(days => $3::int)
FROM course_enrollments ce
JOIN courses co ON co.id = ce.course_id
WHERE ce.id = $4
ON CONFLICT (course_enrollment_id) DO NOTHING
`

type InsertCourseLedgerHeldParams struct {
	AmountMinor        int64
	Currency           string
	ClearingDays       int32
	CourseEnrollmentID uuid.UUID
}

// Phase C3: the course-purchase sibling of InsertLedgerHeld. One row per
// captured course sale, keyed on course_enrollment_id instead of booking_id
// (see payout_ledger's booking_id/course_enrollment_id CHECK, migration
// 000018). teacher_id is derived by joining the enrollment to its course;
// amount_minor is the teacher's already-computed revenue-share (Go arithmetic
// in payments.CourseService.CreditCourseSale, never derived here), and
// available_at opens the same clearing window as a lesson's earning: capture
// time + PAYOUTS_CLEARING_DAYS.
//
// Called by courses.Service.Purchase (via the courses.PaymentGateway port)
// right after the enrollment row is created, NOT from this package's own
// ApplyCourseEvent webhook handler on payment.captured — unlike a booking
// (which exists before its payment), a course_enrollment does not exist yet
// at capture time, so there is no enrollment id to attach a ledger row to
// until courses.Service creates one. See CreditCourseSale's doc comment.
//
// ON CONFLICT (course_enrollment_id) DO NOTHING is the idempotency guard: a
// retried/duplicate call for the same enrollment (e.g. a concurrent
// double-submit racing EnsureEnrollment) never double-credits the teacher.
func (q *Queries) InsertCourseLedgerHeld(ctx context.Context, arg InsertCourseLedgerHeldParams) error {
	_, err := q.db.Exec(ctx, insertCourseLedgerHeld,
		arg.AmountMinor,
		arg.Currency,
		arg.ClearingDays,
		arg.CourseEnrollmentID,
	)
	return err
}

const insertLedgerHeld = `-- name: InsertLedgerHeld :exec
INSERT INTO payout_ledger (teacher_id, booking_id, amount_minor, currency, state, available_at)
SELECT b.teacher_id, b.id,
       $1::bigint,
       $2::text,
       'held',
       now() + make_interval(days => $3::int)
FROM bookings b
WHERE b.id = $4
ON CONFLICT (booking_id) DO NOTHING
`

type InsertLedgerHeldParams struct {
	AmountMinor  int64
	Currency     string
	ClearingDays int32
	BookingID    uuid.UUID
}

// One row per captured booking. teacher_id is copied from the booking, and
// available_at opens the clearing window: capture time + PAYOUTS_CLEARING_DAYS.
// The row stays 'held' until a payout run settles it (phase E) — nothing flips
// it to 'available'; that state is derived from available_at at read time.
func (q *Queries) InsertLedgerHeld(ctx context.Context, arg InsertLedgerHeldParams) error {
	_, err := q.db.Exec(ctx, insertLedgerHeld,
		arg.AmountMinor,
		arg.Currency,
		arg.ClearingDays,
		arg.BookingID,
	)
	return err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :exec
INSERT INTO payment_events (event_id, payment_id, type)
VALUES ($1, $2, $3)
`

type InsertPaymentEventParams struct {
	EventID   string
	PaymentID uuid.UUID
	Type      string
}

// The idempotency gate. A duplicate event_id raises SQLSTATE 23505, which the
// repository treats as "already processed".
func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) error {
	_, err := q.db.Exec(ctx, insertPaymentEvent, arg.EventID, arg.PaymentID, arg.Type)
	return err
}

const listTeacherEarnings = `-- name: ListTeacherEarnings :many
SELECT pl.booking_id, pl.course_enrollment_id, pl.amount_minor, pl.currency, pl.state, pl.available_at,
       coalesce(b.start_at, ce.created_at) AS start_at,
       coalesce(bu.display_name, cu.display_name) AS student_display_name,
       co.title AS course_title
FROM payout_ledger pl
LEFT JOIN bookings b ON b.id = pl.booking_id
LEFT JOIN users bu ON bu.id = b.student_id
LEFT JOIN course_enrollments ce ON ce.id = pl.course_enrollment_id
LEFT JOIN courses co ON co.id = ce.course_id
LEFT JOIN users cu ON cu.id = ce.student_id
WHERE pl.teacher_id = $1
ORDER BY coalesce(b.start_at, ce.created_at) DESC, pl.id
`

type ListTeacherEarningsRow struct {
	BookingID          uuid.NullUUID
	CourseEnrollmentID uuid.NullUUID
	AmountMinor        int64
	Currency           string
	State              string
	AvailableAt        pgtype.Timestamptz
	StartAt            pgtype.Timestamptz
	StudentDisplayName string
	CourseTitle        pgtype.Text
}

// Phase C3 widens this to a teacher's course-sale earnings alongside their
// lesson earnings: LEFT JOIN both sources (a row's booking_id XOR
// course_enrollment_id is set, per the ledger's own CHECK) and coalesce the
// "when" and "counterparty name" columns so a client sees one uniform shape.
// course_title is NULL for a lesson row, non-NULL for a course row — the
// discriminator a client uses to render each line differently.
func (q *Queries) ListTeacherEarnings(ctx context.Context, teacherID uuid.UUID) ([]ListTeacherEarningsRow, error) {
	rows, err := q.db.Query(ctx, listTeacherEarnings, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherEarningsRow{}
	for rows.Next() {
		var i ListTeacherEarningsRow
		if err := rows.Scan(
			&i.BookingID,
			&i.CourseEnrollmentID,
			&i.AmountMinor,
			&i.Currency,
			&i.State,
			&i.AvailableAt,
			&i.StartAt,
			&i.StudentDisplayName,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCourseLedgerReversedByCourseAndStudent = `-- name: MarkCourseLedgerReversedByCourseAndStudent :exec
UPDATE payout_ledger pl
SET state = 'reversed', updated_at = now()
FROM course_enrollments ce
WHERE pl.course_enrollment_id = ce.id
  AND ce.course_id = $1
  AND ce.student_id = $2
  AND pl.state NOT IN ('reversed', 'paid')
`

type MarkCourseLedgerReversedByCourseAndStudentParams struct {
	CourseID  uuid.UUID
	StudentID uuid.UUID
}

// The course sibling of MarkLedgerReversed. A refunded course_payment carries
// no enrollment id of its own (the enrollment is created by courses.Service
// only after a successful capture, see InsertCourseLedgerHeld's doc comment),
// so the reversal is keyed by (course_id, student_id) instead — at most one
// enrollment exists per (course, student) pair (course_enrollments' own
// unique constraint), so this reverses exactly the one ledger row a refund on
// that course payment could ever correspond to. Same "not already
// paid/reversed" guard as MarkLedgerReversed.
func (q *Queries) MarkCourseLedgerReversedByCourseAndStudent(ctx context.Context, arg MarkCourseLedgerReversedByCourseAndStudentParams) error {
	_, err := q.db.Exec(ctx, markCourseLedgerReversedByCourseAndStudent, arg.CourseID, arg.StudentID)
	return err
}

const markLedgerReversed = `-- name: MarkLedgerReversed :exec
UPDATE payout_ledger
SET state = 'reversed', updated_at = now()
WHERE booking_id = $1 AND state NOT IN ('reversed', 'paid')
`

// A refund reverses the teacher's earning — unless a payout batch already paid
// it out, which cannot be un-paid from here (the money has left the platform).
func (q *Queries) MarkLedgerReversed(ctx context.Context, bookingID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, markLedgerReversed, bookingID)
	return err
}

const markPaymentAuthorized = `-- name: MarkPaymentAuthorized :exec
UPDATE payments
SET status = 'authorized', provider_ref = $2, last_error = '',
    authorized_at = now(), updated_at = now()
WHERE id = $1
`

type MarkPaymentAuthorizedParams struct {
	ID          uuid.UUID
	ProviderRef pgtype.Text
}

func (q *Queries) MarkPaymentAuthorized(ctx context.Context, arg MarkPaymentAuthorizedParams) error {
	_, err := q.db.Exec(ctx, markPaymentAuthorized, arg.ID, arg.ProviderRef)
	return err
}

const markPaymentCaptured = `-- name: MarkPaymentCaptured :exec
UPDATE payments
SET status = 'captured', captured_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkPaymentCaptured(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentCaptured, id)
	return err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :exec
UPDATE payments
SET status = 'failed', last_error = $2, updated_at = now()
WHERE id = $1
`

type MarkPaymentFailedParams struct {
	ID        uuid.UUID
	LastError string
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error {
	_, err := q.db.Exec(ctx, markPaymentFailed, arg.ID, arg.LastError)
	return err
}

const markPaymentRefunded = `-- name: MarkPaymentRefunded :exec
UPDATE payments
SET status = 'refunded', refunded_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkPaymentRefunded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentRefunded, id)
	return err
}

const seedInsertCapturedPayment = `-- name: SeedInsertCapturedPayment :exec
INSERT INTO payments (booking_id, provider, provider_ref, status, amount_minor,
                      currency, authorized_at, captured_at)
VALUES ($1, 'fake', $2, 'captured', $3, $4, now(), now())
`

type SeedInsertCapturedPaymentParams struct {
	BookingID   uuid.UUID
	ProviderRef pgtype.Text
	AmountMinor int64
	Currency    string
}

// Seed-only: a settled payment for a booking the seed created directly in the
// `completed` state, so the payout ledger row it carries has a matching intent.
func (q *Queries) SeedInsertCapturedPayment(ctx context.Context, arg SeedInsertCapturedPaymentParams) error {
	_, err := q.db.Exec(ctx, seedInsertCapturedPayment,
		arg.BookingID,
		arg.ProviderRef,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}
