// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountPayoutBatches = `-- name: AdminCountPayoutBatches :one
SELECT count(*) FROM payout_batches
`

func (q *Queries) AdminCountPayoutBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountPayoutBatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetPayoutBatch = `-- name: AdminGetPayoutBatch :one
SELECT b.id, b.created_by, u.display_name AS created_by_display_name,
       b.status, b.total_minor, b.currency, b.teacher_count, b.line_count,
       b.created_at, b.completed_at
FROM payout_batches b
JOIN users u ON u.id = b.created_by
WHERE b.id = $1
`

type AdminGetPayoutBatchRow struct {
	ID                   uuid.UUID
	CreatedBy            uuid.UUID
	CreatedByDisplayName string
	Status               string
	TotalMinor           int64
	Currency             string
	TeacherCount         int32
	LineCount            int32
	CreatedAt            pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
}

func (q *Queries) AdminGetPayoutBatch(ctx context.Context, id uuid.UUID) (AdminGetPayoutBatchRow, error) {
	row := q.db.QueryRow(ctx, adminGetPayoutBatch, id)
	var i AdminGetPayoutBatchRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CreatedByDisplayName,
		&i.Status,
		&i.TotalMinor,
		&i.Currency,
		&i.TeacherCount,
		&i.LineCount,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const adminListOwedPayouts = `-- name: AdminListOwedPayouts :many

SELECT t.slug,
       t.display_name,
       pl.currency,
       sum(pl.amount_minor)::bigint      AS available_minor,
       min(pl.available_at)::timestamptz AS oldest_available_at
FROM payout_ledger pl
JOIN teachers t ON t.id = pl.teacher_id
WHERE pl.state IN ('held', 'available') AND pl.available_at <= now()
GROUP BY t.slug, t.display_name, pl.currency
ORDER BY sum(pl.amount_minor) DESC, t.slug
`

type AdminListOwedPayoutsRow struct {
	Slug              string
	DisplayName       string
	Currency          string
	AvailableMinor    int64
	OldestAvailableAt pgtype.Timestamptz
}

// Payouts module (phase E): the operator payout dashboard and the payout run
// that settles what teachers are owed.
//
// The clearing window is derived, not materialised: a ledger row is payable when
// its state is still open (`held`, or the legacy `available` written before
// migration 000011) AND its available_at deadline has passed. Money is integer
// minor units everywhere.
// What the platform owes right now, one row per teacher: the sum of the ledger
// rows past their clearing deadline and not yet paid out, biggest first.
func (q *Queries) AdminListOwedPayouts(ctx context.Context) ([]AdminListOwedPayoutsRow, error) {
	rows, err := q.db.Query(ctx, adminListOwedPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOwedPayoutsRow{}
	for rows.Next() {
		var i AdminListOwedPayoutsRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Currency,
			&i.AvailableMinor,
			&i.OldestAvailableAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPayoutBatchLines = `-- name: AdminListPayoutBatchLines :many
SELECT t.slug,
       t.display_name,
       pl.currency,
       sum(pl.amount_minor)::bigint AS amount_minor,
       count(*)::int                AS lesson_count
FROM payout_ledger pl
JOIN teachers t ON t.id = pl.teacher_id
WHERE pl.payout_batch_id = $1
GROUP BY t.slug, t.display_name, pl.currency
ORDER BY sum(pl.amount_minor) DESC, t.slug
`

type AdminListPayoutBatchLinesRow struct {
	Slug        string
	DisplayName string
	Currency    string
	AmountMinor int64
	LessonCount int32
}

// One line per teacher paid by a batch, biggest first.
func (q *Queries) AdminListPayoutBatchLines(ctx context.Context, payoutBatchID uuid.NullUUID) ([]AdminListPayoutBatchLinesRow, error) {
	rows, err := q.db.Query(ctx, adminListPayoutBatchLines, payoutBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPayoutBatchLinesRow{}
	for rows.Next() {
		var i AdminListPayoutBatchLinesRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Currency,
			&i.AmountMinor,
			&i.LessonCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPayoutBatches = `-- name: AdminListPayoutBatches :many
SELECT b.id, b.created_by, u.display_name AS created_by_display_name,
       b.status, b.total_minor, b.currency, b.teacher_count, b.line_count,
       b.created_at, b.completed_at
FROM payout_batches b
JOIN users u ON u.id = b.created_by
ORDER BY b.created_at DESC, b.id
LIMIT $2::int OFFSET $1::int
`

type AdminListPayoutBatchesParams struct {
	PageOffset int32
	PageLimit  int32
}

type AdminListPayoutBatchesRow struct {
	ID                   uuid.UUID
	CreatedBy            uuid.UUID
	CreatedByDisplayName string
	Status               string
	TotalMinor           int64
	Currency             string
	TeacherCount         int32
	LineCount            int32
	CreatedAt            pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
}

// Past payout runs, newest first.
func (q *Queries) AdminListPayoutBatches(ctx context.Context, arg AdminListPayoutBatchesParams) ([]AdminListPayoutBatchesRow, error) {
	rows, err := q.db.Query(ctx, adminListPayoutBatches, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPayoutBatchesRow{}
	for rows.Next() {
		var i AdminListPayoutBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CreatedByDisplayName,
			&i.Status,
			&i.TotalMinor,
			&i.Currency,
			&i.TeacherCount,
			&i.LineCount,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPayoutTotals = `-- name: AdminPayoutTotals :one
SELECT
    coalesce(sum(amount_minor) FILTER (
        WHERE state IN ('held', 'available') AND available_at <= now()), 0)::bigint AS available_total_minor,
    coalesce(sum(amount_minor) FILTER (
        WHERE state IN ('held', 'available') AND available_at > now()), 0)::bigint  AS held_total_minor,
    coalesce(sum(amount_minor) FILTER (WHERE state = 'paid'), 0)::bigint            AS paid_total_minor,
    coalesce(max(currency), '')::text                                               AS currency
FROM payout_ledger
`

type AdminPayoutTotalsRow struct {
	AvailableTotalMinor int64
	HeldTotalMinor      int64
	PaidTotalMinor      int64
	Currency            string
}

// Platform-wide ledger totals: payable now, still inside the clearing window,
// and already disbursed. Reversed rows count towards none of them.
func (q *Queries) AdminPayoutTotals(ctx context.Context) (AdminPayoutTotalsRow, error) {
	row := q.db.QueryRow(ctx, adminPayoutTotals)
	var i AdminPayoutTotalsRow
	err := row.Scan(
		&i.AvailableTotalMinor,
		&i.HeldTotalMinor,
		&i.PaidTotalMinor,
		&i.Currency,
	)
	return i, err
}

const deleteAllPayoutBatches = `-- name: DeleteAllPayoutBatches :exec
DELETE FROM payout_batches
`

// Seed-only. payout_ledger.payout_batch_id references payout_batches with no
// ON DELETE CASCADE, so the seed clears the ledger first, and payout_batches
// before users (created_by).
func (q *Queries) DeleteAllPayoutBatches(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPayoutBatches)
	return err
}

const insertPayoutBatch = `-- name: InsertPayoutBatch :one
INSERT INTO payout_batches (created_by, status, total_minor, currency,
                            teacher_count, line_count, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, created_at, completed_at
`

type InsertPayoutBatchParams struct {
	CreatedBy    uuid.UUID
	Status       string
	TotalMinor   int64
	Currency     string
	TeacherCount int32
	LineCount    int32
}

type InsertPayoutBatchRow struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

// The fake provider settles in-process, so a batch is written already
// 'completed' in the same transaction that marks its rows paid. A real
// disbursement API would insert 'processing' here and flip it afterwards.
func (q *Queries) InsertPayoutBatch(ctx context.Context, arg InsertPayoutBatchParams) (InsertPayoutBatchRow, error) {
	row := q.db.QueryRow(ctx, insertPayoutBatch,
		arg.CreatedBy,
		arg.Status,
		arg.TotalMinor,
		arg.Currency,
		arg.TeacherCount,
		arg.LineCount,
	)
	var i InsertPayoutBatchRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.CompletedAt)
	return i, err
}

const lockPayablePayoutLedger = `-- name: LockPayablePayoutLedger :many
SELECT id, teacher_id, amount_minor, currency
FROM payout_ledger
WHERE state IN ('held', 'available') AND available_at <= now()
ORDER BY id
FOR UPDATE SKIP LOCKED
`

type LockPayablePayoutLedgerRow struct {
	ID          uuid.UUID
	TeacherID   uuid.UUID
	AmountMinor int64
	Currency    string
}

// The payout run's row selection, inside the run's transaction.
//
// FOR UPDATE SKIP LOCKED is the double-run guard: two operators running at the
// same time get disjoint row sets — the second skips the rows the first has
// locked rather than blocking on them or settling them a second time — and the
// loser typically ends up with nothing to pay (409 nothing_to_pay).
func (q *Queries) LockPayablePayoutLedger(ctx context.Context) ([]LockPayablePayoutLedgerRow, error) {
	rows, err := q.db.Query(ctx, lockPayablePayoutLedger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockPayablePayoutLedgerRow{}
	for rows.Next() {
		var i LockPayablePayoutLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.AmountMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLedgerRowsPaid = `-- name: MarkLedgerRowsPaid :exec
UPDATE payout_ledger
SET state = 'paid', payout_batch_id = $1,
    paid_at = now(), updated_at = now()
WHERE id = ANY ($2::uuid[]) AND state <> 'paid'
`

type MarkLedgerRowsPaidParams struct {
	PayoutBatchID uuid.NullUUID
	Ids           []uuid.UUID
}

// Settles exactly the rows the run locked. The state guard is belt-and-braces:
// FOR UPDATE SKIP LOCKED already makes the set exclusive.
func (q *Queries) MarkLedgerRowsPaid(ctx context.Context, arg MarkLedgerRowsPaidParams) error {
	_, err := q.db.Exec(ctx, markLedgerRowsPaid, arg.PayoutBatchID, arg.Ids)
	return err
}

const seedInsertPayoutLedgerRow = `-- name: SeedInsertPayoutLedgerRow :exec
INSERT INTO payout_ledger (teacher_id, booking_id, amount_minor, currency, state,
                           available_at, paid_at, payout_batch_id)
SELECT b.teacher_id, b.id,
       $1::bigint,
       $2::text,
       $3::text,
       now() - make_interval(days => $4::int),
       CASE WHEN $5::uuid IS NULL THEN NULL ELSE now() END,
       $5::uuid
FROM bookings b
WHERE b.id = $6
`

type SeedInsertPayoutLedgerRowParams struct {
	AmountMinor    int64
	Currency       string
	State          string
	ClearedDaysAgo int32
	PayoutBatchID  uuid.NullUUID
	BookingID      uuid.UUID
}

// Seed-only: a ledger row for a booking the seed created directly in the
// `completed` state, with its clearing deadline placed in the past so the
// payout dashboard is not empty on a fresh database. A non-null batch id also
// marks the row paid.
func (q *Queries) SeedInsertPayoutLedgerRow(ctx context.Context, arg SeedInsertPayoutLedgerRowParams) error {
	_, err := q.db.Exec(ctx, seedInsertPayoutLedgerRow,
		arg.AmountMinor,
		arg.Currency,
		arg.State,
		arg.ClearedDaysAgo,
		arg.PayoutBatchID,
		arg.BookingID,
	)
	return err
}
