// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAvailabilitySlot(ctx context.Context, arg AddAvailabilitySlotParams) error
	AddTeacherExperience(ctx context.Context, arg AddTeacherExperienceParams) error
	AddTeacherFocus(ctx context.Context, arg AddTeacherFocusParams) error
	AddTeacherLanguage(ctx context.Context, arg AddTeacherLanguageParams) error
	CancelBooking(ctx context.Context, arg CancelBookingParams) error
	// System transition (no participant check): pending_payment -> confirmed on a
	// successful authorization webhook. Guarded so a replay cannot resurrect a
	// cancelled booking.
	ConfirmBookingForPayment(ctx context.Context, id uuid.UUID) error
	CountTeachers(ctx context.Context, arg CountTeachersParams) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error)
	// Payments module: one payment intent per booking, the webhook-event log that
	// guards idempotency, and the simplified teacher-earnings ledger. Money is
	// integer minor units everywhere.
	// Eagerly created right after a booking is inserted. Idempotent: a second call
	// for the same booking is a no-op and still returns the existing row.
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (uuid.UUID, error)
	// Auth module: user accounts and refresh-token sessions.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Seed-only. bookings.teacher_id / student_id reference teachers / users with
	// no ON DELETE CASCADE, so the seed must clear bookings before those tables.
	DeleteAllBookings(ctx context.Context) error
	DeleteAllPaymentEvents(ctx context.Context) error
	// Seed-only. payments.booking_id references bookings with no ON DELETE CASCADE,
	// so the seed must clear payment rows (and the event log / ledger that
	// reference them) before bookings.
	DeleteAllPayments(ctx context.Context) error
	DeleteAllPayoutLedger(ctx context.Context) error
	DeleteAllTeachers(ctx context.Context) error
	// Seed-only. teachers.user_id references users, so callers must clear teachers
	// first.
	DeleteAllUsers(ctx context.Context) error
	DeleteAvailabilitySlots(ctx context.Context, teacherID uuid.UUID) error
	DeleteTeacherExperience(ctx context.Context, teacherID uuid.UUID) error
	DeleteTeacherFocus(ctx context.Context, teacherID uuid.UUID) error
	DeleteTeacherLanguages(ctx context.Context, teacherID uuid.UUID) error
	GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error)
	// Booking module: concrete scheduled lessons. Times are UTC timestamptz. The
	// recurring weekly availability is read via the availability queries; here we
	// only need the teacher context, existing bookings for overlap checks, and the
	// booking rows themselves (joined to a light teacher + student summary so the
	// frontend lists avoid N+1 calls).
	// Slug -> everything the booking flow needs: identity, timezone, pricing, and
	// the owning account (drives the "can't book yourself" check).
	GetBookingTeacherContext(ctx context.Context, slug string) (GetBookingTeacherContextRow, error)
	GetPaymentByBooking(ctx context.Context, bookingID uuid.UUID) (Payment, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error)
	// Availability module: a teacher's weekly recurring slots (UTC minutes).
	// Resolve a slug to the teacher id, timezone, and owning user the availability
	// endpoints need (user_id drives the ownership check on PUT).
	GetTeacherAvailabilityContext(ctx context.Context, slug string) (GetTeacherAvailabilityContextRow, error)
	GetTeacherBySlug(ctx context.Context, slug string) (Teacher, error)
	// The teacher profile owned by an account (one per user), or no rows.
	GetTeacherIDByOwner(ctx context.Context, userID uuid.NullUUID) (uuid.UUID, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// One row per captured booking. teacher_id is copied from the booking.
	InsertLedgerHeld(ctx context.Context, arg InsertLedgerHeldParams) error
	// The idempotency gate. A duplicate event_id raises SQLSTATE 23505, which the
	// repository treats as "already processed".
	InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) error
	// Count of teachers per taught language across the whole catalog. Drives the
	// language filter in the UI, so it is intentionally unfiltered.
	LanguageFacets(ctx context.Context) ([]LanguageFacetsRow, error)
	ListAvailabilitySlots(ctx context.Context, teacherID uuid.UUID) ([]ListAvailabilitySlotsRow, error)
	// Bookings the caller participates in. Pass the caller's user id as
	// student_filter and/or the caller-owned teacher id as teacher_filter; use the
	// all-zero uuid for a dimension that should not match. Newest lesson first.
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error)
	ListExperienceForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]ListExperienceForTeachersRow, error)
	ListFocusForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]TeacherFocu, error)
	ListLanguagesForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]TeacherLanguage, error)
	// Non-cancelled bookings for a teacher that overlap the [from, to) window, for
	// server-side slot generation and the pre-insert bookability re-check.
	ListTeacherBookingIntervals(ctx context.Context, arg ListTeacherBookingIntervalsParams) ([]ListTeacherBookingIntervalsRow, error)
	ListTeacherEarnings(ctx context.Context, teacherID uuid.UUID) ([]ListTeacherEarningsRow, error)
	ListTeacherSlugs(ctx context.Context) ([]string, error)
	// Page of teachers matching the optional filters, ordered by the requested sort.
	// Child collections (languages, focus, experience) are loaded separately by the
	// repository using the returned ids.
	ListTeachers(ctx context.Context, arg ListTeachersParams) ([]Teacher, error)
	// MVP: 'held' clears to 'available' immediately (no hold period).
	// TODO(payouts): real clearing window.
	MarkLedgerAvailable(ctx context.Context, bookingID uuid.UUID) error
	MarkLedgerReversed(ctx context.Context, bookingID uuid.UUID) error
	MarkPaymentAuthorized(ctx context.Context, arg MarkPaymentAuthorizedParams) error
	MarkPaymentCaptured(ctx context.Context, id uuid.UUID) error
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error
	MarkPaymentRefunded(ctx context.Context, id uuid.UUID) error
	// Reuse-detection hammer: kills every still-active session for a user.
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	// Marks a session revoked and records the session that replaced it (rotation).
	// No-op if it was already revoked.
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	// Per-booking meeting link override. An empty string clears it (fall back to the
	// teacher's default meeting_url).
	SetBookingMeetingLinkOverride(ctx context.Context, arg SetBookingMeetingLinkOverrideParams) error
	// Records who missed the lesson. The status transition (completed on a student
	// no-show, cancelled on a teacher no-show) is applied separately via
	// SetBookingStatus / CancelBooking so the capture / refund path is reused.
	SetBookingNoShowParty(ctx context.Context, arg SetBookingNoShowPartyParams) error
	SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) error
	// The teacher profile owned by a user (one per user), or no rows.
	TeacherRefByOwner(ctx context.Context, userID uuid.NullUUID) (TeacherRefByOwnerRow, error)
	// Write queries: the demo seed plus the dashboard's create/update-profile flow.
	// Slug -> id + owning user, for the ownership check on PATCH /v1/teachers/{slug}.
	TeacherRefBySlug(ctx context.Context, slug string) (TeacherRefBySlugRow, error)
	TeacherSlugExists(ctx context.Context, slug string) (bool, error)
	// Edit the caller-editable profile fields. Server-controlled aggregates (rating,
	// review_count, lessons_completed, student_count, response_time_hours,
	// accepting_students) and the slug are intentionally left untouched.
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) error
	// Edit the caller's own account. Email is immutable here (changing it needs a
	// verification flow that does not exist yet).
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
