// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAvailabilitySlot(ctx context.Context, arg AddAvailabilitySlotParams) error
	// Items.
	// position is the current item count for the section, same idiom as sections.
	// is_preview / duration_seconds are phase-D1 video metadata; the service has
	// already refused a preview or a duration on a non-video item before we get
	// here, and the table's CHECKs are the backstop.
	AddCourseItem(ctx context.Context, arg AddCourseItemParams) (CourseItem, error)
	// Sections.
	// position is the current section count for the course, computed here so the
	// insert stays a single statement (same idiom as AttachBookingResource).
	AddCourseSection(ctx context.Context, arg AddCourseSectionParams) (CourseSection, error)
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AddTeacherExperience(ctx context.Context, arg AddTeacherExperienceParams) error
	AddTeacherFocus(ctx context.Context, arg AddTeacherFocusParams) error
	AddTeacherLanguage(ctx context.Context, arg AddTeacherLanguageParams) error
	// gmv_minor = booking price that actually flowed: bookings that reached
	// confirmed or completed. this_week = created in the last 7 days. upcoming =
	// confirmed and not yet started. active_students = distinct people who booked.
	AdminBookingStats(ctx context.Context) (AdminBookingStatsRow, error)
	AdminCountBookings(ctx context.Context, arg AdminCountBookingsParams) (int64, error)
	AdminCountCourseReviews(ctx context.Context, arg AdminCountCourseReviewsParams) (int64, error)
	AdminCountCourses(ctx context.Context, arg AdminCountCoursesParams) (int64, error)
	AdminCountDisputes(ctx context.Context, status pgtype.Text) (int64, error)
	AdminCountPayoutBatches(ctx context.Context) (int64, error)
	// Same filters as AdminListReviews — the total match count for pagination.
	AdminCountReviews(ctx context.Context, arg AdminCountReviewsParams) (int64, error)
	AdminCountTeachers(ctx context.Context, arg AdminCountTeachersParams) (int64, error)
	AdminCountUsers(ctx context.Context, q_ pgtype.Text) (int64, error)
	// The activity chart (GET /v1/admin/metrics/activity) is two ranged reads. Days
	// are UTC calendar days (the server's date), zero-filled so the series always
	// has one point per day and the chart needs no gap handling.
	AdminDailyActivity(ctx context.Context, days int32) ([]AdminDailyActivityRow, error)
	// One booking with everything the operator detail view shows: the list-row
	// fields plus the lifecycle extras, the effective meeting link (the per-booking
	// override if set, else the teacher's default), and the payment detail.
	AdminGetBooking(ctx context.Context, id uuid.UUID) (AdminGetBookingRow, error)
	// One moderation-queue row by id, with the course title and student name the
	// bare course_reviews row can't carry. Used to build the response after a
	// hide/unhide, whose RETURNING clause only sees the one table.
	AdminGetCourseReview(ctx context.Context, id uuid.UUID) (AdminGetCourseReviewRow, error)
	AdminGetPayoutBatch(ctx context.Context, id uuid.UUID) (AdminGetPayoutBatchRow, error)
	AdminGetReview(ctx context.Context, id uuid.UUID) (AdminGetReviewRow, error)
	AdminGetTeacherModeration(ctx context.Context, slug string) (AdminGetTeacherModerationRow, error)
	AdminGetUser(ctx context.Context, id uuid.UUID) (AdminGetUserRow, error)
	AdminGetUserTeacherProfile(ctx context.Context, userID uuid.NullUUID) (AdminGetUserTeacherProfileRow, error)
	// The booking's full dispute thread, newest first. Read straight from the
	// disputes table: the admin surface is an ops tool, not a public API (see the
	// package doc), so it does not route this through the disputes service.
	AdminListBookingDisputes(ctx context.Context, bookingID uuid.UUID) ([]AdminListBookingDisputesRow, error)
	// --- phase D: bookings admin ---
	// Every booking on the platform (not just the caller's), newest lesson first.
	// `status` is an optional exact filter; `q` matches the teacher's display name
	// or slug and the student's email or display name. payment_status is '' when the
	// booking has no intent yet (payments.booking_id is UNIQUE, so the LEFT JOIN
	// cannot fan the row set out).
	AdminListBookings(ctx context.Context, arg AdminListBookingsParams) ([]AdminListBookingsRow, error)
	// The moderation queue: every course review regardless of visibility, newest
	// first, optionally narrowed to one visibility, one course, or a rating
	// ceiling (to surface the low-star reviews an operator is looking for).
	AdminListCourseReviews(ctx context.Context, arg AdminListCourseReviewsParams) ([]AdminListCourseReviewsRow, error)
	// Phase C3: admin moderation.
	// The operator moderation queue: every course regardless of status/teacher/
	// suspension, newest first. Filters mirror reviews' ModerationQuery shape:
	// status ('draft'|'published'|'archived', "archived" meaning archived_at IS NOT
	// NULL regardless of the underlying status column), suspended ('true'|'false'),
	// teacher_slug, and a title substring q — each NULL/empty means "any".
	AdminListCourses(ctx context.Context, arg AdminListCoursesParams) ([]AdminListCoursesRow, error)
	// The operator queue: disputes filtered by status (default 'open' in the
	// service), each with the booking + parties context the list view renders.
	AdminListDisputes(ctx context.Context, arg AdminListDisputesParams) ([]AdminListDisputesRow, error)
	// Payouts module (phase E): the operator payout dashboard and the payout run
	// that settles what teachers are owed.
	//
	// The clearing window is derived, not materialised: a ledger row is payable when
	// its state is still open (`held`, or the legacy `available` written before
	// migration 000011) AND its available_at deadline has passed. Money is integer
	// minor units everywhere.
	// What the platform owes right now, one row per teacher: the sum of the ledger
	// rows past their clearing deadline and not yet paid out, biggest first.
	AdminListOwedPayouts(ctx context.Context) ([]AdminListOwedPayoutsRow, error)
	// One line per teacher paid by a batch, biggest first.
	AdminListPayoutBatchLines(ctx context.Context, payoutBatchID uuid.NullUUID) ([]AdminListPayoutBatchLinesRow, error)
	// Past payout runs, newest first.
	AdminListPayoutBatches(ctx context.Context, arg AdminListPayoutBatchesParams) ([]AdminListPayoutBatchesRow, error)
	// --- Admin: review moderation (phase F) ---
	// A page of reviews for the moderation queue, newest first. Filters are all
	// optional: visibility ('visible' | 'hidden'; NULL = both), a teacher slug, and
	// a rating ceiling (to surface the low-star reviews an operator is looking for).
	AdminListReviews(ctx context.Context, arg AdminListReviewsParams) ([]AdminListReviewsRow, error)
	AdminListTeachers(ctx context.Context, arg AdminListTeachersParams) ([]AdminListTeachersRow, error)
	// The 50 newest bookings the user takes part in, as student or as teacher-owner.
	AdminListUserBookings(ctx context.Context, studentID uuid.UUID) ([]AdminListUserBookingsRow, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	AdminOpenDisputeCount(ctx context.Context) (int64, error)
	// Money the platform actually moved: captured = collected from students,
	// refunded = returned to them.
	AdminPaymentStats(ctx context.Context) (AdminPaymentStatsRow, error)
	// owed_minor = earned by teachers but not yet disbursed (held or cleared);
	// paid_minor = disbursed by past payout runs. Reversed rows count towards none.
	AdminPayoutStats(ctx context.Context) (AdminPayoutStatsRow, error)
	// Platform-wide ledger totals: payable now, still inside the clearing window,
	// and already disbursed. Reversed rows count towards none of them.
	AdminPayoutTotals(ctx context.Context) (AdminPayoutTotalsRow, error)
	// Visible reviews only (hidden ones are off the platform). average_rating is
	// rounded to one decimal, 0 when there are none.
	AdminReviewStats(ctx context.Context) (AdminReviewStatsRow, error)
	AdminSetTeacherStatus(ctx context.Context, arg AdminSetTeacherStatusParams) error
	AdminSetTeacherVerified(ctx context.Context, arg AdminSetTeacherVerifiedParams) error
	AdminTeacherStats(ctx context.Context) (AdminTeacherStatsRow, error)
	// Who earned the platform the most over the window: booked money that reached
	// confirmed or completed, by the day the booking was made.
	AdminTopTeachers(ctx context.Context, arg AdminTopTeachersParams) ([]AdminTopTeachersRow, error)
	// The user's payments as the paying student, bucketed by current payment state.
	AdminUserPaymentsSummary(ctx context.Context, studentID uuid.UUID) (AdminUserPaymentsSummaryRow, error)
	AdminUserRoles(ctx context.Context, userID uuid.UUID) ([]AdminUserRolesRow, error)
	// Admin module (phase A/B): read-across-tables queries for the ops dashboard and
	// the moderation write path. This is an internal tool behind auth.RequireAdmin,
	// so it reads other modules' tables directly rather than routing through their
	// services.
	// The dashboard counters (GET /v1/admin/metrics) are six small aggregate reads,
	// one per area. Each is cheap (a single sequential scan of one table); the
	// dashboard is a rare, operator-only call.
	AdminUserStats(ctx context.Context) (AdminUserStatsRow, error)
	// Slug -> id, but only for a publicly visible (approved) teacher. GET
	// /v1/teachers/{slug}/reviews 404s for a non-approved slug, same as the profile.
	ApprovedTeacherIDBySlug(ctx context.Context, slug string) (uuid.UUID, error)
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	// Lesson resources (phase A2/A3): attaching a resource to a booking, and the
	// student's submissions against it.
	// position is the current attachment count for the booking, computed here so
	// the insert stays a single statement. A duplicate (booking_id, resource_id)
	// raises SQLSTATE 23505 on the table's UNIQUE constraint, mapped by the
	// repository to ErrAlreadyAttached — race-safe, never a check-then-insert.
	AttachBookingResource(ctx context.Context, arg AttachBookingResourceParams) (AttachBookingResourceRow, error)
	// cancelled_by records WHO cancelled: 'student', 'teacher' (includes a teacher
	// no-show) or 'admin' (the operator force-cancel override); cancellation_outcome
	// what happened to the money (refunded / forfeited / unpaid, see migration
	// 000027). The service picks both values; the columns' CHECK constraints are
	// the guard.
	CancelBooking(ctx context.Context, arg CancelBookingParams) error
	// Catalog: published, non-archived, non-suspended courses only, from an
	// approved teacher (mirrors GetBookingTeacherContext's status = 'approved'
	// gate — a suspended teacher's courses shouldn't surface in the public
	// marketplace even if the course row itself is still 'published'). Phase C3
	// adds suspended_at IS NULL: an operator takedown must 404 the storefront the
	// same way an unpublished/archived course already does.
	// sort: 'price_asc' | 'price_desc' | 'rating' | anything else (including "" /
	// 'newest') falls back to newest-first. Each CASE column is NULL for every
	// row unless its own sort is selected, so they never affect ordering
	// otherwise and the final created_at/id tiebreak always applies.
	//
	// 'rating' sorts by the derived aggregate, with review_count as the
	// tiebreaker so a lone 5★ review doesn't outrank a course with fifty of
	// them — the usual "one rave review isn't a track record" correction.
	CatalogListCourses(ctx context.Context, arg CatalogListCoursesParams) ([]CatalogListCoursesRow, error)
	// Marks an item complete unconditionally (a course-embedded resource's
	// submission reaching submitted/graded, via resources.CourseProgress). Never
	// regresses video_position_seconds or an already-recorded completed_at.
	CompleteItemProgress(ctx context.Context, arg CompleteItemProgressParams) (CourseItemProgress, error)
	// System transition (no participant check): pending_payment -> confirmed on a
	// successful authorization webhook. Guarded so a replay cannot resurrect a
	// cancelled booking.
	ConfirmBookingForPayment(ctx context.Context, id uuid.UUID) error
	// Spend a token by its hash (the redeem flows already hold the hash, not the id).
	ConsumeAuthToken(ctx context.Context, tokenSha256 []byte) error
	// Invalidate a user's outstanding tokens of a purpose before issuing a new one,
	// so only the newest link works.
	ConsumeUserAuthTokens(ctx context.Context, arg ConsumeUserAuthTokensParams) error
	CountCatalogCourses(ctx context.Context, arg CountCatalogCoursesParams) (int64, error)
	CountCourseReviews(ctx context.Context, courseID uuid.UUID) (int64, error)
	CountTeacherCourses(ctx context.Context, arg CountTeacherCoursesParams) (int64, error)
	CountTeacherResources(ctx context.Context, arg CountTeacherResourcesParams) (int64, error)
	CountTeacherReviews(ctx context.Context, teacherID uuid.UUID) (int64, error)
	CountTeacherSubmissionInbox(ctx context.Context, arg CountTeacherSubmissionInboxParams) (int64, error)
	CountTeachers(ctx context.Context, arg CountTeachersParams) (int64, error)
	CountUsersWithRole(ctx context.Context, roleID uuid.UUID) (int64, error)
	// The "5★ ▓▓▓ 12" histogram under a course's rating. Visible rows only, and
	// only the star values that actually occur — the caller fills 1..5 with zeros.
	CourseRatingBreakdown(ctx context.Context, courseID uuid.UUID) ([]CourseRatingBreakdownRow, error)
	// --- account-recovery link tokens (migration 000013) ---
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (uuid.UUID, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (uuid.UUID, error)
	// Course authoring (phase C1): a teacher's courses, and the curriculum tree
	// (sections -> items) each one owns.
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	// Phase C2: course-purchase payments. A sibling of payments.sql's booking
	// flow — same status lifecycle and webhook-idempotency shape, keyed to
	// (course_id, student_id) instead of booking_id. No payout-ledger write here;
	// revenue-share for course sales is a future phase.
	// Idempotent: a second call for the same (course_id, student_id) is a no-op
	// and still returns the existing row (mirrors CreatePayment's ON CONFLICT
	// DO UPDATE no-op trick).
	CreateCoursePayment(ctx context.Context, arg CreateCoursePaymentParams) (CoursePayment, error)
	// File assets (phase A1): the app's handle to a blob in the store.
	CreateFileAsset(ctx context.Context, arg CreateFileAssetParams) (FileAsset, error)
	CreateLessonType(ctx context.Context, arg CreateLessonTypeParams) (LessonType, error)
	// Payments module: one payment intent per booking, the webhook-event log that
	// guards idempotency, and the simplified teacher-earnings ledger. Money is
	// integer minor units everywhere.
	// Eagerly created right after a booking is inserted. Idempotent: a second call
	// for the same booking is a no-op and still returns the existing row.
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Learning resources library (phase A1).
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Both the demo seed and POST /v1/teachers insert through here. The seed passes
	// status = 'approved'; the API create path passes 'pending' so a new profile is
	// not public until an admin approves it. verified defaults to false.
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (uuid.UUID, error)
	// Auth module: user accounts and refresh-token sessions.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Seed-only. booking_resources.booking_id cascades; resource_id has no
	// cascade, so the seed clears attachments before resources.
	DeleteAllBookingResources(ctx context.Context) error
	// Seed-only. bookings.teacher_id / student_id reference teachers / users with
	// no ON DELETE CASCADE, so the seed must clear bookings before those tables.
	DeleteAllBookings(ctx context.Context) error
	DeleteAllCourseEnrollments(ctx context.Context) error
	// Seed-only. FK order (deepest first): course_item_progress -> course_items/
	// course_enrollments; submissions.enrollment_id -> course_enrollments (cleared
	// by resources.DeleteAllSubmissions, called by cmd/seed before
	// DeleteAllCourseEnrollments); course_enrollments -> courses/users;
	// course_items -> course_sections; course_sections -> courses; courses ->
	// teachers. cmd/seed clears all of these before DeleteAllTeachers/
	// DeleteAllUsers, same "explicit, deepest-first" discipline as its existing
	// booking/payment clearing.
	DeleteAllCourseItemProgress(ctx context.Context) error
	DeleteAllCourseItems(ctx context.Context) error
	// Seed-only. course_payment_events -> course_payments -> courses/users; clear
	// events before payments, and both before courses.DeleteAllCourses.
	DeleteAllCoursePaymentEvents(ctx context.Context) error
	DeleteAllCoursePayments(ctx context.Context) error
	DeleteAllCourseReviews(ctx context.Context) error
	DeleteAllCourseSections(ctx context.Context) error
	DeleteAllCourses(ctx context.Context) error
	// Seed-only. disputes.booking_id cascades, but raised_by / resolved_by
	// reference users with no cascade, so the seed clears disputes explicitly
	// before bookings and users.
	DeleteAllDisputes(ctx context.Context) error
	// Seed-only. file_assets.owner_id -> users cascades, but resources may still
	// reference an asset id in JSONB (no FK), so the seed clears this before users.
	DeleteAllFileAssets(ctx context.Context) error
	// Seed-only (no ON DELETE CASCADE in this schema — see cmd/seed).
	DeleteAllLessonTypePrices(ctx context.Context) error
	DeleteAllLessonTypes(ctx context.Context) error
	DeleteAllPaymentEvents(ctx context.Context) error
	// Seed-only. payments.booking_id references bookings with no ON DELETE CASCADE,
	// so the seed must clear payment rows (and the event log / ledger that
	// reference them) before bookings.
	DeleteAllPayments(ctx context.Context) error
	// Seed-only. payout_ledger.payout_batch_id references payout_batches with no
	// ON DELETE CASCADE, so the seed clears the ledger first, and payout_batches
	// before users (created_by).
	DeleteAllPayoutBatches(ctx context.Context) error
	DeleteAllPayoutLedger(ctx context.Context) error
	// Seed-only. resources.teacher_id -> teachers cascades; kept explicit + ordered.
	DeleteAllResources(ctx context.Context) error
	// Seed-only. reviews references teachers / users / bookings with no cascade, so
	// the seed clears it before all three.
	DeleteAllReviews(ctx context.Context) error
	DeleteAllRolePermissions(ctx context.Context) error
	DeleteAllRoles(ctx context.Context) error
	// Seed-only. submissions.booking_id cascades, but resource_id / student_id
	// reference resources / users with no cascade, so the seed clears submissions
	// before those tables.
	DeleteAllSubmissions(ctx context.Context) error
	DeleteAllTeachers(ctx context.Context) error
	// Seed-only. Clear assignments before roles / users.
	DeleteAllUserRoles(ctx context.Context) error
	// Seed-only. teachers.user_id references users, so callers must clear teachers
	// first.
	DeleteAllUsers(ctx context.Context) error
	DeleteAvailabilitySlots(ctx context.Context, teacherID uuid.UUID) error
	DeleteCourse(ctx context.Context, id uuid.UUID) error
	DeleteCourseItem(ctx context.Context, id uuid.UUID) error
	DeleteCourseSection(ctx context.Context, id uuid.UUID) error
	DeleteLessonTypePrices(ctx context.Context, lessonTypeID uuid.UUID) error
	DeleteResource(ctx context.Context, id uuid.UUID) error
	DeleteReview(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error
	DeleteTeacherExperience(ctx context.Context, teacherID uuid.UUID) error
	DeleteTeacherFocus(ctx context.Context, teacherID uuid.UUID) error
	DeleteTeacherLanguages(ctx context.Context, teacherID uuid.UUID) error
	DetachBookingResource(ctx context.Context, arg DetachBookingResourceParams) (int64, error)
	// Does this enrollment's course actually embed resourceID as a curriculum
	// item? The course-context equivalent of GetBookingResourceByPair's "is this
	// actually attached" check.
	EnrollmentGrantsResource(ctx context.Context, arg EnrollmentGrantsResourceParams) (bool, error)
	// Widens files.Download beyond owner-only: true iff some resource whose
	// content carries this file_asset_id / audio_asset_id is attached to a
	// booking belonging to this student.
	FileAssetAccessibleToStudent(ctx context.Context, arg FileAssetAccessibleToStudentParams) (bool, error)
	// Whose token is this? Ignores consumed / expired — used to recognise a
	// just-redeemed verification token on a double-submit.
	GetAuthTokenUser(ctx context.Context, arg GetAuthTokenUserParams) (uuid.UUID, error)
	GetBookingByID(ctx context.Context, id uuid.UUID) (GetBookingByIDRow, error)
	// Is this resource attached to this booking, and as what kind? Backs the
	// "homework assigned on this booking" check before a submission may start.
	GetBookingResourceByPair(ctx context.Context, arg GetBookingResourceByPairParams) (GetBookingResourceByPairRow, error)
	// Booking module: concrete scheduled lessons. Times are UTC timestamptz. The
	// recurring weekly availability is read via the availability queries; here we
	// only need the teacher context, existing bookings for overlap checks, and the
	// booking rows themselves (joined to a light teacher + student summary so the
	// frontend lists avoid N+1 calls).
	// Slug -> everything the booking flow needs: identity, timezone, pricing, and
	// the owning account (drives the "can't book yourself" check).
	// Only an approved (publicly visible) teacher can be booked. A non-approved slug
	// returns no rows here, so the booking flow treats it as "no such teacher": 404
	// on GET /v1/teachers/{slug}/slots and 404 teacher_not_found on POST /v1/bookings.
	GetBookingTeacherContext(ctx context.Context, slug string) (GetBookingTeacherContextRow, error)
	GetCourse(ctx context.Context, id uuid.UUID) (Course, error)
	GetCourseItem(ctx context.Context, id uuid.UUID) (CourseItem, error)
	// Resolves the curriculum item a course-context submission's resource
	// corresponds to, scoped to the enrollment's own course. Backs
	// resources.CourseProgress.ItemCompleted.
	GetCourseItemForEnrollmentResource(ctx context.Context, arg GetCourseItemForEnrollmentResourceParams) (CourseItem, error)
	GetCoursePaymentByCourseAndStudent(ctx context.Context, arg GetCoursePaymentByCourseAndStudentParams) (CoursePayment, error)
	GetCoursePaymentByID(ctx context.Context, id uuid.UUID) (CoursePayment, error)
	GetCourseReviewByEnrollment(ctx context.Context, enrollmentID uuid.UUID) (CourseReview, error)
	GetCourseReviewByID(ctx context.Context, id uuid.UUID) (CourseReview, error)
	GetCourseSection(ctx context.Context, id uuid.UUID) (CourseSection, error)
	// Disputes module (phase D): a participant contests a confirmed / completed
	// lesson, an operator with `disputes.resolve` closes it.
	//
	// Like the reviews module, this file reads the booking context it needs
	// directly (the participant + status check) rather than routing through the
	// bookings service — the Go packages stay decoupled, the SQL joins once.
	// Everything POST/GET /v1/bookings/{id}/disputes needs to authorize the caller:
	// the booking's student, the account owning the teacher profile, and the status
	// (only confirmed / completed lessons can be disputed).
	GetDisputeBookingContext(ctx context.Context, id uuid.UUID) (GetDisputeBookingContextRow, error)
	GetDisputeByID(ctx context.Context, id uuid.UUID) (GetDisputeByIDRow, error)
	GetEnrollmentByCourseAndStudent(ctx context.Context, arg GetEnrollmentByCourseAndStudentParams) (CourseEnrollment, error)
	GetEnrollmentByID(ctx context.Context, id uuid.UUID) (CourseEnrollment, error)
	// Resolves an enrollment's two participants for authorization: the course's
	// teacher's owning account, and the enrolled student.
	GetEnrollmentParticipants(ctx context.Context, id uuid.UUID) (GetEnrollmentParticipantsRow, error)
	GetFileAsset(ctx context.Context, id uuid.UUID) (FileAsset, error)
	GetLessonType(ctx context.Context, id uuid.UUID) (LessonType, error)
	// A token that can still be redeemed: matches the hash + purpose, not consumed,
	// not expired.
	GetLiveAuthToken(ctx context.Context, arg GetLiveAuthTokenParams) (GetLiveAuthTokenRow, error)
	// The booking's open dispute, if any. Backs the `open_dispute` /
	// `can_raise_dispute` fields the participant sees on a booking.
	GetOpenDisputeForBooking(ctx context.Context, bookingID uuid.UUID) (GetOpenDisputeForBookingRow, error)
	GetPaymentByBooking(ctx context.Context, bookingID uuid.UUID) (Payment, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	// Phase D1: free preview lessons.
	// Resolves a course item for the PUBLIC preview stream, returning everything
	// the access decision needs in one query so the handler can't accidentally
	// check a subset: the item's own preview flag and video asset, plus the
	// storefront gates (published, not archived, not suspended, approved teacher)
	// of the course it actually belongs to. The course_id predicate is what stops
	// a caller pairing a preview item id with an unrelated published course id.
	GetPreviewItem(ctx context.Context, arg GetPreviewItemParams) (GetPreviewItemRow, error)
	GetResource(ctx context.Context, id uuid.UUID) (Resource, error)
	// Reviews module (Phase 6): a student's rating + comment for a completed lesson.
	// A real review carries booking_id; the demo seed inserts booking-less samples.
	// Everything the POST /v1/bookings/{id}/review flow needs to authorize the
	// caller and build the review: the booking's student + status and the teacher
	// it is for, plus the display names embedded in the response.
	GetReviewBookingContext(ctx context.Context, id uuid.UUID) (GetReviewBookingContextRow, error)
	// The review for a booking (for embedding in a BookingDTO). No rows -> the
	// booking has not been reviewed.
	GetReviewByBooking(ctx context.Context, bookingID uuid.NullUUID) (GetReviewByBookingRow, error)
	GetRole(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (Session, error)
	// The trial a student already holds with a teacher, if any. Mirrors the
	// partial unique index bookings_one_trial_per_student_idx: cancelled trials
	// do not count, everything else does.
	GetStudentTrialBooking(ctx context.Context, arg GetStudentTrialBookingParams) (uuid.UUID, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	// Availability module: a teacher's weekly recurring slots (UTC minutes).
	// Resolve a slug to the teacher id, timezone, and owning user the availability
	// endpoints need (user_id drives the ownership check on PUT).
	GetTeacherAvailabilityContext(ctx context.Context, slug string) (GetTeacherAvailabilityContextRow, error)
	GetTeacherBySlug(ctx context.Context, slug string) (Teacher, error)
	// The teacher profile owned by an account (one per user), or no rows.
	GetTeacherIDByOwner(ctx context.Context, userID uuid.NullUUID) (uuid.UUID, error)
	// Phase C2: public catalog, purchase/enrollment, the student player, and
	// progress tracking.
	// The account that owns a teacher profile (the reverse of GetTeacherIDByOwner).
	// Used to resolve who to authorize as "the teacher" for a course (e.g. an
	// enrollment's grading authorization) without joining through users elsewhere.
	GetTeacherOwnerID(ctx context.Context, id uuid.UUID) (uuid.NullUUID, error)
	GetTeacherSummary(ctx context.Context, id uuid.UUID) (GetTeacherSummaryRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	// A plain contact lookup, used only for the grading-done email.
	GetUserContact(ctx context.Context, id uuid.UUID) (GetUserContactRow, error)
	// Only a `writing` submission reaches this (enforced in the service);
	// teacher_score is nullable — a teacher may grade with feedback only.
	GradeSubmission(ctx context.Context, arg GradeSubmissionParams) (Submission, error)
	// Phase C3: the course-purchase sibling of InsertLedgerHeld. One row per
	// captured course sale, keyed on course_enrollment_id instead of booking_id
	// (see payout_ledger's booking_id/course_enrollment_id CHECK, migration
	// 000018). teacher_id is derived by joining the enrollment to its course;
	// amount_minor is the teacher's already-computed revenue-share (Go arithmetic
	// in payments.CourseService.CreditCourseSale, never derived here), and
	// available_at opens the same clearing window as a lesson's earning: capture
	// time + PAYOUTS_CLEARING_DAYS.
	//
	// Called by courses.Service.Purchase (via the courses.PaymentGateway port)
	// right after the enrollment row is created, NOT from this package's own
	// ApplyCourseEvent webhook handler on payment.captured — unlike a booking
	// (which exists before its payment), a course_enrollment does not exist yet
	// at capture time, so there is no enrollment id to attach a ledger row to
	// until courses.Service creates one. See CreditCourseSale's doc comment.
	//
	// ON CONFLICT (course_enrollment_id) DO NOTHING is the idempotency guard: a
	// retried/duplicate call for the same enrollment (e.g. a concurrent
	// double-submit racing EnsureEnrollment) never double-credits the teacher.
	InsertCourseLedgerHeld(ctx context.Context, arg InsertCourseLedgerHeldParams) error
	InsertCoursePaymentEvent(ctx context.Context, arg InsertCoursePaymentEventParams) error
	// Course reviews (phase D2): a buyer's rating + comment for a course they are
	// enrolled in, plus the derived display aggregate on courses.rating /
	// review_count. See migration 000024 for the design notes.
	// A duplicate (enrollment_id) raises SQLSTATE 23505 on the table's UNIQUE
	// constraint, which the repository maps to ErrAlreadyReviewed — race-safe,
	// never a check-then-insert.
	InsertCourseReview(ctx context.Context, arg InsertCourseReviewParams) (CourseReview, error)
	// A second OPEN dispute for the same booking raises SQLSTATE 23505 on
	// disputes_one_open_per_booking, which the repository maps to ErrDisputeExists
	// (race-safe, never a check-then-insert).
	InsertDispute(ctx context.Context, arg InsertDisputeParams) (Dispute, error)
	// Enrollment.
	// Insert-first idempotency: a duplicate (course_id, student_id) raises
	// SQLSTATE 23505 on the table's UNIQUE constraint, mapped by the repository
	// to load-and-return the existing row instead — never check-then-insert.
	InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (CourseEnrollment, error)
	// One row per captured booking. teacher_id is copied from the booking, and
	// available_at opens the clearing window: capture time + PAYOUTS_CLEARING_DAYS.
	// The row stays 'held' until a payout run settles it (phase E) — nothing flips
	// it to 'available'; that state is derived from available_at at read time.
	InsertLedgerHeld(ctx context.Context, arg InsertLedgerHeldParams) error
	// Replace is delete-then-insert; a price list is at most five rows, so the
	// repository loops rather than carrying a two-array unnest.
	InsertLessonTypePrice(ctx context.Context, arg InsertLessonTypePriceParams) error
	// The idempotency gate. A duplicate event_id raises SQLSTATE 23505, which the
	// repository treats as "already processed".
	InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) error
	// The fake provider settles in-process, so a batch is written already
	// 'completed' in the same transaction that marks its rows paid. A real
	// disbursement API would insert 'processing' here and flip it afterwards.
	InsertPayoutBatch(ctx context.Context, arg InsertPayoutBatchParams) (InsertPayoutBatchRow, error)
	// A real, booking-tied review. A duplicate for the same booking_id raises
	// SQLSTATE 23505 on reviews_booking_uniq, which the repository maps to
	// ErrAlreadyReviewed (race-safe, never a check-then-insert).
	InsertReview(ctx context.Context, arg InsertReviewParams) (InsertReviewRow, error)
	// Phase A2: can this resource be deleted? True once it has ever been attached
	// to a booking (detaching does not clear this — attach it once, and it is
	// "in use" for delete purposes forever; archive instead).
	IsResourceAssigned(ctx context.Context, resourceID uuid.UUID) (bool, error)
	// Count of teachers per taught language across the whole catalog. Drives the
	// language filter in the UI, so it is intentionally unfiltered.
	LanguageFacets(ctx context.Context) ([]LanguageFacetsRow, error)
	// The most recent still-live token of a purpose for a user — drives the "one was
	// just sent, don't send another" cooldown. No row -> zero time.
	LatestAuthTokenAt(ctx context.Context, arg LatestAuthTokenAtParams) (pgtype.Timestamptz, error)
	// Durations a live offering can be booked for, cheapest first.
	LessonTypeDurations(ctx context.Context, lessonTypeID uuid.UUID) ([]LessonTypeDurationsRow, error)
	// What the booking service needs to price one lesson: the offering, its owner
	// and the price for the requested duration. No row means the duration is not
	// offered (or the type is archived / belongs to another teacher).
	LessonTypeOffering(ctx context.Context, arg LessonTypeOfferingParams) (LessonTypeOfferingRow, error)
	ListAvailabilitySlots(ctx context.Context, teacherID uuid.UUID) ([]ListAvailabilitySlotsRow, error)
	// A booking's attachments, teacher-ordered, each with its resource's display
	// fields joined in (title/type/status/content) so the caller never N+1s.
	ListBookingResources(ctx context.Context, bookingID uuid.UUID) ([]ListBookingResourcesRow, error)
	// Bookings the caller participates in. Pass the caller's user id as
	// student_filter and/or the caller-owned teacher id as teacher_filter; use the
	// all-zero uuid for a dimension that should not match. Newest lesson first.
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error)
	ListCourseItems(ctx context.Context, sectionID uuid.UUID) ([]CourseItem, error)
	// Every item across a course's sections, in curriculum order (section
	// position, then item position) — one query for the whole tree instead of
	// N+1 per-section queries; the service groups rows by section_id in Go.
	ListCourseItemsByCourse(ctx context.Context, courseID uuid.UUID) ([]CourseItem, error)
	// One course's public review list: visible rows only, newest first.
	ListCourseReviews(ctx context.Context, arg ListCourseReviewsParams) ([]ListCourseReviewsRow, error)
	ListCourseSections(ctx context.Context, courseID uuid.UUID) ([]CourseSection, error)
	// The whole dispute thread for one booking, newest first.
	ListDisputesForBooking(ctx context.Context, bookingID uuid.UUID) ([]ListDisputesForBookingRow, error)
	// "My learning": the student's enrollments, newest first, each with its
	// course summary and a progress percent computed from two correlated
	// subqueries (total curriculum items for the course; completed rows for this
	// specific enrollment) — cheap since a course has at most a few dozen items.
	ListEnrollmentsForStudent(ctx context.Context, studentID uuid.UUID) ([]ListEnrollmentsForStudentRow, error)
	ListExperienceForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]ListExperienceForTeachersRow, error)
	ListFocusForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]TeacherFocu, error)
	ListItemProgressForEnrollment(ctx context.Context, enrollmentID uuid.UUID) ([]CourseItemProgress, error)
	ListLanguagesForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]TeacherLanguage, error)
	ListLessonTypePrices(ctx context.Context, lessonTypeIds []uuid.UUID) ([]LessonTypePrice, error)
	// Lesson types: a teacher's 1-on-1 offerings and their per-duration prices.
	// Prices are read as a separate pass (by type id) rather than joined, so a
	// type with no prices yet still comes back and the caller assembles the tree.
	// The teacher's live offerings, trial first, then by position.
	ListLessonTypes(ctx context.Context, arg ListLessonTypesParams) ([]LessonType, error)
	ListPermissionsForRoles(ctx context.Context, roleIds []uuid.UUID) ([]RolePermission, error)
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	// Every submission filed against one booking's homeworks. A booking has
	// exactly one student, so this never needs a student filter of its own.
	ListSubmissionsForBooking(ctx context.Context, bookingID uuid.NullUUID) ([]Submission, error)
	// Non-cancelled bookings for a teacher that overlap the [from, to) window, for
	// server-side slot generation and the pre-insert bookability re-check.
	ListTeacherBookingIntervals(ctx context.Context, arg ListTeacherBookingIntervalsParams) ([]ListTeacherBookingIntervalsRow, error)
	// The authoring library list. Filters are optional: status ('draft'|'published')
	// and whether to include archived rows.
	ListTeacherCourses(ctx context.Context, arg ListTeacherCoursesParams) ([]Course, error)
	// Phase C3 widens this to a teacher's course-sale earnings alongside their
	// lesson earnings: LEFT JOIN both sources (a row's booking_id XOR
	// course_enrollment_id is set, per the ledger's own CHECK) and coalesce the
	// "when" and "counterparty name" columns so a client sees one uniform shape.
	// course_title is NULL for a lesson row, non-NULL for a course row — the
	// discriminator a client uses to render each line differently.
	ListTeacherEarnings(ctx context.Context, teacherID uuid.UUID) ([]ListTeacherEarningsRow, error)
	// The library list. Filters are optional: type, status ('draft'|'published'),
	// and whether to include archived rows.
	ListTeacherResources(ctx context.Context, arg ListTeacherResourcesParams) ([]Resource, error)
	// A page of a teacher's PUBLIC reviews, newest first. Hidden reviews (removed
	// from display by an operator) never appear on the profile.
	ListTeacherReviews(ctx context.Context, arg ListTeacherReviewsParams) ([]ListTeacherReviewsRow, error)
	// Public: the frontend's static-generation slug list. Non-approved teachers are
	// not public, so they are excluded here too.
	ListTeacherSlugs(ctx context.Context) ([]string, error)
	// Page of teachers matching the optional filters, ordered by the requested sort.
	// Child collections (languages, focus, experience) are loaded separately by the
	// repository using the returned ids.
	//
	// from_price_minor is derived, not stored: the price filter and the price sorts
	// run on it so that what a student filters by is what they can actually book.
	ListTeachers(ctx context.Context, arg ListTeachersParams) ([]ListTeachersRow, error)
	// The payout run's row selection, inside the run's transaction.
	//
	// FOR UPDATE SKIP LOCKED is the double-run guard: two operators running at the
	// same time get disjoint row sets — the second skips the rows the first has
	// locked rather than blocking on them or settling them a second time — and the
	// loser typically ends up with nothing to pay (409 nothing_to_pay).
	LockPayablePayoutLedger(ctx context.Context) ([]LockPayablePayoutLedgerRow, error)
	// The course sibling of MarkLedgerReversed. A refunded course_payment carries
	// no enrollment id of its own (the enrollment is created by courses.Service
	// only after a successful capture, see InsertCourseLedgerHeld's doc comment),
	// so the reversal is keyed by (course_id, student_id) instead — at most one
	// enrollment exists per (course, student) pair (course_enrollments' own
	// unique constraint), so this reverses exactly the one ledger row a refund on
	// that course payment could ever correspond to. Same "not already
	// paid/reversed" guard as MarkLedgerReversed.
	MarkCourseLedgerReversedByCourseAndStudent(ctx context.Context, arg MarkCourseLedgerReversedByCourseAndStudentParams) error
	MarkCoursePaymentAuthorized(ctx context.Context, arg MarkCoursePaymentAuthorizedParams) error
	MarkCoursePaymentCaptured(ctx context.Context, id uuid.UUID) error
	MarkCoursePaymentFailed(ctx context.Context, arg MarkCoursePaymentFailedParams) error
	MarkCoursePaymentRefunded(ctx context.Context, id uuid.UUID) error
	// A refund reverses the teacher's earning — unless a payout batch already paid
	// it out, which cannot be un-paid from here (the money has left the platform).
	MarkLedgerReversed(ctx context.Context, bookingID uuid.NullUUID) error
	// Settles exactly the rows the run locked. The state guard is belt-and-braces:
	// FOR UPDATE SKIP LOCKED already makes the set exclusive.
	MarkLedgerRowsPaid(ctx context.Context, arg MarkLedgerRowsPaidParams) error
	MarkPaymentAuthorized(ctx context.Context, arg MarkPaymentAuthorizedParams) error
	MarkPaymentCaptured(ctx context.Context, id uuid.UUID) error
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error
	MarkPaymentRefunded(ctx context.Context, id uuid.UUID) error
	// Idempotent: keeps the first verification time if the row is already verified.
	MarkUserEmailVerified(ctx context.Context, id uuid.UUID) error
	// RBAC module: roles, the permissions they grant, and role assignments. A
	// user's effective permissions are the union across their roles, resolved per
	// request (never from the JWT).
	// The caller's effective permission keys, deduped and sorted. One indexed join.
	PermissionsForUser(ctx context.Context, userID uuid.UUID) ([]string, error)
	// Rebuild courses.rating / review_count from the course's currently VISIBLE
	// reviews. Idempotent and order-independent — run it inside the same
	// transaction as any create / edit / hide / unhide / delete. A course with no
	// visible reviews reads as 0/0, which every surface renders as "no ratings
	// yet" rather than as a zero-star course.
	RecomputeCourseRating(ctx context.Context, courseID uuid.UUID) error
	// Rebuild a teacher's display aggregate (teachers.rating / review_count) from
	// the immutable historical baseline (rating_base / review_count_base) folded
	// with their currently VISIBLE, booking-tied reviews. Idempotent and
	// order-independent — run it after a review is created, hidden, unhidden, or
	// removed. Result clamped to [0, 5]; a teacher with no baseline and no visible
	// reviews reads as 0.
	RecomputeTeacherRating(ctx context.Context, teacherID uuid.UUID) error
	RenameCourseSection(ctx context.Context, arg RenameCourseSectionParams) (CourseSection, error)
	ReorderCourseItems(ctx context.Context, arg ReorderCourseItemsParams) (int64, error)
	// Rewrites positions 0..n-1 from the given ordered id array in one statement.
	// The service has already validated the array is exactly this course's
	// current section ids; the course_id filter is a defense-in-depth guard
	// against a section that raced its way into another course between the
	// service's check and this write (affected rows short of len(ids) surfaces
	// to the caller as a write failure, never a silent partial reorder).
	ReorderCourseSections(ctx context.Context, arg ReorderCourseSectionsParams) (int64, error)
	// Guarded UPDATE: only an OPEN dispute moves. No rows back means either "no such
	// dispute" or "already resolved" — the repository re-reads the row to tell the
	// two apart, so a lost race renders 409 already_resolved rather than clobbering
	// another operator's resolution.
	ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error)
	// Phase C2: which resource(s) reference this file_asset_id as their
	// material file or listening audio? Backs FileAssetAccessible's course-based
	// widening — the caller checks each returned resource id against
	// resources.EnrollmentReader.StudentResourceAccess, keeping the course-side
	// check behind that port rather than a raw join into course_items here.
	ResourceIDsForFileAsset(ctx context.Context, fileAssetID string) ([]uuid.UUID, error)
	// A rejected profile that was just edited goes back into the moderation
	// queue. The note stays so the moderator sees what they asked for last time.
	ResubmitTeacher(ctx context.Context, id uuid.UUID) error
	// Reuse-detection hammer: kills every still-active session for a user.
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	// Marks a session revoked and records the session that replaced it (rotation).
	// No-op if it was already revoked.
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RolesForUser(ctx context.Context, userID uuid.UUID) ([]RolesForUserRow, error)
	SaveSubmissionAnswers(ctx context.Context, arg SaveSubmissionAnswersParams) (Submission, error)
	// Seed-only: spread the demo accounts over the past weeks so the admin
	// dashboard's sign-ups series has a shape instead of one spike on seed day.
	SeedBackdateUser(ctx context.Context, arg SeedBackdateUserParams) error
	// Seed-only: a booking in an explicit lifecycle state (the API path always
	// starts at pending_payment). Used to give the admin / dispute demo data
	// something to point at on a fresh database.
	SeedInsertBooking(ctx context.Context, arg SeedInsertBookingParams) (uuid.UUID, error)
	// Seed-only: a settled payment for a booking the seed created directly in the
	// `completed` state, so the payout ledger row it carries has a matching intent.
	SeedInsertCapturedPayment(ctx context.Context, arg SeedInsertCapturedPaymentParams) error
	// Seed-only: an open dispute on a seeded booking so /v1/admin/disputes is not
	// empty on a fresh database.
	SeedInsertDispute(ctx context.Context, arg SeedInsertDisputeParams) error
	// Seed-only: a ledger row for a booking the seed created directly in the
	// `completed` state, with its clearing deadline placed in the past so the
	// payout dashboard is not empty on a fresh database. A non-null batch id also
	// marks the row paid.
	SeedInsertPayoutLedgerRow(ctx context.Context, arg SeedInsertPayoutLedgerRowParams) error
	// Seed-only: a booking-less sample review. Does NOT touch the teacher aggregate.
	SeedInsertReview(ctx context.Context, arg SeedInsertReviewParams) error
	// Seed-only: stamp every demo account verified so the nudge banner is quiet.
	SeedMarkEmailVerified(ctx context.Context) error
	// Seed-only: once the demo teachers are inserted with their hand-set
	// rating / review_count, stamp those as the immutable baseline the review
	// moderation recompute folds visible reviews onto (migration 000012 does the
	// same for an existing database — but on a fresh migrate the teachers table is
	// still empty, so the seed has to redo it here).
	SeedSnapshotRatingBaselines(ctx context.Context) error
	// Per-booking meeting link override. An empty string clears it (fall back to the
	// teacher's default meeting_url).
	SetBookingMeetingLinkOverride(ctx context.Context, arg SetBookingMeetingLinkOverrideParams) error
	// Records who missed the lesson. The status transition (completed on a student
	// no-show, cancelled on a teacher no-show) is applied separately via
	// SetBookingStatus / CancelBooking so the capture / refund path is reused.
	SetBookingNoShowParty(ctx context.Context, arg SetBookingNoShowPartyParams) error
	SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) error
	SetCourseArchived(ctx context.Context, arg SetCourseArchivedParams) (Course, error)
	SetCourseReviewHidden(ctx context.Context, arg SetCourseReviewHiddenParams) (CourseReview, error)
	// ever_published is a one-way latch: OR'd with "is this setting `published`",
	// so unpublishing (status back to draft) never clears it — Delete stays
	// blocked forever once a course has gone live at least once.
	SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (Course, error)
	// Idempotent: suspending an already-suspended course (or unsuspending an
	// already-active one) is a no-op that still returns the current row — COALESCE
	// keeps the original suspended_at instead of sliding it forward on a repeat
	// call, same "don't move a timestamp that's already set" idiom as
	// UpsertItemProgress's completed_at. Returns the course row only; the
	// repository loads the teacher summary separately with GetTeacherSummary
	// (same two-query shape avoids a CTE-scoped ambiguous-column parse sqlc
	// rejects when the same query both updates and re-joins the touched row).
	SetCourseSuspended(ctx context.Context, arg SetCourseSuspendedParams) (Course, error)
	SetLessonTypeArchived(ctx context.Context, arg SetLessonTypeArchivedParams) (LessonType, error)
	SetResourceArchived(ctx context.Context, arg SetResourceArchivedParams) (Resource, error)
	SetResourceStatus(ctx context.Context, arg SetResourceStatusParams) (Resource, error)
	SetReviewHidden(ctx context.Context, arg SetReviewHiddenParams) error
	// Password reset: replace the hash and bump updated_at. The caller also revokes
	// every session in the same transaction.
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// Phase C2's course-context sibling of StartOrGetSubmission: idempotent
	// "start" against submissions_course_uniq instead of submissions_lesson_uniq.
	// There is no separate "attach" step for courses — the resource IS the
	// curriculum item, checked by the service via EnrollmentGrantsResource.
	StartOrGetCourseSubmission(ctx context.Context, arg StartOrGetCourseSubmissionParams) (Submission, error)
	// Idempotent "start homework": a second call for the same
	// (resource_id, student_id, booking_id) returns the existing row rather than
	// erroring — the no-op ON CONFLICT DO UPDATE is required to get RETURNING on
	// a conflict (DO NOTHING skips it).
	StartOrGetSubmission(ctx context.Context, arg StartOrGetSubmissionParams) (Submission, error)
	// Does studentID have SOME active enrollment granting access to resourceID,
	// independent of which specific enrollment? Backs the course-based widening
	// of a course-embedded resource's material/audio file.
	StudentHasResourceAccess(ctx context.Context, arg StudentHasResourceAccessParams) (bool, error)
	// Backs files.AssigneeChecker's course-based widening: is fileAssetID a video
	// item's asset in some course the student is actively enrolled in?
	StudentHasVideoAccess(ctx context.Context, arg StudentHasVideoAccessParams) (bool, error)
	// Writes the outcome of POST /v1/submissions/{id}/submit. For an
	// auto-gradable type the caller passes status='graded' with the computed
	// auto_score/auto_max; for `writing` it passes status='submitted' with both
	// null.
	SubmitSubmission(ctx context.Context, arg SubmitSubmissionParams) (Submission, error)
	// The teacher profile owned by a user (one per user), or no rows.
	TeacherRefByOwner(ctx context.Context, userID uuid.NullUUID) (TeacherRefByOwnerRow, error)
	// Write queries: the demo seed plus the dashboard's create/update-profile flow.
	// Slug -> id + owning user, for the ownership check on PATCH /v1/teachers/{slug}.
	TeacherRefBySlug(ctx context.Context, slug string) (TeacherRefBySlugRow, error)
	TeacherSlugExists(ctx context.Context, slug string) (bool, error)
	// The grading inbox: a teacher's own resources' submissions (lesson or
	// course context alike — both join through resources.teacher_id), filtered
	// by status (default 'submitted' in the service), newest-submitted-first.
	TeacherSubmissionInbox(ctx context.Context, arg TeacherSubmissionInboxParams) ([]Submission, error)
	UnassignRoleFromUser(ctx context.Context, arg UnassignRoleFromUserParams) error
	// Full replace of the editable fields: title / subtitle / description / cover
	// / price. The service passes the current value for anything it isn't
	// changing, same convention as UpdateResource.
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	// Phase D1: the item edit now carries the preview flag and the video duration
	// alongside the title. Both are COALESCEd so a caller that omits them (the
	// plain rename path) leaves the stored values alone.
	UpdateCourseItem(ctx context.Context, arg UpdateCourseItemParams) (CourseItem, error)
	// The author edits their own standing opinion. Scoped by student_id so an
	// edit can never touch someone else's row even if the id leaked.
	UpdateCourseReview(ctx context.Context, arg UpdateCourseReviewParams) (CourseReview, error)
	UpdateLessonType(ctx context.Context, arg UpdateLessonTypeParams) (LessonType, error)
	// Partial edit: title / instructions / content are replaced wholesale when
	// provided (the service passes the current value for fields it isn't changing).
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateRoleDescription(ctx context.Context, arg UpdateRoleDescriptionParams) error
	// Edit the caller-editable profile fields. Server-controlled aggregates (rating,
	// review_count, lessons_completed, student_count, response_time_hours,
	// accepting_students) and the slug are intentionally left untouched.
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) error
	// Edit the caller's own account. Email is immutable here (changing it needs a
	// verification flow that does not exist yet). A NULL arg leaves that column
	// as it is.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	// Progress.
	// Merges the given fields into a video item's progress row for a student
	// driving the player (position updates as they watch; explicit
	// complete/uncomplete). NULL args (a field the client didn't send) leave the
	// stored value unchanged. completed=true stamps completed_at once (COALESCE
	// keeps the first time it was ever set); completed=false clears it.
	UpsertItemProgress(ctx context.Context, arg UpsertItemProgressParams) (CourseItemProgress, error)
	UserExists(ctx context.Context, id uuid.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
