// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission)
VALUES ($1, $2)
ON CONFLICT (role_id, permission) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID     uuid.UUID
	Permission string
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.Permission)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const countUsersWithRole = `-- name: CountUsersWithRole :one
SELECT count(*) FROM user_roles WHERE role_id = $1
`

func (q *Queries) CountUsersWithRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, is_system)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_system, created_at
`

type CreateRoleParams struct {
	Name        string
	Description string
	IsSystem    bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.IsSystem)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllRolePermissions = `-- name: DeleteAllRolePermissions :exec
DELETE FROM role_permissions
`

func (q *Queries) DeleteAllRolePermissions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllRolePermissions)
	return err
}

const deleteAllRoles = `-- name: DeleteAllRoles :exec
DELETE FROM roles
`

func (q *Queries) DeleteAllRoles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllRoles)
	return err
}

const deleteAllUserRoles = `-- name: DeleteAllUserRoles :exec
DELETE FROM user_roles
`

// Seed-only. Clear assignments before roles / users.
func (q *Queries) DeleteAllUserRoles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllUserRoles)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, name, description, is_system, created_at FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, created_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionsForRoles = `-- name: ListPermissionsForRoles :many
SELECT role_id, permission
FROM role_permissions
WHERE role_id = ANY($1::uuid[])
ORDER BY role_id, permission
`

func (q *Queries) ListPermissionsForRoles(ctx context.Context, roleIds []uuid.UUID) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRoles, roleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT
    r.id, r.name, r.description, r.is_system, r.created_at,
    (SELECT count(*) FROM user_roles ur WHERE ur.role_id = r.id)::bigint AS user_count
FROM roles r
ORDER BY r.is_system DESC, r.name
`

type ListRolesRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   pgtype.Timestamptz
	UserCount   int64
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permissionsForUser = `-- name: PermissionsForUser :many

SELECT DISTINCT rp.permission
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
WHERE ur.user_id = $1
ORDER BY rp.permission
`

// RBAC module: roles, the permissions they grant, and role assignments. A
// user's effective permissions are the union across their roles, resolved per
// request (never from the JWT).
// The caller's effective permission keys, deduped and sorted. One indexed join.
func (q *Queries) PermissionsForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, permissionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolesForUser = `-- name: RolesForUser :many
SELECT r.id, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

type RolesForUserRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RolesForUser(ctx context.Context, userID uuid.UUID) ([]RolesForUserRow, error) {
	rows, err := q.db.Query(ctx, rolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolesForUserRow{}
	for rows.Next() {
		var i RolesForUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignRoleFromUser = `-- name: UnassignRoleFromUser :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type UnassignRoleFromUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) UnassignRoleFromUser(ctx context.Context, arg UnassignRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, unassignRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const updateRoleDescription = `-- name: UpdateRoleDescription :exec
UPDATE roles SET description = $2 WHERE id = $1
`

type UpdateRoleDescriptionParams struct {
	ID          uuid.UUID
	Description string
}

func (q *Queries) UpdateRoleDescription(ctx context.Context, arg UpdateRoleDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateRoleDescription, arg.ID, arg.Description)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
