// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTeacherResources = `-- name: CountTeacherResources :one
SELECT count(*)
FROM resources
WHERE teacher_id = $1
  AND ($2::text   IS NULL OR type = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::bool OR archived_at IS NULL)
`

type CountTeacherResourcesParams struct {
	TeacherID       uuid.UUID
	Type            pgtype.Text
	Status          pgtype.Text
	IncludeArchived bool
}

func (q *Queries) CountTeacherResources(ctx context.Context, arg CountTeacherResourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeacherResources,
		arg.TeacherID,
		arg.Type,
		arg.Status,
		arg.IncludeArchived,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one

INSERT INTO resources (teacher_id, type, title, instructions, content, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, teacher_id, type, title, instructions, content, status, archived_at, created_at, updated_at
`

type CreateResourceParams struct {
	TeacherID    uuid.UUID
	Type         string
	Title        string
	Instructions string
	Content      []byte
	Status       string
}

// Learning resources library (phase A1).
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.TeacherID,
		arg.Type,
		arg.Title,
		arg.Instructions,
		arg.Content,
		arg.Status,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Type,
		&i.Title,
		&i.Instructions,
		&i.Content,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllResources = `-- name: DeleteAllResources :exec
DELETE FROM resources
`

// Seed-only. resources.teacher_id -> teachers cascades; kept explicit + ordered.
func (q *Queries) DeleteAllResources(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllResources)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, teacher_id, type, title, instructions, content, status, archived_at, created_at, updated_at
FROM resources
WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id uuid.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Type,
		&i.Title,
		&i.Instructions,
		&i.Content,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeacherResources = `-- name: ListTeacherResources :many
SELECT id, teacher_id, type, title, instructions, content, status, archived_at, created_at, updated_at
FROM resources
WHERE teacher_id = $1
  AND ($2::text   IS NULL OR type = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::bool OR archived_at IS NULL)
ORDER BY created_at DESC, id
LIMIT $6::int OFFSET $5::int
`

type ListTeacherResourcesParams struct {
	TeacherID       uuid.UUID
	Type            pgtype.Text
	Status          pgtype.Text
	IncludeArchived bool
	PageOffset      int32
	PageLimit       int32
}

// The library list. Filters are optional: type, status ('draft'|'published'),
// and whether to include archived rows.
func (q *Queries) ListTeacherResources(ctx context.Context, arg ListTeacherResourcesParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listTeacherResources,
		arg.TeacherID,
		arg.Type,
		arg.Status,
		arg.IncludeArchived,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Type,
			&i.Title,
			&i.Instructions,
			&i.Content,
			&i.Status,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResourceArchived = `-- name: SetResourceArchived :one
UPDATE resources
SET archived_at = CASE WHEN $1::bool THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $2
RETURNING id, teacher_id, type, title, instructions, content, status, archived_at, created_at, updated_at
`

type SetResourceArchivedParams struct {
	Archived bool
	ID       uuid.UUID
}

func (q *Queries) SetResourceArchived(ctx context.Context, arg SetResourceArchivedParams) (Resource, error) {
	row := q.db.QueryRow(ctx, setResourceArchived, arg.Archived, arg.ID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Type,
		&i.Title,
		&i.Instructions,
		&i.Content,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setResourceStatus = `-- name: SetResourceStatus :one
UPDATE resources
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, teacher_id, type, title, instructions, content, status, archived_at, created_at, updated_at
`

type SetResourceStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetResourceStatus(ctx context.Context, arg SetResourceStatusParams) (Resource, error) {
	row := q.db.QueryRow(ctx, setResourceStatus, arg.Status, arg.ID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Type,
		&i.Title,
		&i.Instructions,
		&i.Content,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET title = $2, instructions = $3, content = $4, updated_at = now()
WHERE id = $1
RETURNING id, teacher_id, type, title, instructions, content, status, archived_at, created_at, updated_at
`

type UpdateResourceParams struct {
	ID           uuid.UUID
	Title        string
	Instructions string
	Content      []byte
}

// Partial edit: title / instructions / content are replaced wholesale when
// provided (the service passes the current value for fields it isn't changing).
func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Title,
		arg.Instructions,
		arg.Content,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Type,
		&i.Title,
		&i.Instructions,
		&i.Content,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
