// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountReviews = `-- name: AdminCountReviews :one
SELECT count(*)
FROM reviews r
JOIN teachers t ON t.id = r.teacher_id
WHERE (
        $1::text IS NULL
        OR ($1::text = 'visible' AND NOT r.hidden)
        OR ($1::text = 'hidden'  AND r.hidden)
      )
  AND ($2::text IS NULL OR t.slug = $2::text)
  AND ($3::int IS NULL OR r.rating <= $3::int)
`

type AdminCountReviewsParams struct {
	Visibility  pgtype.Text
	TeacherSlug pgtype.Text
	MaxRating   pgtype.Int4
}

// Same filters as AdminListReviews — the total match count for pagination.
func (q *Queries) AdminCountReviews(ctx context.Context, arg AdminCountReviewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountReviews, arg.Visibility, arg.TeacherSlug, arg.MaxRating)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetReview = `-- name: AdminGetReview :one
SELECT r.id, r.teacher_id, r.rating, r.comment, r.created_at, r.hidden, r.booking_id,
       t.slug         AS teacher_slug,
       t.display_name AS teacher_display_name,
       u.display_name AS student_display_name
FROM reviews r
JOIN teachers t ON t.id = r.teacher_id
JOIN users    u ON u.id = r.student_id
WHERE r.id = $1
`

type AdminGetReviewRow struct {
	ID                 uuid.UUID
	TeacherID          uuid.UUID
	Rating             int16
	Comment            string
	CreatedAt          pgtype.Timestamptz
	Hidden             bool
	BookingID          uuid.NullUUID
	TeacherSlug        string
	TeacherDisplayName string
	StudentDisplayName string
}

func (q *Queries) AdminGetReview(ctx context.Context, id uuid.UUID) (AdminGetReviewRow, error) {
	row := q.db.QueryRow(ctx, adminGetReview, id)
	var i AdminGetReviewRow
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.Hidden,
		&i.BookingID,
		&i.TeacherSlug,
		&i.TeacherDisplayName,
		&i.StudentDisplayName,
	)
	return i, err
}

const adminListReviews = `-- name: AdminListReviews :many

SELECT r.id, r.rating, r.comment, r.created_at, r.hidden, r.booking_id,
       t.slug         AS teacher_slug,
       t.display_name AS teacher_display_name,
       u.display_name AS student_display_name
FROM reviews r
JOIN teachers t ON t.id = r.teacher_id
JOIN users    u ON u.id = r.student_id
WHERE (
        $1::text IS NULL
        OR ($1::text = 'visible' AND NOT r.hidden)
        OR ($1::text = 'hidden'  AND r.hidden)
      )
  AND ($2::text IS NULL OR t.slug = $2::text)
  AND ($3::int IS NULL OR r.rating <= $3::int)
ORDER BY r.created_at DESC, r.id DESC
LIMIT $5::int OFFSET $4::int
`

type AdminListReviewsParams struct {
	Visibility  pgtype.Text
	TeacherSlug pgtype.Text
	MaxRating   pgtype.Int4
	PageOffset  int32
	PageLimit   int32
}

type AdminListReviewsRow struct {
	ID                 uuid.UUID
	Rating             int16
	Comment            string
	CreatedAt          pgtype.Timestamptz
	Hidden             bool
	BookingID          uuid.NullUUID
	TeacherSlug        string
	TeacherDisplayName string
	StudentDisplayName string
}

// --- Admin: review moderation (phase F) ---
// A page of reviews for the moderation queue, newest first. Filters are all
// optional: visibility ('visible' | 'hidden'; NULL = both), a teacher slug, and
// a rating ceiling (to surface the low-star reviews an operator is looking for).
func (q *Queries) AdminListReviews(ctx context.Context, arg AdminListReviewsParams) ([]AdminListReviewsRow, error) {
	rows, err := q.db.Query(ctx, adminListReviews,
		arg.Visibility,
		arg.TeacherSlug,
		arg.MaxRating,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListReviewsRow{}
	for rows.Next() {
		var i AdminListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.Hidden,
			&i.BookingID,
			&i.TeacherSlug,
			&i.TeacherDisplayName,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const approvedTeacherIDBySlug = `-- name: ApprovedTeacherIDBySlug :one
SELECT id FROM teachers WHERE slug = $1 AND status = 'approved'
`

// Slug -> id, but only for a publicly visible (approved) teacher. GET
// /v1/teachers/{slug}/reviews 404s for a non-approved slug, same as the profile.
func (q *Queries) ApprovedTeacherIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, approvedTeacherIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countTeacherReviews = `-- name: CountTeacherReviews :one
SELECT count(*) FROM reviews WHERE teacher_id = $1 AND NOT hidden
`

func (q *Queries) CountTeacherReviews(ctx context.Context, teacherID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeacherReviews, teacherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllReviews = `-- name: DeleteAllReviews :exec
DELETE FROM reviews
`

// Seed-only. reviews references teachers / users / bookings with no cascade, so
// the seed clears it before all three.
func (q *Queries) DeleteAllReviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllReviews)
	return err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReviewBookingContext = `-- name: GetReviewBookingContext :one

SELECT b.id, b.status, b.teacher_id, b.student_id,
       t.slug            AS teacher_slug,
       u.display_name    AS student_display_name
FROM bookings b
JOIN teachers t ON t.id = b.teacher_id
JOIN users    u ON u.id = b.student_id
WHERE b.id = $1
`

type GetReviewBookingContextRow struct {
	ID                 uuid.UUID
	Status             string
	TeacherID          uuid.UUID
	StudentID          uuid.UUID
	TeacherSlug        string
	StudentDisplayName string
}

// Reviews module (Phase 6): a student's rating + comment for a completed lesson.
// A real review carries booking_id; the demo seed inserts booking-less samples.
// Everything the POST /v1/bookings/{id}/review flow needs to authorize the
// caller and build the review: the booking's student + status and the teacher
// it is for, plus the display names embedded in the response.
func (q *Queries) GetReviewBookingContext(ctx context.Context, id uuid.UUID) (GetReviewBookingContextRow, error) {
	row := q.db.QueryRow(ctx, getReviewBookingContext, id)
	var i GetReviewBookingContextRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TeacherID,
		&i.StudentID,
		&i.TeacherSlug,
		&i.StudentDisplayName,
	)
	return i, err
}

const getReviewByBooking = `-- name: GetReviewByBooking :one
SELECT r.id, r.teacher_id, r.student_id, r.booking_id, r.rating, r.comment, r.created_at,
       t.slug            AS teacher_slug,
       u.display_name    AS student_display_name
FROM reviews r
JOIN teachers t ON t.id = r.teacher_id
JOIN users    u ON u.id = r.student_id
WHERE r.booking_id = $1
`

type GetReviewByBookingRow struct {
	ID                 uuid.UUID
	TeacherID          uuid.UUID
	StudentID          uuid.UUID
	BookingID          uuid.NullUUID
	Rating             int16
	Comment            string
	CreatedAt          pgtype.Timestamptz
	TeacherSlug        string
	StudentDisplayName string
}

// The review for a booking (for embedding in a BookingDTO). No rows -> the
// booking has not been reviewed.
func (q *Queries) GetReviewByBooking(ctx context.Context, bookingID uuid.NullUUID) (GetReviewByBookingRow, error) {
	row := q.db.QueryRow(ctx, getReviewByBooking, bookingID)
	var i GetReviewByBookingRow
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.StudentID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.TeacherSlug,
		&i.StudentDisplayName,
	)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (teacher_id, student_id, booking_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, teacher_id, student_id, booking_id, rating, comment, created_at
`

type InsertReviewParams struct {
	TeacherID uuid.UUID
	StudentID uuid.UUID
	BookingID uuid.NullUUID
	Rating    int16
	Comment   string
}

type InsertReviewRow struct {
	ID        uuid.UUID
	TeacherID uuid.UUID
	StudentID uuid.UUID
	BookingID uuid.NullUUID
	Rating    int16
	Comment   string
	CreatedAt pgtype.Timestamptz
}

// A real, booking-tied review. A duplicate for the same booking_id raises
// SQLSTATE 23505 on reviews_booking_uniq, which the repository maps to
// ErrAlreadyReviewed (race-safe, never a check-then-insert).
func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (InsertReviewRow, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.TeacherID,
		arg.StudentID,
		arg.BookingID,
		arg.Rating,
		arg.Comment,
	)
	var i InsertReviewRow
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.StudentID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listTeacherReviews = `-- name: ListTeacherReviews :many
SELECT r.id, r.rating, r.comment, r.created_at,
       u.display_name AS student_display_name
FROM reviews r
JOIN users u ON u.id = r.student_id
WHERE r.teacher_id = $1 AND NOT r.hidden
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3::int OFFSET $2::int
`

type ListTeacherReviewsParams struct {
	TeacherID  uuid.UUID
	PageOffset int32
	PageLimit  int32
}

type ListTeacherReviewsRow struct {
	ID                 uuid.UUID
	Rating             int16
	Comment            string
	CreatedAt          pgtype.Timestamptz
	StudentDisplayName string
}

// A page of a teacher's PUBLIC reviews, newest first. Hidden reviews (removed
// from display by an operator) never appear on the profile.
func (q *Queries) ListTeacherReviews(ctx context.Context, arg ListTeacherReviewsParams) ([]ListTeacherReviewsRow, error) {
	rows, err := q.db.Query(ctx, listTeacherReviews, arg.TeacherID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherReviewsRow{}
	for rows.Next() {
		var i ListTeacherReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeTeacherRating = `-- name: RecomputeTeacherRating :exec
WITH v AS (
    SELECT COALESCE(sum(rating), 0)::numeric AS sum_r,
           count(*)                          AS n
    FROM reviews
    WHERE teacher_id = $1
      AND booking_id IS NOT NULL
      AND NOT hidden
)
UPDATE teachers t
SET review_count = t.review_count_base + v.n,
    rating = CASE
        WHEN t.review_count_base + v.n = 0 THEN 0
        ELSE LEAST(5, GREATEST(0, round(
            (t.rating_base::numeric * t.review_count_base + v.sum_r)
            / (t.review_count_base + v.n), 1)))::real
    END,
    updated_at = now()
FROM v
WHERE t.id = $1
`

// Rebuild a teacher's display aggregate (teachers.rating / review_count) from
// the immutable historical baseline (rating_base / review_count_base) folded
// with their currently VISIBLE, booking-tied reviews. Idempotent and
// order-independent — run it after a review is created, hidden, unhidden, or
// removed. Result clamped to [0, 5]; a teacher with no baseline and no visible
// reviews reads as 0.
func (q *Queries) RecomputeTeacherRating(ctx context.Context, teacherID uuid.UUID) error {
	_, err := q.db.Exec(ctx, recomputeTeacherRating, teacherID)
	return err
}

const seedInsertReview = `-- name: SeedInsertReview :exec
INSERT INTO reviews (teacher_id, student_id, booking_id, rating, comment, hidden)
VALUES ($1, $2, NULL, $3, $4, $5)
`

type SeedInsertReviewParams struct {
	TeacherID uuid.UUID
	StudentID uuid.UUID
	Rating    int16
	Comment   string
	Hidden    bool
}

// Seed-only: a booking-less sample review. Does NOT touch the teacher aggregate.
func (q *Queries) SeedInsertReview(ctx context.Context, arg SeedInsertReviewParams) error {
	_, err := q.db.Exec(ctx, seedInsertReview,
		arg.TeacherID,
		arg.StudentID,
		arg.Rating,
		arg.Comment,
		arg.Hidden,
	)
	return err
}

const setReviewHidden = `-- name: SetReviewHidden :exec
UPDATE reviews SET hidden = $1 WHERE id = $2
`

type SetReviewHiddenParams struct {
	Hidden bool
	ID     uuid.UUID
}

func (q *Queries) SetReviewHidden(ctx context.Context, arg SetReviewHiddenParams) error {
	_, err := q.db.Exec(ctx, setReviewHidden, arg.Hidden, arg.ID)
	return err
}
