// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teachers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTeachers = `-- name: CountTeachers :one
SELECT count(*)
FROM teachers t
WHERE
    ($1::teacher_kind IS NULL OR t.kind = $1::teacher_kind)
    AND ($2::bigint IS NULL OR t.price_per_hour_minor <= $2::bigint)
    AND (
        $3::text IS NULL
        OR EXISTS (
            SELECT 1 FROM teacher_languages tl
            WHERE tl.teacher_id = t.id AND tl.role = 'teaches' AND tl.code = $3::text
        )
    )
    AND (
        $4::text IS NULL
        OR t.display_name ILIKE '%' || $4 || '%'
        OR t.headline ILIKE '%' || $4 || '%'
        OR EXISTS (
            SELECT 1 FROM teacher_focus tf
            WHERE tf.teacher_id = t.id AND tf.tag ILIKE '%' || $4 || '%'
        )
    )
`

type CountTeachersParams struct {
	Kind          NullTeacherKind
	MaxPriceMinor pgtype.Int8
	Language      pgtype.Text
	Q             pgtype.Text
}

func (q *Queries) CountTeachers(ctx context.Context, arg CountTeachersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeachers,
		arg.Kind,
		arg.MaxPriceMinor,
		arg.Language,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeacherBySlug = `-- name: GetTeacherBySlug :one
SELECT id, slug, display_name, headline, kind, country_code, country_name, city, timezone, price_per_hour_minor, trial_price_minor, currency, rating, review_count, lessons_completed, student_count, response_time_hours, accepting_students, avatar_url, video_thumbnail_url, intro_video_url, about, teaching_style, created_at, updated_at FROM teachers WHERE slug = $1
`

func (q *Queries) GetTeacherBySlug(ctx context.Context, slug string) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacherBySlug, slug)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Headline,
		&i.Kind,
		&i.CountryCode,
		&i.CountryName,
		&i.City,
		&i.Timezone,
		&i.PricePerHourMinor,
		&i.TrialPriceMinor,
		&i.Currency,
		&i.Rating,
		&i.ReviewCount,
		&i.LessonsCompleted,
		&i.StudentCount,
		&i.ResponseTimeHours,
		&i.AcceptingStudents,
		&i.AvatarUrl,
		&i.VideoThumbnailUrl,
		&i.IntroVideoUrl,
		&i.About,
		&i.TeachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const languageFacets = `-- name: LanguageFacets :many
SELECT code, name, count(DISTINCT teacher_id)::bigint AS teacher_count
FROM teacher_languages
WHERE role = 'teaches'
GROUP BY code, name
ORDER BY name
`

type LanguageFacetsRow struct {
	Code         string
	Name         string
	TeacherCount int64
}

// Count of teachers per taught language across the whole catalog. Drives the
// language filter in the UI, so it is intentionally unfiltered.
func (q *Queries) LanguageFacets(ctx context.Context) ([]LanguageFacetsRow, error) {
	rows, err := q.db.Query(ctx, languageFacets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LanguageFacetsRow{}
	for rows.Next() {
		var i LanguageFacetsRow
		if err := rows.Scan(&i.Code, &i.Name, &i.TeacherCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExperienceForTeachers = `-- name: ListExperienceForTeachers :many
SELECT teacher_id, title, org, period, position
FROM teacher_experience
WHERE teacher_id = ANY($1::uuid[])
ORDER BY teacher_id, position
`

type ListExperienceForTeachersRow struct {
	TeacherID uuid.UUID
	Title     string
	Org       string
	Period    string
	Position  int32
}

func (q *Queries) ListExperienceForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]ListExperienceForTeachersRow, error) {
	rows, err := q.db.Query(ctx, listExperienceForTeachers, teacherIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExperienceForTeachersRow{}
	for rows.Next() {
		var i ListExperienceForTeachersRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.Title,
			&i.Org,
			&i.Period,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFocusForTeachers = `-- name: ListFocusForTeachers :many
SELECT teacher_id, tag, position
FROM teacher_focus
WHERE teacher_id = ANY($1::uuid[])
ORDER BY teacher_id, position, tag
`

func (q *Queries) ListFocusForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]TeacherFocu, error) {
	rows, err := q.db.Query(ctx, listFocusForTeachers, teacherIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherFocu{}
	for rows.Next() {
		var i TeacherFocu
		if err := rows.Scan(&i.TeacherID, &i.Tag, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLanguagesForTeachers = `-- name: ListLanguagesForTeachers :many
SELECT teacher_id, role, code, name, level, position
FROM teacher_languages
WHERE teacher_id = ANY($1::uuid[])
ORDER BY teacher_id, role, position, code
`

func (q *Queries) ListLanguagesForTeachers(ctx context.Context, teacherIds []uuid.UUID) ([]TeacherLanguage, error) {
	rows, err := q.db.Query(ctx, listLanguagesForTeachers, teacherIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeacherLanguage{}
	for rows.Next() {
		var i TeacherLanguage
		if err := rows.Scan(
			&i.TeacherID,
			&i.Role,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherSlugs = `-- name: ListTeacherSlugs :many
SELECT slug FROM teachers ORDER BY slug
`

func (q *Queries) ListTeacherSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTeacherSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT t.id, t.slug, t.display_name, t.headline, t.kind, t.country_code, t.country_name, t.city, t.timezone, t.price_per_hour_minor, t.trial_price_minor, t.currency, t.rating, t.review_count, t.lessons_completed, t.student_count, t.response_time_hours, t.accepting_students, t.avatar_url, t.video_thumbnail_url, t.intro_video_url, t.about, t.teaching_style, t.created_at, t.updated_at
FROM teachers t
WHERE
    ($1::teacher_kind IS NULL OR t.kind = $1::teacher_kind)
    AND ($2::bigint IS NULL OR t.price_per_hour_minor <= $2::bigint)
    AND (
        $3::text IS NULL
        OR EXISTS (
            SELECT 1 FROM teacher_languages tl
            WHERE tl.teacher_id = t.id AND tl.role = 'teaches' AND tl.code = $3::text
        )
    )
    AND (
        $4::text IS NULL
        OR t.display_name ILIKE '%' || $4 || '%'
        OR t.headline ILIKE '%' || $4 || '%'
        OR EXISTS (
            SELECT 1 FROM teacher_focus tf
            WHERE tf.teacher_id = t.id AND tf.tag ILIKE '%' || $4 || '%'
        )
    )
ORDER BY
    CASE WHEN $5::text = 'recommended' THEN t.accepting_students END DESC,
    CASE WHEN $5::text = 'recommended' THEN t.rating END DESC,
    CASE WHEN $5::text = 'rating_desc' THEN t.rating END DESC,
    CASE WHEN $5::text = 'price_asc' THEN t.price_per_hour_minor END ASC,
    CASE WHEN $5::text = 'price_desc' THEN t.price_per_hour_minor END DESC,
    t.review_count DESC,
    t.id
LIMIT $7::int
OFFSET $6::int
`

type ListTeachersParams struct {
	Kind          NullTeacherKind
	MaxPriceMinor pgtype.Int8
	Language      pgtype.Text
	Q             pgtype.Text
	Sort          string
	PageOffset    int32
	PageLimit     int32
}

// Page of teachers matching the optional filters, ordered by the requested sort.
// Child collections (languages, focus, experience) are loaded separately by the
// repository using the returned ids.
func (q *Queries) ListTeachers(ctx context.Context, arg ListTeachersParams) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listTeachers,
		arg.Kind,
		arg.MaxPriceMinor,
		arg.Language,
		arg.Q,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Headline,
			&i.Kind,
			&i.CountryCode,
			&i.CountryName,
			&i.City,
			&i.Timezone,
			&i.PricePerHourMinor,
			&i.TrialPriceMinor,
			&i.Currency,
			&i.Rating,
			&i.ReviewCount,
			&i.LessonsCompleted,
			&i.StudentCount,
			&i.ResponseTimeHours,
			&i.AcceptingStudents,
			&i.AvatarUrl,
			&i.VideoThumbnailUrl,
			&i.IntroVideoUrl,
			&i.About,
			&i.TeachingStyle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
