/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Reads the `ftr_session` cookie, issues a fresh access + refresh pair, revokes the presented refresh token, and sets the new cookie. A missing, expired, or already-revoked cookie returns 401 (and, on re-use of a revoked token, every session for that user is revoked).
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the current session and clears the `ftr_session` cookie. Idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search teachers */
        get: operations["listTeachers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teachers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one teacher profile */
        get: operations["getTeacherBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teachers/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a teacher's weekly availability
         * @description The teacher's recurring weekly slots, stored and returned in UTC. Combine `timezone` with each slot to show the grid in the teacher's local time; booking will do the same conversion server-side.
         */
        get: operations["getTeacherAvailability"];
        /**
         * Replace a teacher's weekly availability
         * @description Replaces the teacher's **entire** weekly set with the slots in the body (send `[]` to clear it).
         *     Requires a Bearer access token whose user owns the teacher profile (`teachers.user_id`); otherwise 401 (no/invalid token) or 403 (not the owner).
         *     Validation: `weekday` in 0–6; `0 <= start_minute < end_minute <= 1440`; both bounds a multiple of `granularity_minutes` (15); no two slots on the same weekday may overlap (touching slots are allowed).
         */
        put: operations["replaceTeacherAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description Stable, machine-readable identifier (e.g. `not_found`). */
                code: string;
                /** @description Human-readable explanation, safe to surface to users. */
                message: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description Minimum 8 characters. */
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
        };
        /** @description The access token (hold in memory, send as `Authorization: Bearer`) plus the user. The refresh token is NOT here — it is the `ftr_session` cookie. */
        AuthResponse: {
            /** @description HS256 JWT. */
            access_token: string;
            /** @description Access-token lifetime in seconds. */
            expires_in: number;
            user: components["schemas"]["AuthUser"];
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: {
                [key: string]: "ok" | "down";
            };
        };
        /** @enum {string} */
        Currency: "UZS" | "USD";
        Money: {
            /**
             * Format: int64
             * @description Amount in minor units (tiyin / cents). 9000000 UZS == 90,000 so'm.
             */
            amount_minor: number;
            currency: components["schemas"]["Currency"];
        };
        /**
         * @description `professional` — certified/qualified teacher, structured lessons. `community` — conversation practice, informal tutoring.
         * @enum {string}
         */
        TeacherKind: "professional" | "community";
        /**
         * @default recommended
         * @enum {string}
         */
        TeacherSort: "recommended" | "price_asc" | "price_desc" | "rating_desc";
        /** @enum {string} */
        LanguageLevel: "native" | "c2" | "c1" | "b2" | "b1" | "a2" | "a1";
        Language: {
            /** @description ISO 639-1 */
            code: string;
            name: string;
            level: components["schemas"]["LanguageLevel"];
        };
        Experience: {
            title: string;
            org: string;
            /** @description Free text, e.g. "2019 – present". */
            period: string;
        };
        /** @description Card view used in search results. */
        TeacherSummary: {
            /** Format: uuid */
            id: string;
            /** @description URL-safe, stable; used in /teachers/{slug}. */
            slug: string;
            display_name: string;
            /** @description One-line hook in the teacher's own words. */
            headline: string;
            kind: components["schemas"]["TeacherKind"];
            /** @description ISO 3166-1 alpha-2 */
            country_code: string;
            country_name: string;
            city: string;
            /** @description IANA name, e.g. "Asia/Tashkent". Source of truth for slot conversion. */
            timezone: string;
            teaches: components["schemas"]["Language"][];
            also_speaks: components["schemas"]["Language"][];
            price_per_hour: components["schemas"]["Money"];
            /**
             * Format: float
             * @description Aggregate rating to one decimal.
             */
            rating: number;
            review_count: number;
            lessons_completed: number;
            student_count: number;
            /** @description Free-text focus tags, e.g. "IELTS", "Kids & teens". */
            focus: string[];
            /** @description Median hours to reply to a booking request. */
            response_time_hours: number;
            accepting_students: boolean;
            /** Format: uri */
            avatar_url: string;
            /** Format: uri */
            video_thumbnail_url: string;
        };
        /** @description Full profile — every summary field plus the long-form content. */
        TeacherProfile: components["schemas"]["TeacherSummary"] & {
            /** Format: uri */
            intro_video_url: string;
            /** @description Long-form, plain text; paragraphs separated by "\n\n". */
            about: string;
            teaching_style: string;
            experience: components["schemas"]["Experience"][];
            /** @description Present only when the teacher offers a trial lesson. */
            trial_price?: components["schemas"]["Money"];
        };
        LanguageFacet: {
            code: string;
            name: string;
            /** @description Number of teachers in the catalog who teach this language. */
            count: number;
        };
        TeacherListResult: {
            teachers: components["schemas"]["TeacherSummary"][];
            /** @description Total matches across all pages. */
            total: number;
            facets: {
                languages: components["schemas"]["LanguageFacet"][];
            };
        };
        /** @description One recurring availability span on a single weekday, in UTC. Times are minutes from 00:00 UTC (like money's minor units — an integer, never a clock string). `end_minute` is exclusive. */
        AvailabilitySlot: {
            /** @description 0 = Sunday … 6 = Saturday (matches JS `Date.getDay()`). */
            weekday: number;
            /** @description Minutes from 00:00 UTC. Multiple of `granularity_minutes`. */
            start_minute: number;
            /** @description Exclusive end, minutes from 00:00 UTC. Greater than `start_minute`. */
            end_minute: number;
        };
        /** @description A teacher's full weekly recurring availability, in UTC. */
        WeeklyAvailability: {
            teacher_slug: string;
            /** @description The teacher's IANA timezone (e.g. "Asia/Tashkent"). Use it to render the UTC slots in local time. */
            timezone: string;
            /** @description The grid every slot boundary aligns to (currently 15). */
            granularity_minutes: number;
            /** @description Ordered by weekday, then start_minute. Non-overlapping. */
            slots: components["schemas"]["AvailabilitySlot"][];
        };
        /** @description The full weekly set to store. An empty array clears availability. */
        AvailabilityReplacement: {
            slots: components["schemas"]["AvailabilitySlot"][];
        };
    };
    responses: {
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication is missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller is not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and signed in. Body carries the access token; the `ftr_session` refresh cookie is set. */
            201: {
                headers: {
                    /** @description `ftr_session=<opaque>; HttpOnly; SameSite=Lax; Path=/v1/auth` */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description That email is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. Body carries the access token; the `ftr_session` refresh cookie is set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token in the body; new `ftr_session` cookie set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out (cookie cleared). Returned even if no session was active. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All backing services reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description One or more backing services are unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listTeachers: {
        parameters: {
            query?: {
                /** @description Filter to teachers who teach this language (ISO 639-1 code, e.g. `en`). */
                language?: string;
                kind?: components["schemas"]["TeacherKind"];
                /** @description Only teachers whose hourly price is at or below this amount (minor units). */
                max_price_minor?: number;
                /** @description Case-insensitive substring match across name, headline, and focus tags. */
                q?: string;
                sort?: components["schemas"]["TeacherSort"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matching teachers plus catalog-wide facets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherListResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getTeacherBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full teacher profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherProfile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTeacherAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The teacher's full weekly availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyAvailability"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceTeacherAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityReplacement"];
            };
        };
        responses: {
            /** @description The stored weekly availability after replacement. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyAvailability"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
