/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token
         * @description Reads the `ftr_session` cookie, issues a fresh access + refresh pair, revokes the presented refresh token, and sets the new cookie. A missing, expired, or already-revoked cookie returns 401 (and, on re-use of a revoked token, every session for that user is revoked).
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes the current session and clears the `ftr_session` cookie. Idempotent.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit the signed-in account
         * @description Updates the caller's own account. Only `display_name` is editable; changing the email is out of scope and any `email` key in the body is ignored. Omitting `display_name` is a no-op that returns the account unchanged.
         */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search teachers */
        get: operations["listTeachers"];
        put?: never;
        /**
         * Create the caller's teacher profile
         * @description Claims a teacher profile for the authenticated account. One profile per account — a second attempt is 409. The new profile's owner is the caller.
         *     The body carries only the editable fields; server-controlled aggregates (`rating`, `review_count`, `lessons_completed`, `student_count`, `response_time_hours`) start at 0, `accepting_students` starts true, and the `slug` is generated from `display_name` (de-duplicated with a numeric suffix). `languages` / `focus` / `experience` are stored as given.
         *
         *     On create, `display_name`, `headline`, `kind`, `country_code`, `country_name`, `city`, `timezone`, and `price_per_hour_minor` are required; a missing or blank one is a 400.
         */
        post: operations["createTeacherProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teachers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own teacher profile
         * @description Returns the teacher profile owned by the authenticated account, or 404 if they have not created one yet. The dashboard uses this to decide between the "create profile" and the edit flow, and to get the slug for the availability editor.
         */
        get: operations["getMyTeacherProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teachers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one teacher profile */
        get: operations["getTeacherBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit the caller's own teacher profile
         * @description Partial update of the profile at `slug`. Requires a Bearer token whose account owns the profile (`teachers.user_id`); otherwise 401 (no/invalid token) or 403 (not the owner — an unclaimed profile is never editable).
         *     Every field is optional; an omitted field is left unchanged. A present `languages` / `focus` / `experience` array (even `[]`) fully replaces that collection. The `slug` is immutable and server-controlled aggregates cannot be set here.
         */
        patch: operations["updateTeacherProfile"];
        trace?: never;
    };
    "/v1/teachers/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a teacher's weekly availability
         * @description The teacher's recurring weekly slots, stored and returned in UTC. Combine `timezone` with each slot to show the grid in the teacher's local time; booking will do the same conversion server-side.
         */
        get: operations["getTeacherAvailability"];
        /**
         * Replace a teacher's weekly availability
         * @description Replaces the teacher's **entire** weekly set with the slots in the body (send `[]` to clear it).
         *     Requires a Bearer access token whose user owns the teacher profile (`teachers.user_id`); otherwise 401 (no/invalid token) or 403 (not the owner).
         *     Validation: `weekday` in 0–6; `0 <= start_minute < end_minute <= 1440`; both bounds a multiple of `granularity_minutes` (15); no two slots on the same weekday may overlap (touching slots are allowed).
         */
        put: operations["replaceTeacherAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/teachers/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a teacher's concrete bookable start times
         * @description Projects the teacher's recurring weekly availability (`teacher_availability_slots`, stored as UTC minutes-from-midnight on a UTC weekday) onto real UTC datetimes across `[from, to]`, then removes any start that collides with an existing non-cancelled booking.
         *     Window rules: `from` defaults to now (and is clamped forward to now), `to` defaults to `from + 14 days`, and `to - from` may not exceed 21 days (400 otherwise). Slots are never generated in the past.
         *     A start time is included only if `[start, start + duration]` fits entirely inside one availability window. Windows the frontend split across 00:00 UTC are stitched back together first, so a lesson may legitimately straddle UTC midnight. Candidate starts step every 30 minutes from the start of each window.
         *     `price.amount_minor = round(price_per_hour_minor * duration / 60)` in integer minor units, rounded half-up.
         */
        get: operations["listTeacherSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's bookings
         * @description With no `role`, returns every booking the caller participates in (as student or as the owner of the teacher profile). `role=student` limits it to bookings the caller booked; `role=teacher` to bookings for the teacher profile the caller owns (empty if they own none). Newest lesson first. Optional `status` filter.
         */
        get: operations["listBookings"];
        put?: never;
        /**
         * Book a lesson
         * @description Creates a booking in `pending_payment` and opens a `requires_payment` payment intent for its price. The server re-derives the bookable slot set and rejects a `start_at` that is not a real, currently free slot; it never trusts a client-supplied price.
         *     `duration_minutes` must be one of 30/60/90/120. When `is_trial` is true the duration is forced to 30 minutes and the price is the teacher's `trial_price_minor` (400 if the teacher offers no trial). You cannot book your own teacher profile.
         *     The student then calls `POST /v1/bookings/{id}/pay` to authorise payment, which confirms the booking.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one booking */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay for a booking
         * @description Authorises payment for a `pending_payment` booking and, on success, moves it to `confirmed` (the payment webhook performs the transition). Student-only — only the account that booked the lesson may pay.
         *     The `method_token` is an opaque payment-method handle. The MVP ships a deterministic fake provider (Stripe does not operate in Uzbekistan); its tokens drive the outcome: `pm_ok` authorises, `pm_decline` is refused (402 `payment_failed`), `pm_capture_fail` authorises but fails the first capture at completion.
         *     Response is the booking with its embedded `payment` (now `authorized`).
         */
        post: operations["payBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a lesson
         * @description Moves a `confirmed` booking to `completed` and captures the payment, then writes the teacher's payout-ledger entry. Teacher-owner only. Allowed only once the lesson's `end_at` is in the past (409 `too_early` otherwise).
         *     Capture happens before the status flips, so a capture failure leaves the booking `confirmed` and retryable (502 `capture_failed`).
         */
        post: operations["completeBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a booking
         * @description Moves `pending_payment` or `confirmed` -> `cancelled`, recording `cancelled_at` and the optional `reason`. Participant-only. For the MVP cancellation is allowed at any time (no window / penalties yet). Already `completed` or `cancelled` -> 409.
         *     Payment side effects: an `authorized` intent is refunded in full (the hold is released); an intent that was never authorised is voided. If a payout-ledger row exists it is reversed.
         */
        post: operations["cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment provider webhook
         * @description Receives one provider state-change event. Unauthenticated — a real provider signs the body and the handler verifies the `X-Payment-Signature` header (HMAC-SHA256) when a secret is configured.
         *     Idempotent by `event_id`: the id is inserted into `payment_events` under its primary key, and a duplicate is treated as already processed. A well-formed event always returns 200, with `applied` telling whether this delivery was the one that ran the effect.
         *     Events: `payment.authorized` (payment -> authorized, booking `pending_payment` -> `confirmed`), `payment.captured` (payment -> captured, payout-ledger row `held` -> `available`), `payment.refunded` (payment -> refunded, ledger row -> `reversed`), `payment.failed` (payment -> failed).
         *     The MVP's in-process fake provider reaches the same handler code via an internal sink rather than an HTTP call.
         */
        post: operations["paymentsWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's teacher earnings summary
         * @description Aggregates the caller-owned teacher profile's payout-ledger. `held` is money captured but not yet payable, `available` is payable now (the MVP has no clearing window, so a lesson lands `available` the moment it is captured), and reversed lessons are excluded from the totals. 404 if the caller owns no teacher profile.
         */
        get: operations["getMyEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description Stable, machine-readable identifier (e.g. `not_found`). */
                code: string;
                /** @description Human-readable explanation, safe to surface to users. */
                message: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description Minimum 8 characters. */
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Fields to change on the caller's account. All optional; an omitted field is left unchanged. `email` is not editable and is ignored if sent. */
        UpdateMeRequest: {
            display_name?: string;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
        };
        /** @description The access token (hold in memory, send as `Authorization: Bearer`) plus the user. The refresh token is NOT here — it is the `ftr_session` cookie. */
        AuthResponse: {
            /** @description HS256 JWT. */
            access_token: string;
            /** @description Access-token lifetime in seconds. */
            expires_in: number;
            user: components["schemas"]["AuthUser"];
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: {
                [key: string]: "ok" | "down";
            };
        };
        /** @enum {string} */
        Currency: "UZS" | "USD";
        Money: {
            /**
             * Format: int64
             * @description Amount in minor units (tiyin / cents). 9000000 UZS == 90,000 so'm.
             */
            amount_minor: number;
            currency: components["schemas"]["Currency"];
        };
        /**
         * @description `professional` — certified/qualified teacher, structured lessons. `community` — conversation practice, informal tutoring.
         * @enum {string}
         */
        TeacherKind: "professional" | "community";
        /**
         * @default recommended
         * @enum {string}
         */
        TeacherSort: "recommended" | "price_asc" | "price_desc" | "rating_desc";
        /** @enum {string} */
        LanguageLevel: "native" | "c2" | "c1" | "b2" | "b1" | "a2" | "a1";
        Language: {
            /** @description ISO 639-1 */
            code: string;
            name: string;
            level: components["schemas"]["LanguageLevel"];
        };
        Experience: {
            title: string;
            org: string;
            /** @description Free text, e.g. "2019 – present". */
            period: string;
        };
        /** @description Card view used in search results. */
        TeacherSummary: {
            /** Format: uuid */
            id: string;
            /** @description URL-safe, stable; used in /teachers/{slug}. */
            slug: string;
            display_name: string;
            /** @description One-line hook in the teacher's own words. */
            headline: string;
            kind: components["schemas"]["TeacherKind"];
            /** @description ISO 3166-1 alpha-2 */
            country_code: string;
            country_name: string;
            city: string;
            /** @description IANA name, e.g. "Asia/Tashkent". Source of truth for slot conversion. */
            timezone: string;
            teaches: components["schemas"]["Language"][];
            also_speaks: components["schemas"]["Language"][];
            price_per_hour: components["schemas"]["Money"];
            /**
             * Format: float
             * @description Aggregate rating to one decimal.
             */
            rating: number;
            review_count: number;
            lessons_completed: number;
            student_count: number;
            /** @description Free-text focus tags, e.g. "IELTS", "Kids & teens". */
            focus: string[];
            /** @description Median hours to reply to a booking request. */
            response_time_hours: number;
            accepting_students: boolean;
            /** Format: uri */
            avatar_url: string;
            /** Format: uri */
            video_thumbnail_url: string;
        };
        /** @description Full profile — every summary field plus the long-form content. */
        TeacherProfile: components["schemas"]["TeacherSummary"] & {
            /** Format: uri */
            intro_video_url: string;
            /** @description Long-form, plain text; paragraphs separated by "\n\n". */
            about: string;
            teaching_style: string;
            experience: components["schemas"]["Experience"][];
            /** @description Present only when the teacher offers a trial lesson. */
            trial_price?: components["schemas"]["Money"];
        };
        /** @description One row of the `languages` collection in a write request. `role` splits into the read shape's `teaches` / `also_speaks` arrays. */
        LanguageEntry: {
            /** @enum {string} */
            role: "teaches" | "also_speaks";
            /** @description ISO 639-1 */
            code: string;
            name: string;
            level: components["schemas"]["LanguageLevel"];
        };
        /** @description The caller-editable profile fields shared by create and update. Money stays in integer minor units. Server-controlled aggregates (`rating`, `review_count`, `lessons_completed`, `student_count`, `response_time_hours`, `accepting_students`) and `slug` are never accepted here. */
        TeacherProfileWritable: {
            display_name?: string;
            headline?: string;
            kind?: components["schemas"]["TeacherKind"];
            /** @description ISO 3166-1 alpha-2 */
            country_code?: string;
            country_name?: string;
            city?: string;
            /** @description IANA name, e.g. "Asia/Tashkent". Must resolve via the tz database. */
            timezone?: string;
            /** Format: int64 */
            price_per_hour_minor?: number;
            /**
             * Format: int64
             * @description Omit or null for "no trial lesson offered".
             */
            trial_price_minor?: number | null;
            /** @description Must be `UZS` (the only supported currency). Defaults to `UZS` on create. */
            currency?: components["schemas"]["Currency"];
            about?: string;
            teaching_style?: string;
            avatar_url?: string;
            intro_video_url?: string;
            video_thumbnail_url?: string;
            languages?: components["schemas"]["LanguageEntry"][];
            focus?: string[];
            experience?: components["schemas"]["Experience"][];
        };
        LanguageFacet: {
            code: string;
            name: string;
            /** @description Number of teachers in the catalog who teach this language. */
            count: number;
        };
        TeacherListResult: {
            teachers: components["schemas"]["TeacherSummary"][];
            /** @description Total matches across all pages. */
            total: number;
            facets: {
                languages: components["schemas"]["LanguageFacet"][];
            };
        };
        /** @description One recurring availability span on a single weekday, in UTC. Times are minutes from 00:00 UTC (like money's minor units — an integer, never a clock string). `end_minute` is exclusive. */
        AvailabilitySlot: {
            /** @description 0 = Sunday … 6 = Saturday (matches JS `Date.getDay()`). */
            weekday: number;
            /** @description Minutes from 00:00 UTC. Multiple of `granularity_minutes`. */
            start_minute: number;
            /** @description Exclusive end, minutes from 00:00 UTC. Greater than `start_minute`. */
            end_minute: number;
        };
        /** @description A teacher's full weekly recurring availability, in UTC. */
        WeeklyAvailability: {
            teacher_slug: string;
            /** @description The teacher's IANA timezone (e.g. "Asia/Tashkent"). Use it to render the UTC slots in local time. */
            timezone: string;
            /** @description The grid every slot boundary aligns to (currently 15). */
            granularity_minutes: number;
            /** @description Ordered by weekday, then start_minute. Non-overlapping. */
            slots: components["schemas"]["AvailabilitySlot"][];
        };
        /** @description The full weekly set to store. An empty array clears availability. */
        AvailabilityReplacement: {
            slots: components["schemas"]["AvailabilitySlot"][];
        };
        /** @enum {string} */
        BookingStatus: "pending_payment" | "confirmed" | "completed" | "cancelled";
        /** @description One concrete bookable start time with its price. */
        Slot: {
            /**
             * Format: date-time
             * @description RFC3339 UTC.
             */
            start_at: string;
            /**
             * Format: date-time
             * @description RFC3339 UTC — start_at + duration.
             */
            end_at: string;
            price: components["schemas"]["Money"];
        };
        TeacherSlots: {
            teacher_slug: string;
            /** @description The teacher's IANA timezone, for display only — the slot math is pure UTC. */
            timezone: string;
            /**
             * Format: date-time
             * @description Effective window start (RFC3339 UTC).
             */
            from: string;
            /**
             * Format: date-time
             * @description Effective window end (RFC3339 UTC).
             */
            to: string;
            /** @enum {integer} */
            duration_minutes: 30 | 60 | 90 | 120;
            /** @description Ordered by start_at. */
            slots: components["schemas"]["Slot"][];
        };
        /** @description Light teacher summary embedded in a booking so lists avoid N+1 calls. */
        BookingTeacherSummary: {
            slug: string;
            display_name: string;
            /** @description IANA name. */
            timezone: string;
            avatar_url: string;
        };
        BookingStudentSummary: {
            /** Format: uuid */
            id: string;
            display_name: string;
        };
        Booking: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["BookingStatus"];
            /**
             * Format: date-time
             * @description RFC3339 UTC.
             */
            start_at: string;
            /**
             * Format: date-time
             * @description RFC3339 UTC.
             */
            end_at: string;
            duration_minutes: number;
            is_trial: boolean;
            price: components["schemas"]["Money"];
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Set when status is `cancelled`, otherwise null.
             */
            cancelled_at: string | null;
            /** @description Present (may be empty) only once cancelled; omitted otherwise. */
            cancellation_reason?: string;
            teacher: components["schemas"]["BookingTeacherSummary"];
            student: components["schemas"]["BookingStudentSummary"];
            /** @description The booking's payment intent. Null when there is none yet, and omitted from list responses (only single-booking responses embed it). */
            payment: components["schemas"]["BookingPayment"] | null;
        };
        /** @description The payment intent embedded in a booking. */
        BookingPayment: {
            /** @enum {string} */
            status: "requires_payment" | "authorized" | "captured" | "refunded" | "failed";
            /**
             * Format: int64
             * @description Integer minor units.
             */
            amount_minor: number;
            currency: string;
        };
        PayBookingRequest: {
            /** @description Opaque payment-method handle. Fake-provider tokens: `pm_ok`, `pm_decline`, `pm_capture_fail`. */
            method_token: string;
        };
        PaymentWebhookEvent: {
            /** @description Stable per state change; replaying it is a no-op. */
            event_id: string;
            /** @enum {string} */
            type: "payment.authorized" | "payment.captured" | "payment.refunded" | "payment.failed";
            /** Format: uuid */
            payment_id: string;
            /** @description The provider's reference for the intent/charge. */
            provider_ref?: string;
            /** Format: int64 */
            amount_minor?: number;
            currency?: string;
            /** @description Human-readable detail */
            message?: string;
        };
        PaymentWebhookAck: {
            received: boolean;
            /** @description True when this delivery ran the effect; false for a recognised duplicate. */
            applied: boolean;
        };
        TeacherEarnings: {
            /**
             * Format: int64
             * @description held + available (integer minor units); excludes reversed lessons.
             */
            total_earned_minor: number;
            /** Format: int64 */
            held_minor: number;
            /** Format: int64 */
            available_minor: number;
            currency: string;
            lessons: components["schemas"]["EarningLesson"][];
        };
        EarningLesson: {
            /** Format: uuid */
            booking_id: string;
            student_display_name: string;
            /**
             * Format: date-time
             * @description RFC3339 UTC.
             */
            start_at: string;
            /** Format: int64 */
            amount_minor: number;
            /** @enum {string} */
            state: "held" | "available" | "reversed";
        };
        BookingList: {
            bookings: components["schemas"]["Booking"][];
        };
        CreateBookingRequest: {
            teacher_slug: string;
            /**
             * Format: date-time
             * @description RFC3339 UTC. Must be in the future and a real bookable slot.
             */
            start_at: string;
            /**
             * @description Ignored when is_trial is true (forced to 30).
             * @enum {integer}
             */
            duration_minutes: 30 | 60 | 90 | 120;
            /**
             * @description A trial lesson — 30 minutes, priced at the teacher's trial_price.
             * @default false
             */
            is_trial: boolean;
        };
        /** @description Optional body. Omit entirely for a reason-less cancellation. */
        CancelBookingRequest: {
            reason?: string;
        };
    };
    responses: {
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication is missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller is not allowed to perform this action. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and signed in. Body carries the access token; the `ftr_session` refresh cookie is set. */
            201: {
                headers: {
                    /** @description `ftr_session=<opaque>; HttpOnly; SameSite=Lax; Path=/v1/auth` */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description That email is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. Body carries the access token; the `ftr_session` refresh cookie is set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New access token in the body; new `ftr_session` cookie set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out (cookie cleared). Returned even if no session was active. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The updated account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All backing services reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description One or more backing services are unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listTeachers: {
        parameters: {
            query?: {
                /** @description Filter to teachers who teach this language (ISO 639-1 code, e.g. `en`). */
                language?: string;
                kind?: components["schemas"]["TeacherKind"];
                /** @description Only teachers whose hourly price is at or below this amount (minor units). */
                max_price_minor?: number;
                /** @description Case-insensitive substring match across name, headline, and focus tags. */
                q?: string;
                sort?: components["schemas"]["TeacherSort"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matching teachers plus catalog-wide facets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherListResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createTeacherProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherProfileWritable"];
            };
        };
        responses: {
            /** @description The created profile (same shape as GET /v1/teachers/{slug}). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The account already has a teacher profile. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMyTeacherProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's full teacher profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTeacherBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full teacher profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherProfile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTeacherProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherProfileWritable"];
            };
        };
        responses: {
            /** @description The updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getTeacherAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The teacher's full weekly availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyAvailability"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceTeacherAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityReplacement"];
            };
        };
        responses: {
            /** @description The stored weekly availability after replacement. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyAvailability"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTeacherSlots: {
        parameters: {
            query?: {
                /** @description RFC3339 UTC. Defaults to now. */
                from?: string;
                /** @description RFC3339 UTC. Defaults to from + 14 days. Max span 21 days. */
                to?: string;
                /** @description Lesson length in minutes. */
                duration?: 30 | 60 | 90 | 120;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bookable start times in the window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherSlots"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listBookings: {
        parameters: {
            query?: {
                role?: "student" | "teacher";
                status?: components["schemas"]["BookingStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matching bookings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The created booking. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The slot is not bookable (`slot_unavailable` — outside availability, misaligned, in the past, or already taken) or was taken by a concurrent request between the check and the insert (`slot_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    payBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayBookingRequest"];
            };
        };
        responses: {
            /** @description The confirmed booking with its authorised payment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The payment method was declined (`payment_failed`). The booking stays `pending_payment`. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The caller is not the student who booked this lesson (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The booking is already paid (`already_paid`) or is cancelled (`invalid_state`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The completed booking with its captured payment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The caller is not the teacher for this lesson (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The booking is not `confirmed` (`invalid_state`) or the lesson has not ended yet (`too_early`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The provider could not capture the hold (`capture_failed`). The booking stays `confirmed`. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelBookingRequest"];
            };
        };
        responses: {
            /** @description The cancelled booking. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The booking is already completed or cancelled (`invalid_state`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    paymentsWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentWebhookEvent"];
            };
        };
        responses: {
            /** @description The event was accepted (newly applied or a recognised duplicate). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentWebhookAck"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The webhook signature did not verify. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMyEarnings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The earnings summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherEarnings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
