import type { TeacherProfile } from "@/types/teacher";

/**
 * Seed data for building the UI before the API exists.
 *
 * Market is Uzbekistan: learners are in Tashkent, most teachers are local and
 * teach English or Russian, a few teach from abroad. Prices are in UZS.
 * Photos come from deterministic placeholder services (see next.config.ts).
 * Everything else is fictional. When the real endpoints land this file is
 * deleted and `features/teachers/api.ts` points at the generated client.
 */
export const MOCK_TEACHERS: TeacherProfile[] = [
  {
    id: "t_nodira",
    slug: "nodira-karimova",
    displayName: "Nodira Karimova",
    headline: "IELTS students who freeze up in the speaking test — that's my specialty",
    avatarUrl: "https://i.pravatar.cc/240?img=45",
    videoThumbnailUrl: "https://picsum.photos/seed/nodira/640/360",
    introVideoUrl: "https://example.com/video/nodira",
    kind: "professional",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Tashkent",
    timezone: "Asia/Tashkent",
    teaches: [{ code: "en", name: "English", level: "c2" }],
    alsoSpeaks: [
      { code: "uz", name: "Uzbek", level: "native" },
      { code: "ru", name: "Russian", level: "c1" },
    ],
    pricePerHour: { amountMinor: 9_000_000, currency: "UZS" },
    trialPrice: { amountMinor: 3_000_000, currency: "UZS" },
    rating: 4.9,
    reviewCount: 214,
    lessonsCompleted: 3800,
    studentCount: 260,
    focus: ["IELTS", "Speaking", "Academic writing"],
    responseTimeHours: 1,
    acceptingStudents: true,
    about:
      "I've taught English in Tashkent for nine years, the last five focused almost entirely on IELTS. More than 200 of my students have reached the band they needed for a scholarship or a visa.\n\nMost people come to me because their speaking score won't move. We work on fluency first — getting you talking without the long pauses — then accuracy. You get a written summary and a target for the week after every lesson.",
    teachingStyle:
      "Structured but conversational. Each lesson has a clear goal tied to one of the four IELTS skills. I record your speaking answers so you can hear the difference over time. Homework is short and every lesson.",
    experience: [
      { title: "IELTS instructor", org: "Cambridge Language Centre, Tashkent", period: "2019 – present" },
      { title: "English teacher", org: "Presidential School, Tashkent", period: "2015 – 2019" },
    ],
  },
  {
    id: "t_sardor",
    slug: "sardor-yusupov",
    displayName: "Sardor Yusupov",
    headline: "Talk about your job, your week, your plans — in English, from the first lesson",
    avatarUrl: "https://i.pravatar.cc/240?img=33",
    videoThumbnailUrl: "https://picsum.photos/seed/sardor/640/360",
    introVideoUrl: "https://example.com/video/sardor",
    kind: "community",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Tashkent",
    timezone: "Asia/Tashkent",
    teaches: [{ code: "en", name: "English", level: "c1" }],
    alsoSpeaks: [
      { code: "uz", name: "Uzbek", level: "native" },
      { code: "ru", name: "Russian", level: "c2" },
    ],
    pricePerHour: { amountMinor: 5_500_000, currency: "UZS" },
    trialPrice: { amountMinor: 2_000_000, currency: "UZS" },
    rating: 4.7,
    reviewCount: 96,
    lessonsCompleted: 1720,
    studentCount: 140,
    focus: ["Conversational", "Business English", "Interview prep"],
    responseTimeHours: 3,
    acceptingStudents: true,
    about:
      "I work in IT project management and use English every day with clients abroad. I started tutoring because I remember how useless it felt to know grammar rules but not be able to hold a call.\n\nThese are speaking-focused sessions for people who already have some English and need to actually use it — at work, in interviews, while travelling.",
    teachingStyle:
      "We talk the whole hour. I take notes on the mistakes that get in the way of being understood and we review them at the end. I'll push you to explain things, not just answer yes or no.",
    experience: [
      { title: "IT project manager", org: "EPAM Uzbekistan", period: "2018 – present" },
      { title: "Conversation tutor", org: "Independent", period: "2021 – present" },
    ],
  },
  {
    id: "t_elena",
    slug: "elena-kim",
    displayName: "Elena Kim",
    headline: "Russian for school and university, explained the way it finally clicks",
    avatarUrl: "https://i.pravatar.cc/240?img=47",
    videoThumbnailUrl: "https://picsum.photos/seed/elena/640/360",
    introVideoUrl: "https://example.com/video/elena",
    kind: "professional",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Tashkent",
    timezone: "Asia/Tashkent",
    teaches: [{ code: "ru", name: "Russian", level: "native" }],
    alsoSpeaks: [
      { code: "uz", name: "Uzbek", level: "c1" },
      { code: "en", name: "English", level: "b2" },
    ],
    pricePerHour: { amountMinor: 7_000_000, currency: "UZS" },
    trialPrice: { amountMinor: 2_500_000, currency: "UZS" },
    rating: 4.9,
    reviewCount: 158,
    lessonsCompleted: 4300,
    studentCount: 190,
    focus: ["University prep", "Grammar", "Writing"],
    responseTimeHours: 2,
    acceptingStudents: true,
    about:
      "I taught Russian language and literature in a Tashkent school for fifteen years before moving to tutoring full time.\n\nMy students are mostly teenagers preparing for university entrance and adults who need clearer, more correct Russian for work. We build from wherever you are — no lesson assumes you remember something we haven't covered.",
    teachingStyle:
      "Calm and thorough. I explain a rule, we practise it in speech and in writing, and I don't move on until it's solid. I send a short grammar reference after each topic so you can review offline.",
    experience: [
      { title: "Russian language teacher", org: "School No. 110, Tashkent", period: "2007 – 2022" },
      { title: "Private tutor", org: "Independent", period: "2022 – present" },
    ],
  },
  {
    id: "t_dilnoza",
    slug: "dilnoza-abdullayeva",
    displayName: "Dilnoza Abdullayeva",
    headline: "Patient English lessons for kids who'd rather be doing anything else",
    avatarUrl: "https://i.pravatar.cc/240?img=31",
    videoThumbnailUrl: "https://picsum.photos/seed/dilnoza/640/360",
    introVideoUrl: "https://example.com/video/dilnoza",
    kind: "professional",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Samarkand",
    timezone: "Asia/Samarkand",
    teaches: [{ code: "en", name: "English", level: "c1" }],
    alsoSpeaks: [
      { code: "uz", name: "Uzbek", level: "native" },
      { code: "ru", name: "Russian", level: "b2" },
    ],
    pricePerHour: { amountMinor: 6_500_000, currency: "UZS" },
    trialPrice: { amountMinor: 2_000_000, currency: "UZS" },
    rating: 4.8,
    reviewCount: 122,
    lessonsCompleted: 2600,
    studentCount: 110,
    focus: ["Kids & teens", "Beginners", "Cambridge YLE"],
    responseTimeHours: 4,
    acceptingStudents: true,
    about:
      "I specialise in learners aged 7 to 15. I have a teaching degree and a CELT-P certificate for teaching young learners.\n\nLessons use games, stories, and a lot of pictures. Parents get a short message after each lesson so you know what we did and how it went.",
    teachingStyle:
      "Playful and consistent. Short activities, frequent changes of pace, praise for effort. For teens I bring in music, football, and YouTube so the English feels worth learning.",
    experience: [
      { title: "Primary English teacher", org: "Fidokor School, Samarkand", period: "2016 – present" },
      { title: "CELT-P (young learners)", org: "British Council", period: "2018" },
    ],
  },
  {
    id: "t_jasur",
    slug: "jasur-rakhimov",
    displayName: "Jasur Rakhimov",
    headline: "We fix the grammar mistakes that quietly cost you marks on the exam",
    avatarUrl: "https://i.pravatar.cc/240?img=52",
    videoThumbnailUrl: "https://picsum.photos/seed/jasur/640/360",
    introVideoUrl: "https://example.com/video/jasur",
    kind: "community",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Namangan",
    timezone: "Asia/Tashkent",
    teaches: [{ code: "en", name: "English", level: "c1" }],
    alsoSpeaks: [
      { code: "uz", name: "Uzbek", level: "native" },
      { code: "ru", name: "Russian", level: "b1" },
    ],
    pricePerHour: { amountMinor: 4_500_000, currency: "UZS" },
    rating: 4.6,
    reviewCount: 71,
    lessonsCompleted: 1180,
    studentCount: 95,
    focus: ["Grammar", "Exam prep", "CEFR A2–B1"],
    responseTimeHours: 8,
    acceptingStudents: true,
    about:
      "I'm a final-year linguistics student and I've been tutoring school and university students for four years.\n\nMost of my students are getting ready for a placement test or a national exam and keep losing points on the same few things — tenses, articles, prepositions. We drill those until they're automatic.",
    teachingStyle:
      "Explanation, then a lot of practice. I use error correction from your own writing rather than generic worksheets. Homework every lesson, checked at the start of the next one.",
    experience: [
      { title: "Linguistics student", org: "Namangan State University", period: "2021 – present" },
      { title: "English tutor", org: "Independent", period: "2020 – present" },
    ],
  },
  {
    id: "t_aziza",
    slug: "aziza-tosheva",
    displayName: "Aziza Tosheva",
    headline: "German is logical once someone shows you the pattern — I'll show you",
    avatarUrl: "https://i.pravatar.cc/240?img=44",
    videoThumbnailUrl: "https://picsum.photos/seed/aziza/640/360",
    introVideoUrl: "https://example.com/video/aziza",
    kind: "professional",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Tashkent",
    timezone: "Asia/Tashkent",
    teaches: [{ code: "de", name: "German", level: "c1" }],
    alsoSpeaks: [
      { code: "uz", name: "Uzbek", level: "native" },
      { code: "ru", name: "Russian", level: "c1" },
      { code: "en", name: "English", level: "b2" },
    ],
    pricePerHour: { amountMinor: 8_500_000, currency: "UZS" },
    trialPrice: { amountMinor: 3_000_000, currency: "UZS" },
    rating: 4.9,
    reviewCount: 84,
    lessonsCompleted: 1600,
    studentCount: 90,
    focus: ["Goethe exam", "A1–B2", "Studying in Germany"],
    responseTimeHours: 5,
    acceptingStudents: false,
    about:
      "I studied for a master's degree in Cologne and now teach German to people planning the same move — for an Ausbildung, a university place, or the Blue Card.\n\nWe follow a clear A1-to-B2 path and prepare specifically for the Goethe or telc exam you need.",
    teachingStyle:
      "Systematic. I teach grammar in patterns and colours, not long lists. Lots of speaking practice about real situations: renting a flat, registering at the Bürgeramt, a job interview.",
    experience: [
      { title: "M.A., Media Studies", org: "University of Cologne", period: "2016 – 2018" },
      { title: "German instructor", org: "DeutschKlub Tashkent", period: "2019 – present" },
    ],
  },
  {
    id: "t_minjun",
    slug: "kim-min-jun",
    displayName: "Kim Min-jun",
    headline: "From the K-drama phrases you already know to real conversation — and TOPIK if you want it",
    avatarUrl: "https://i.pravatar.cc/240?img=68",
    videoThumbnailUrl: "https://picsum.photos/seed/minjun/640/360",
    introVideoUrl: "https://example.com/video/minjun",
    kind: "professional",
    countryCode: "KR",
    countryName: "South Korea",
    city: "Seoul",
    timezone: "Asia/Seoul",
    teaches: [{ code: "ko", name: "Korean", level: "native" }],
    alsoSpeaks: [{ code: "en", name: "English", level: "c1" }],
    pricePerHour: { amountMinor: 11_000_000, currency: "UZS" },
    trialPrice: { amountMinor: 4_000_000, currency: "UZS" },
    rating: 4.8,
    reviewCount: 133,
    lessonsCompleted: 2900,
    studentCount: 180,
    focus: ["TOPIK", "Speaking", "Hangul & pronunciation"],
    responseTimeHours: 6,
    acceptingStudents: true,
    about:
      "I'm a certified Korean teacher in Seoul with students in a dozen countries, including a growing group in Uzbekistan.\n\nWhether you're learning for K-content, for work with Korean companies, or to study in Korea, we start with solid Hangul and pronunciation so bad habits never set in.",
    teachingStyle:
      "Immersive but supported. I speak mostly Korean from early on, with English when it saves time. Shared slides for every grammar point and a flashcard deck after each lesson.",
    experience: [
      { title: "Certified Korean language instructor", org: "Sejong Institute", period: "2017 – present" },
    ],
  },
  {
    id: "t_mehmet",
    slug: "mehmet-demir",
    displayName: "Mehmet Demir",
    headline: "Relaxed Turkish conversation — bring a coffee, we'll just talk",
    avatarUrl: "https://i.pravatar.cc/240?img=59",
    videoThumbnailUrl: "https://picsum.photos/seed/mehmet/640/360",
    introVideoUrl: "https://example.com/video/mehmet",
    kind: "community",
    countryCode: "TR",
    countryName: "Türkiye",
    city: "Istanbul",
    timezone: "Europe/Istanbul",
    teaches: [{ code: "tr", name: "Turkish", level: "native" }],
    alsoSpeaks: [
      { code: "en", name: "English", level: "b2" },
      { code: "ru", name: "Russian", level: "b1" },
    ],
    pricePerHour: { amountMinor: 6_000_000, currency: "UZS" },
    trialPrice: { amountMinor: 2_000_000, currency: "UZS" },
    rating: 4.7,
    reviewCount: 58,
    lessonsCompleted: 940,
    studentCount: 80,
    focus: ["Conversational", "Travel", "Uzbek speakers"],
    responseTimeHours: 5,
    acceptingStudents: true,
    about:
      "I'm a graphic designer in Istanbul and I love that Uzbek and Turkish are close enough to get a real conversation going in the first lesson.\n\nThese are casual speaking sessions. Bring a topic or let me pick one. I'll point out the false friends between our languages so they stop tripping you up.",
    teachingStyle:
      "Casual and patient. We talk, I correct what matters, and I keep a running list of new words that I send you afterwards.",
    experience: [
      { title: "Conversation tutor", org: "Independent", period: "2022 – present" },
    ],
  },
  {
    id: "t_kamola",
    slug: "kamola-sattorova",
    displayName: "Kamola Sattorova",
    headline: "Uzbek for people who just moved to Tashkent and want to stop pointing at menus",
    avatarUrl: "https://i.pravatar.cc/240?img=24",
    videoThumbnailUrl: "https://picsum.photos/seed/kamola/640/360",
    introVideoUrl: "https://example.com/video/kamola",
    kind: "professional",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Tashkent",
    timezone: "Asia/Tashkent",
    teaches: [{ code: "uz", name: "Uzbek", level: "native" }],
    alsoSpeaks: [
      { code: "ru", name: "Russian", level: "native" },
      { code: "en", name: "English", level: "c1" },
    ],
    pricePerHour: { amountMinor: 7_500_000, currency: "UZS" },
    trialPrice: { amountMinor: 2_500_000, currency: "UZS" },
    rating: 4.9,
    reviewCount: 76,
    lessonsCompleted: 1340,
    studentCount: 85,
    focus: ["Beginners", "Everyday Uzbek", "Newcomers to Tashkent"],
    responseTimeHours: 2,
    acceptingStudents: true,
    about:
      "I have a degree in Uzbek philology and I've spent the last six years teaching the language to diplomats, NGO staff, and people who married into an Uzbek family.\n\nWe start with the survival phrases you need this week — the bazaar, the taxi, your neighbours — and build grammar around them so it never feels abstract.",
    teachingStyle:
      "Practical and warm. Lots of role-play from real situations you'll face. I teach the spoken Tashkent variety first and point out where the textbook written form differs.",
    experience: [
      { title: "Uzbek language instructor", org: "Internews / diplomatic missions, Tashkent", period: "2019 – present" },
      { title: "B.A., Uzbek Philology", org: "National University of Uzbekistan", period: "2013 – 2017" },
    ],
  },
  {
    id: "t_bekzod",
    slug: "bekzod-ergashev",
    displayName: "Bekzod Ergashev",
    headline: "Reconnect with Uzbek — for anyone who understood their grandparents but never spoke back",
    avatarUrl: "https://i.pravatar.cc/240?img=13",
    videoThumbnailUrl: "https://picsum.photos/seed/bekzod/640/360",
    introVideoUrl: "https://example.com/video/bekzod",
    kind: "community",
    countryCode: "UZ",
    countryName: "Uzbekistan",
    city: "Andijan",
    timezone: "Asia/Tashkent",
    teaches: [{ code: "uz", name: "Uzbek", level: "native" }],
    alsoSpeaks: [
      { code: "ru", name: "Russian", level: "c1" },
      { code: "en", name: "English", level: "b1" },
    ],
    pricePerHour: { amountMinor: 5_000_000, currency: "UZS" },
    trialPrice: { amountMinor: 1_500_000, currency: "UZS" },
    rating: 4.7,
    reviewCount: 44,
    lessonsCompleted: 720,
    studentCount: 60,
    focus: ["Conversational", "Heritage speakers", "Fergana dialect"],
    responseTimeHours: 7,
    acceptingStudents: true,
    about:
      "I'm a history teacher in Andijan. Most of my online students grew up abroad in Uzbek families and can follow a conversation but freeze when it's their turn.\n\nNo grammar drills unless you ask. We talk about family, food, and where your relatives are from, and your speaking comes back faster than you'd think.",
    teachingStyle:
      "Gentle and conversational. I speak slowly, repeat a lot, and never make you feel behind. I'll write down the words you reach for in Russian or English so you have them next time.",
    experience: [
      { title: "History teacher", org: "School No. 24, Andijan", period: "2015 – present" },
      { title: "Uzbek conversation tutor", org: "Independent", period: "2021 – present" },
    ],
  },
];
